In [1]:
print("Hello")

Hello

In [ ]:
# ============================================================
# 05_stage5_master_rgb_singlecell.ipynb
# ONE-CELL, RESUMABLE, STABLE STAGE-5 RGB BENCHMARK
# ============================================================

import os
import gc
import json
import time
import copy
import math
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision.models import (
    resnet18, ResNet18_Weights,
    efficientnet_b0, EfficientNet_B0_Weights,
    mobilenet_v3_small, MobileNet_V3_Small_Weights,
)

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 300)

# ============================================================
# 1. SETTINGS
# ============================================================
SEED = 42

IMG_SIZE = 224
NUM_SAMPLE_FRAMES = 32

# 400 is not practical here. Use stable values.
BATCH_SIZE_BY_MODEL = {
    "resnet18": 24,
    "efficientnet_b0": 16,
    "mobilenet_v3_small": 32,
}

EPOCHS = 12
LR = 1e-4
WEIGHT_DECAY = 1e-4
PATIENCE = 4

USE_AMP = True
USE_PRETRAINED = True

# Jupyter-safe
NUM_WORKERS = 0
PIN_MEMORY = False

# Optional quick debugging
LIMIT_TRAIN = None
LIMIT_VAL = None
LIMIT_TEST = None

# Smart sampling from middle useful region
SAMPLE_START_FRAC = 0.10
SAMPLE_END_FRAC = 0.90

# Resume / skip finished runs automatically
SKIP_IF_METRICS_EXISTS = True

# Run all Stage 5 combinations
FRAME_SOURCES = [
    "RGB",
    "RGB_BGREM",
]

MODELS_TO_RUN = [
    "resnet18",
    "efficientnet_b0",
    "mobilenet_v3_small",
]

# protocol_name, train_csv, val_csv, test_csv
SPLIT_CONFIGS = [
    ("protocol_A",          "protocol_A_train.csv",          "protocol_A_val.csv",          "protocol_A_test.csv"),
    ("protocol_B_4_to_8",   "protocol_B_train_4_test_8.csv", None,                          "protocol_B_test_8.csv"),
    ("protocol_B_8_to_4",   "protocol_B_train_8_test_4.csv", None,                          "protocol_B_test_4.csv"),
    ("protocol_B_4_6_to_8", "protocol_B_train_4_6_test_8.csv", None,                        "protocol_B_test_8_from_4_6.csv"),
    ("protocol_B_4_8_to_6", "protocol_B_train_4_8_test_6.csv", None,                        "protocol_B_test_6_from_4_8.csv"),
    ("protocol_B_6_8_to_4", "protocol_B_train_6_8_test_4.csv", None,                        "protocol_B_test_4_from_6_8.csv"),
]

CLASS_NAMES = [
    "doctor",
    "emergency",
    "fire",
    "help",
    "robbery",
    "sit_down",
    "stand_up",
]
label2id = {c: i for i, c in enumerate(CLASS_NAMES)}
id2label = {i: c for c, i in label2id.items()}
NUM_CLASSES = len(CLASS_NAMES)

# ============================================================
# 2. REPRODUCIBILITY
# ============================================================
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(SEED)

# ============================================================
# 3. PATHS
# ============================================================
cwd = Path.cwd()
ROOT = cwd.parent if cwd.name == "notebooks" else cwd

SPLIT_DIR = ROOT / "data" / "processed" / "splits"
MANIFEST_DIR = ROOT / "data" / "processed" / "manifests"

RESULTS_ROOT = ROOT / "results" / "stage5_rgb_master"
CHECKPOINT_ROOT = ROOT / "checkpoints" / "stage5_rgb_master"
LOG_ROOT = ROOT / "logs" / "stage5_rgb_master"

RESULTS_ROOT.mkdir(parents=True, exist_ok=True)
CHECKPOINT_ROOT.mkdir(parents=True, exist_ok=True)
LOG_ROOT.mkdir(parents=True, exist_ok=True)

FRAME_SUMMARY_CSV = MANIFEST_DIR / "frame_extraction_trimmed_summary.csv"
if not FRAME_SUMMARY_CSV.exists():
    raise FileNotFoundError(f"Missing file: {FRAME_SUMMARY_CSV}")

print("ROOT:", ROOT)
print("FRAME_SUMMARY_CSV:", FRAME_SUMMARY_CSV)
print("CLASS_NAMES:", CLASS_NAMES)

# ============================================================
# 4. DEVICE
# ============================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
torch.backends.cudnn.benchmark = False

# ============================================================
# 5. FRAME SUMMARY
# ============================================================
frame_df_all = pd.read_csv(FRAME_SUMMARY_CSV)
frame_df_all = frame_df_all[frame_df_all["status"] == "success"].copy()
frame_df_all = frame_df_all[["pair_id", "modality", "output_dir", "frames_extracted"]].drop_duplicates()

# ============================================================
# 6. HELPERS
# ============================================================
def sample_indices_middle_region(n_total, n_samples, start_frac=0.10, end_frac=0.90):
    if n_total <= 0:
        return [0] * n_samples

    start_idx = int(round(start_frac * (n_total - 1)))
    end_idx = int(round(end_frac * (n_total - 1)))

    start_idx = max(0, min(start_idx, n_total - 1))
    end_idx = max(start_idx, min(end_idx, n_total - 1))

    idxs = np.linspace(start_idx, end_idx, n_samples)
    idxs = np.round(idxs).astype(int)
    return np.clip(idxs, 0, n_total - 1).tolist()

def frame_index_to_path(frame_dir, idx):
    return Path(frame_dir) / f"frame_{idx+1:06d}.jpg"

def load_split_df(csv_name):
    csv_path = SPLIT_DIR / csv_name
    if not csv_path.exists():
        raise FileNotFoundError(f"Missing split file: {csv_path}")
    df = pd.read_csv(csv_path)
    if "is_valid_pair" in df.columns:
        df = df[df["is_valid_pair"] == True].copy()
    return df.reset_index(drop=True)

def attach_labels(df_):
    out = df_.copy()
    out = out[out["gesture"].isin(CLASS_NAMES)].copy()
    out["label"] = out["gesture"].map(label2id)
    return out.reset_index(drop=True)

def attach_frame_info(df_, frame_source):
    sub = frame_df_all[frame_df_all["modality"] == frame_source].copy()
    sub = sub.rename(columns={
        "output_dir": "frame_dir",
        "frames_extracted": "num_frames_available"
    })
    sub = sub[["pair_id", "frame_dir", "num_frames_available"]].drop_duplicates()

    out = df_.merge(sub, on="pair_id", how="left")
    out = out[out["num_frames_available"].fillna(0) > 0].copy().reset_index(drop=True)
    out["num_frames_available"] = out["num_frames_available"].astype(int)
    return out

# ============================================================
# 7. TRANSFORMS
# ============================================================
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    ),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    ),
])

# ============================================================
# 8. DATASET
# ============================================================
class FrameVotingDataset(Dataset):
    def __init__(self, df, transform, num_sample_frames=32, start_frac=0.10, end_frac=0.90):
        self.df = df.reset_index(drop=True).copy()
        self.transform = transform
        self.sampled_paths = []

        for _, row in self.df.iterrows():
            idxs = sample_indices_middle_region(
                int(row["num_frames_available"]),
                num_sample_frames,
                start_frac,
                end_frac
            )
            self.sampled_paths.append([frame_index_to_path(row["frame_dir"], i) for i in idxs])

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        paths = self.sampled_paths[idx]

        frames = []
        for p in paths:
            try:
                with Image.open(p) as f:
                    img = f.convert("RGB")
            except Exception:
                img = Image.fromarray(np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8))
            frames.append(self.transform(img))

        frames = torch.stack(frames, dim=0)
        label = int(row["label"])

        meta = {
            "pair_id": row["pair_id"],
            "subject_id": row["subject_id"],
            "distance": row["distance"],
            "gesture": row["gesture"],
            "frame_dir": row["frame_dir"],
        }
        return frames, label, meta

def collate_fn(batch):
    frames = torch.stack([x[0] for x in batch], dim=0)
    labels = torch.tensor([x[1] for x in batch], dtype=torch.long)
    metas = [x[2] for x in batch]
    return frames, labels, metas

# ============================================================
# 9. MODEL FACTORY
# ============================================================
def create_model(model_name, num_classes, use_pretrained=True):
    if model_name == "resnet18":
        model = resnet18(weights=ResNet18_Weights.DEFAULT if use_pretrained else None)
        model.fc = nn.Linear(model.fc.in_features, num_classes)

    elif model_name == "efficientnet_b0":
        model = efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT if use_pretrained else None)
        model.classifier[1] = nn.Linear(model.classifier[1].in_features, num_classes)

    elif model_name == "mobilenet_v3_small":
        model = mobilenet_v3_small(weights=MobileNet_V3_Small_Weights.DEFAULT if use_pretrained else None)
        model.classifier[3] = nn.Linear(model.classifier[3].in_features, num_classes)

    else:
        raise ValueError(f"Unsupported model: {model_name}")

    return model

def forward_video_voting(model, frames):
    B, T, C, H, W = frames.shape
    frames = frames.view(B * T, C, H, W)
    frame_logits = model(frames)
    frame_logits = frame_logits.view(B, T, -1)
    video_logits = frame_logits.mean(dim=1)
    return video_logits

# ============================================================
# 10. TRAIN / EVAL
# ============================================================
def run_one_epoch(model, loader, criterion, optimizer=None, scaler=None, train=True):
    model.train() if train else model.eval()

    total_loss = 0.0
    all_labels = []
    all_preds = []

    for frames, labels, metas in loader:
        frames, labels = frames.to(device), labels.to(device)

        if train:
            optimizer.zero_grad(set_to_none=True)

        with torch.set_grad_enabled(train):
            with torch.autocast(
                device_type="cuda",
                dtype=torch.float16,
                enabled=(USE_AMP and device.type == "cuda")
            ):
                video_logits = forward_video_voting(model, frames)
                loss = criterion(video_logits, labels)

            if train:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()

        preds = video_logits.argmax(dim=1)

        total_loss += loss.item() * labels.size(0)
        all_labels.extend(labels.detach().cpu().numpy().tolist())
        all_preds.extend(preds.detach().cpu().numpy().tolist())

    return {
        "loss": total_loss / len(loader.dataset),
        "accuracy": accuracy_score(all_labels, all_preds),
        "macro_f1": f1_score(all_labels, all_preds, average="macro"),
        "weighted_f1": f1_score(all_labels, all_preds, average="weighted"),
    }

@torch.no_grad()
def predict_with_metadata(model, loader):
    model.eval()

    all_labels = []
    all_preds = []
    rows = []

    start_time = time.time()
    total_samples = 0

    for frames, labels, metas in loader:
        frames, labels = frames.to(device), labels.to(device)

        with torch.autocast(
            device_type="cuda",
            dtype=torch.float16,
            enabled=(USE_AMP and device.type == "cuda")
        ):
            video_logits = forward_video_voting(model, frames)
            probs = torch.softmax(video_logits, dim=1)
            preds = probs.argmax(dim=1)

        probs_np = probs.detach().cpu().numpy()
        preds_np = preds.detach().cpu().numpy()
        labels_np = labels.detach().cpu().numpy()

        total_samples += len(labels_np)

        all_labels.extend(labels_np.tolist())
        all_preds.extend(preds_np.tolist())

        for i, meta in enumerate(metas):
            row = {
                "pair_id": meta["pair_id"],
                "subject_id": meta["subject_id"],
                "distance": meta["distance"],
                "gesture_true": id2label[int(labels_np[i])],
                "gesture_pred": id2label[int(preds_np[i])],
                "frame_dir": meta["frame_dir"],
            }
            for c_idx, c_name in id2label.items():
                row[f"prob_{c_name}"] = float(probs_np[i][c_idx])
            rows.append(row)

    elapsed = time.time() - start_time
    videos_per_sec = total_samples / elapsed if elapsed > 0 else None
    return all_labels, all_preds, pd.DataFrame(rows), elapsed, videos_per_sec

# ============================================================
# 11. RUN ONE EXPERIMENT
# ============================================================
def run_experiment(protocol_name, train_csv_name, val_csv_name, test_csv_name, frame_source, model_name):
    print("\n" + "=" * 100)
    print(f"RUNNING | protocol={protocol_name} | frame_source={frame_source} | model={model_name}")
    print("=" * 100)

    train_df = load_split_df(train_csv_name)
    test_df = load_split_df(test_csv_name)

    if val_csv_name is None:
        train_df = train_df.sample(frac=1.0, random_state=SEED).reset_index(drop=True)
        n_val = max(1, int(0.10 * len(train_df)))
        val_df = train_df.iloc[:n_val].copy().reset_index(drop=True)
        train_df = train_df.iloc[n_val:].copy().reset_index(drop=True)
    else:
        val_df = load_split_df(val_csv_name)

    if LIMIT_TRAIN is not None:
        train_df = train_df.head(LIMIT_TRAIN).copy()
    if LIMIT_VAL is not None:
        val_df = val_df.head(LIMIT_VAL).copy()
    if LIMIT_TEST is not None:
        test_df = test_df.head(LIMIT_TEST).copy()

    train_df = attach_labels(train_df)
    val_df = attach_labels(val_df)
    test_df = attach_labels(test_df)

    train_df = attach_frame_info(train_df, frame_source)
    val_df = attach_frame_info(val_df, frame_source)
    test_df = attach_frame_info(test_df, frame_source)

    print(f"train={len(train_df)}, val={len(val_df)}, test={len(test_df)}")

    batch_size = BATCH_SIZE_BY_MODEL[model_name]

    train_loader = DataLoader(
        FrameVotingDataset(train_df, train_transform, NUM_SAMPLE_FRAMES, SAMPLE_START_FRAC, SAMPLE_END_FRAC),
        batch_size=batch_size,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        collate_fn=collate_fn
    )
    val_loader = DataLoader(
        FrameVotingDataset(val_df, eval_transform, NUM_SAMPLE_FRAMES, SAMPLE_START_FRAC, SAMPLE_END_FRAC),
        batch_size=batch_size,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        collate_fn=collate_fn
    )
    test_loader = DataLoader(
        FrameVotingDataset(test_df, eval_transform, NUM_SAMPLE_FRAMES, SAMPLE_START_FRAC, SAMPLE_END_FRAC),
        batch_size=batch_size,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        collate_fn=collate_fn
    )

    run_name = f"{protocol_name}__{frame_source.lower()}__{model_name}__f{NUM_SAMPLE_FRAMES}__img{IMG_SIZE}"
    results_dir = RESULTS_ROOT / run_name
    checkpoint_dir = CHECKPOINT_ROOT / run_name
    log_dir = LOG_ROOT / run_name

    results_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)

    metrics_json = results_dir / "metrics.json"
    if SKIP_IF_METRICS_EXISTS and metrics_json.exists():
        print("Skipping, already finished:", run_name)
        with open(metrics_json, "r") as f:
            return json.load(f)

    model = create_model(model_name, NUM_CLASSES, use_pretrained=USE_PRETRAINED).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    scaler = torch.amp.GradScaler("cuda", enabled=(USE_AMP and device.type == "cuda"))

    best_val_f1 = -1.0
    best_epoch = -1
    epochs_without_improvement = 0
    history = []

    best_ckpt_path = checkpoint_dir / "best_model.pt"
    best_state_dict = None

    train_start = time.time()

    for epoch in range(1, EPOCHS + 1):
        train_metrics = run_one_epoch(model, train_loader, criterion, optimizer, scaler, train=True)
        val_metrics = run_one_epoch(model, val_loader, criterion, optimizer=None, scaler=scaler, train=False)

        history.append({
            "epoch": epoch,
            "train_loss": train_metrics["loss"],
            "train_acc": train_metrics["accuracy"],
            "train_macro_f1": train_metrics["macro_f1"],
            "train_weighted_f1": train_metrics["weighted_f1"],
            "val_loss": val_metrics["loss"],
            "val_acc": val_metrics["accuracy"],
            "val_macro_f1": val_metrics["macro_f1"],
            "val_weighted_f1": val_metrics["weighted_f1"],
        })

        print(
            f"Epoch {epoch:02d} | "
            f"train_macro_f1={train_metrics['macro_f1']:.4f} | "
            f"val_macro_f1={val_metrics['macro_f1']:.4f}"
        )

        if val_metrics["macro_f1"] > best_val_f1:
            best_val_f1 = val_metrics["macro_f1"]
            best_epoch = epoch
            epochs_without_improvement = 0
            best_state_dict = copy.deepcopy(model.state_dict())
            torch.save({
                "epoch": epoch,
                "model_state_dict": best_state_dict,
                "model_name": model_name,
                "frame_source": frame_source,
                "protocol_name": protocol_name,
                "label2id": label2id,
                "id2label": id2label,
            }, best_ckpt_path)
        else:
            epochs_without_improvement += 1

        if epochs_without_improvement >= PATIENCE:
            print("Early stopping triggered.")
            break

    train_elapsed = time.time() - train_start
    pd.DataFrame(history).to_csv(log_dir / "training_log.csv", index=False)

    if best_state_dict is None:
        raise RuntimeError("No best model was saved.")

    model.load_state_dict(best_state_dict)

    test_labels, test_preds, pred_df, infer_elapsed, videos_per_sec = predict_with_metadata(model, test_loader)

    test_acc = accuracy_score(test_labels, test_preds)
    test_macro_f1 = f1_score(test_labels, test_preds, average="macro")
    test_weighted_f1 = f1_score(test_labels, test_preds, average="weighted")

    cm = confusion_matrix(test_labels, test_preds)
    report_dict = classification_report(
        test_labels,
        test_preds,
        target_names=[id2label[i] for i in range(NUM_CLASSES)],
        output_dict=True,
        zero_division=0
    )
    report_df = pd.DataFrame(report_dict).transpose()

    pred_csv = results_dir / "test_predictions.csv"
    report_csv = results_dir / "classification_report.csv"
    cm_png = results_dir / "confusion_matrix.png"

    pred_df.to_csv(pred_csv, index=False)
    report_df.to_csv(report_csv)

    plt.figure(figsize=(8, 6))
    plt.imshow(cm, interpolation="nearest")
    plt.title(f"{protocol_name} | {frame_source} | {model_name}")
    plt.colorbar()
    ticks = np.arange(NUM_CLASSES)
    plt.xticks(ticks, [id2label[i] for i in range(NUM_CLASSES)], rotation=45, ha="right")
    plt.yticks(ticks, [id2label[i] for i in range(NUM_CLASSES)])
    plt.xlabel("Predicted")
    plt.ylabel("True")
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, str(cm[i, j]), ha="center", va="center")
    plt.tight_layout()
    plt.savefig(cm_png, dpi=200, bbox_inches="tight")
    plt.close()

    per_class_f1 = {}
    for cls in CLASS_NAMES:
        if cls in report_df.index:
            per_class_f1[cls] = float(report_df.loc[cls, "f1-score"])

    metrics = {
        "protocol_name": protocol_name,
        "frame_source": frame_source,
        "model_name": model_name,
        "num_sample_frames": NUM_SAMPLE_FRAMES,
        "batch_size": batch_size,
        "best_epoch": int(best_epoch),
        "best_val_macro_f1": float(best_val_f1),
        "test_accuracy": float(test_acc),
        "test_macro_f1": float(test_macro_f1),
        "test_weighted_f1": float(test_weighted_f1),
        "per_class_f1": per_class_f1,
        "train_time_minutes": float(train_elapsed / 60.0),
        "inference_time_seconds": float(infer_elapsed),
        "videos_per_second": float(videos_per_sec) if videos_per_sec is not None else None,
        "train_rows": int(len(train_df)),
        "val_rows": int(len(val_df)),
        "test_rows": int(len(test_df)),
        "predictions_csv": str(pred_csv),
        "classification_report_csv": str(report_csv),
        "confusion_matrix_png": str(cm_png),
        "checkpoint_best": str(best_ckpt_path),
    }

    with open(metrics_json, "w") as f:
        json.dump(metrics, f, indent=4)

    print(json.dumps(metrics, indent=2))

    del model, train_loader, val_loader, test_loader, best_state_dict
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return metrics

# ============================================================
# 12. RUN ALL EXPERIMENTS
# ============================================================
summary_csv = RESULTS_ROOT / "stage5_rgb_master_summary.csv"

all_metrics = []
if summary_csv.exists():
    try:
        prev = pd.read_csv(summary_csv)
        all_metrics = prev.to_dict(orient="records")
    except Exception:
        all_metrics = []

done_keys = set()
for m in all_metrics:
    done_keys.add((m["protocol_name"], m["frame_source"], m["model_name"]))

for frame_source in FRAME_SOURCES:
    for protocol_name, train_csv_name, val_csv_name, test_csv_name in SPLIT_CONFIGS:
        for model_name in MODELS_TO_RUN:
            key = (protocol_name, frame_source, model_name)
            if SKIP_IF_METRICS_EXISTS and key in done_keys:
                print("Already in summary, skipping:", key)
                continue

            metrics = run_experiment(
                protocol_name=protocol_name,
                train_csv_name=train_csv_name,
                val_csv_name=val_csv_name,
                test_csv_name=test_csv_name,
                frame_source=frame_source,
                model_name=model_name
            )
            all_metrics.append(metrics)
            done_keys.add(key)

            pd.DataFrame(all_metrics).to_csv(summary_csv, index=False)

final_df = pd.DataFrame(all_metrics)
final_df.to_csv(summary_csv, index=False)

print("\nDONE.")
print("Saved summary to:", summary_csv)
display(
    final_df[[
        "protocol_name",
        "frame_source",
        "model_name",
        "best_val_macro_f1",
        "test_accuracy",
        "test_macro_f1",
        "test_weighted_f1",
        "train_time_minutes",
        "videos_per_second"
    ]].sort_values(["protocol_name", "frame_source", "test_macro_f1"], ascending=[True, True, False])
)

ROOT: /data/Sajjan_Singh/gesture_recognition
FRAME_SUMMARY_CSV: /data/Sajjan_Singh/gesture_recognition/data/processed/manifests/frame_extraction_trimmed_summary.csv
CLASS_NAMES: ['doctor', 'emergency', 'fire', 'help', 'robbery', 'sit_down', 'stand_up']
Using device: cuda
GPU name: NVIDIA H100 NVL

====================================================================================================
RUNNING | protocol=protocol_A | frame_source=RGB | model=resnet18
====================================================================================================
train=525, val=77, test=147
Skipping, already finished: protocol_A__rgb__resnet18__f32__img224

====================================================================================================
RUNNING | protocol=protocol_A | frame_source=RGB | model=efficientnet_b0
====================================================================================================
train=525, val=77, test=147
Skipping, already finished: protocol_A__rgb__efficientnet_b0__f32__img224

====================================================================================================
RUNNING | protocol=protocol_A | frame_source=RGB | model=mobilenet_v3_small
====================================================================================================
train=525, val=77, test=147
Epoch 01 | train_macro_f1=0.1201 | val_macro_f1=0.1499
Epoch 02 | train_macro_f1=0.2925 | val_macro_f1=0.1981
Epoch 03 | train_macro_f1=0.3735 | val_macro_f1=0.2236
Epoch 04 | train_macro_f1=0.4832 | val_macro_f1=0.3305
Epoch 05 | train_macro_f1=0.6062 | val_macro_f1=0.3890
Epoch 06 | train_macro_f1=0.6570 | val_macro_f1=0.4012
Epoch 07 | train_macro_f1=0.7038 | val_macro_f1=0.4866
Epoch 08 | train_macro_f1=0.7771 | val_macro_f1=0.5167
Epoch 09 | train_macro_f1=0.8038 | val_macro_f1=0.4875
Epoch 10 | train_macro_f1=0.8362 | val_macro_f1=0.5439
Epoch 11 | train_macro_f1=0.8896 | val_macro_f1=0.5392
Epoch 12 | train_macro_f1=0.9065 | val_macro_f1=0.5704
{
  "protocol_name": "protocol_A",
  "frame_source": "RGB",
  "model_name": "mobilenet_v3_small",
  "num_sample_frames": 32,
  "batch_size": 32,
  "best_epoch": 12,
  "best_val_macro_f1": 0.5703842940685045,
  "test_accuracy": 0.6190476190476191,
  "test_macro_f1": 0.62250140804345,
  "test_weighted_f1": 0.62250140804345,
  "per_class_f1": {
    "doctor": 0.6666666666666666,
    "emergency": 0.6666666666666666,
    "fire": 0.7142857142857143,
    "help": 0.6829268292682927,
    "robbery": 0.5454545454545454,
    "sit_down": 0.44,
    "stand_up": 0.6415094339622641
  },
  "train_time_minutes": 150.1362832347552,
  "inference_time_seconds": 308.1972219944,
  "videos_per_second": 0.4769673102461352,
  "train_rows": 525,
  "val_rows": 77,
  "test_rows": 147,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb__mobilenet_v3_small__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb__mobilenet_v3_small__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb__mobilenet_v3_small__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_A__rgb__mobilenet_v3_small__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_8 | frame_source=RGB | model=resnet18
====================================================================================================
train=215, val=23, test=266
Epoch 01 | train_macro_f1=0.1884 | val_macro_f1=0.2476
Epoch 02 | train_macro_f1=0.7383 | val_macro_f1=0.2923
Epoch 03 | train_macro_f1=0.9574 | val_macro_f1=0.4571
Epoch 04 | train_macro_f1=0.9665 | val_macro_f1=0.4435
Epoch 05 | train_macro_f1=0.9762 | val_macro_f1=0.3841
Epoch 06 | train_macro_f1=1.0000 | val_macro_f1=0.3730
Epoch 07 | train_macro_f1=0.9952 | val_macro_f1=0.4127
Early stopping triggered.
{
  "protocol_name": "protocol_B_4_to_8",
  "frame_source": "RGB",
  "model_name": "resnet18",
  "num_sample_frames": 32,
  "batch_size": 24,
  "best_epoch": 3,
  "best_val_macro_f1": 0.4571428571428572,
  "test_accuracy": 0.3533834586466165,
  "test_macro_f1": 0.3102729797626879,
  "test_weighted_f1": 0.3102729797626879,
  "per_class_f1": {
    "doctor": 0.04878048780487805,
    "emergency": 0.39325842696629215,
    "fire": 0.5121951219512195,
    "help": 0.18604651162790697,
    "robbery": 0.18461538461538463,
    "sit_down": 0.25,
    "stand_up": 0.5970149253731343
  },
  "train_time_minutes": 12.415573791662853,
  "inference_time_seconds": 390.04964423179626,
  "videos_per_second": 0.6819644728144482,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 266,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb__resnet18__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb__resnet18__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb__resnet18__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_B_4_to_8__rgb__resnet18__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_8 | frame_source=RGB | model=efficientnet_b0
====================================================================================================
train=215, val=23, test=266
Epoch 01 | train_macro_f1=0.1080 | val_macro_f1=0.0381
Epoch 02 | train_macro_f1=0.4457 | val_macro_f1=0.1190
Epoch 03 | train_macro_f1=0.7092 | val_macro_f1=0.1615
Epoch 04 | train_macro_f1=0.8429 | val_macro_f1=0.2286
Epoch 05 | train_macro_f1=0.8867 | val_macro_f1=0.3673
Epoch 06 | train_macro_f1=0.8488 | val_macro_f1=0.4585
Epoch 07 | train_macro_f1=0.9294 | val_macro_f1=0.4937
Epoch 08 | train_macro_f1=0.9419 | val_macro_f1=0.5420
Epoch 09 | train_macro_f1=0.9674 | val_macro_f1=0.5246
Epoch 10 | train_macro_f1=0.9762 | val_macro_f1=0.5566
Epoch 11 | train_macro_f1=0.9667 | val_macro_f1=0.5420
Epoch 12 | train_macro_f1=0.9763 | val_macro_f1=0.6229
{
  "protocol_name": "protocol_B_4_to_8",
  "frame_source": "RGB",
  "model_name": "efficientnet_b0",
  "num_sample_frames": 32,
  "batch_size": 16,
  "best_epoch": 12,
  "best_val_macro_f1": 0.6229024943310658,
  "test_accuracy": 0.42857142857142855,
  "test_macro_f1": 0.40157317797025455,
  "test_weighted_f1": 0.4015731779702546,
  "per_class_f1": {
    "doctor": 0.3793103448275862,
    "emergency": 0.4189189189189189,
    "fire": 0.5901639344262295,
    "help": 0.3333333333333333,
    "robbery": 0.375,
    "sit_down": 0.5714285714285714,
    "stand_up": 0.14285714285714285
  },
  "train_time_minutes": 21.344228176275887,
  "inference_time_seconds": 421.0570373535156,
  "videos_per_second": 0.6317433896174709,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 266,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb__efficientnet_b0__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb__efficientnet_b0__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb__efficientnet_b0__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_B_4_to_8__rgb__efficientnet_b0__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_8 | frame_source=RGB | model=mobilenet_v3_small
====================================================================================================
train=215, val=23, test=266
Epoch 01 | train_macro_f1=0.0723 | val_macro_f1=0.0947
Epoch 02 | train_macro_f1=0.2620 | val_macro_f1=0.1429
Epoch 03 | train_macro_f1=0.4208 | val_macro_f1=0.1700
Epoch 04 | train_macro_f1=0.4792 | val_macro_f1=0.1622
Epoch 05 | train_macro_f1=0.5222 | val_macro_f1=0.1625
Epoch 06 | train_macro_f1=0.6349 | val_macro_f1=0.1602
Epoch 07 | train_macro_f1=0.6490 | val_macro_f1=0.1657
Early stopping triggered.
{
  "protocol_name": "protocol_B_4_to_8",
  "frame_source": "RGB",
  "model_name": "mobilenet_v3_small",
  "num_sample_frames": 32,
  "batch_size": 32,
  "best_epoch": 3,
  "best_val_macro_f1": 0.1700404858299595,
  "test_accuracy": 0.20300751879699247,
  "test_macro_f1": 0.15183496709502256,
  "test_weighted_f1": 0.15183496709502256,
  "per_class_f1": {
    "doctor": 0.25165562913907286,
    "emergency": 0.136986301369863,
    "fire": 0.0,
    "help": 0.1797752808988764,
    "robbery": 0.0,
    "sit_down": 0.047619047619047616,
    "stand_up": 0.44680851063829785
  },
  "train_time_minutes": 12.2418106396993,
  "inference_time_seconds": 392.575688123703,
  "videos_per_second": 0.6775763452681812,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 266,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb__mobilenet_v3_small__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb__mobilenet_v3_small__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb__mobilenet_v3_small__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_B_4_to_8__rgb__mobilenet_v3_small__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_8_to_4 | frame_source=RGB | model=resnet18
====================================================================================================
train=240, val=26, test=238
Epoch 01 | train_macro_f1=0.1428 | val_macro_f1=0.1929
Epoch 02 | train_macro_f1=0.7350 | val_macro_f1=0.2845
Epoch 03 | train_macro_f1=0.8926 | val_macro_f1=0.2923
Epoch 04 | train_macro_f1=0.9546 | val_macro_f1=0.4229
Epoch 05 | train_macro_f1=0.9839 | val_macro_f1=0.3031
Epoch 06 | train_macro_f1=0.9836 | val_macro_f1=0.3160
Epoch 07 | train_macro_f1=0.9957 | val_macro_f1=0.2857
Epoch 08 | train_macro_f1=0.9959 | val_macro_f1=0.3183
Early stopping triggered.
{
  "protocol_name": "protocol_B_8_to_4",
  "frame_source": "RGB",
  "model_name": "resnet18",
  "num_sample_frames": 32,
  "batch_size": 24,
  "best_epoch": 4,
  "best_val_macro_f1": 0.4229024943310658,
  "test_accuracy": 0.2857142857142857,
  "test_macro_f1": 0.24899364922575992,
  "test_weighted_f1": 0.2489936492257599,
  "per_class_f1": {
    "doctor": 0.21052631578947367,
    "emergency": 0.36363636363636365,
    "fire": 0.391304347826087,
    "help": 0.36065573770491804,
    "robbery": 0.0,
    "sit_down": 0.09302325581395349,
    "stand_up": 0.3238095238095238
  },
  "train_time_minutes": 53.80854616165161,
  "inference_time_seconds": 99.36983442306519,
  "videos_per_second": 2.3950930519489395,
  "train_rows": 240,
  "val_rows": 26,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_8_to_4__rgb__resnet18__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_8_to_4__rgb__resnet18__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_8_to_4__rgb__resnet18__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_B_8_to_4__rgb__resnet18__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_8_to_4 | frame_source=RGB | model=efficientnet_b0
====================================================================================================
train=240, val=26, test=238
Epoch 01 | train_macro_f1=0.1033 | val_macro_f1=0.0646
Epoch 02 | train_macro_f1=0.5056 | val_macro_f1=0.1786
Epoch 03 | train_macro_f1=0.6448 | val_macro_f1=0.1905
Epoch 04 | train_macro_f1=0.6990 | val_macro_f1=0.1636
Epoch 05 | train_macro_f1=0.7815 | val_macro_f1=0.2265
Epoch 06 | train_macro_f1=0.8103 | val_macro_f1=0.2975
Epoch 07 | train_macro_f1=0.8518 | val_macro_f1=0.3094
Epoch 08 | train_macro_f1=0.9131 | val_macro_f1=0.2982
Epoch 09 | train_macro_f1=0.9295 | val_macro_f1=0.3667
Epoch 10 | train_macro_f1=0.9497 | val_macro_f1=0.4269
Epoch 11 | train_macro_f1=0.9461 | val_macro_f1=0.3944
Epoch 12 | train_macro_f1=0.9449 | val_macro_f1=0.4479
{
  "protocol_name": "protocol_B_8_to_4",
  "frame_source": "RGB",
  "model_name": "efficientnet_b0",
  "num_sample_frames": 32,
  "batch_size": 16,
  "best_epoch": 12,
  "best_val_macro_f1": 0.44790685504971217,
  "test_accuracy": 0.27310924369747897,
  "test_macro_f1": 0.2082812404240976,
  "test_weighted_f1": 0.2082812404240976,
  "per_class_f1": {
    "doctor": 0.1111111111111111,
    "emergency": 0.16216216216216217,
    "fire": 0.4,
    "help": 0.10810810810810811,
    "robbery": 0.05714285714285714,
    "sit_down": 0.24444444444444444,
    "stand_up": 0.375
  },
  "train_time_minutes": 83.12501016060511,
  "inference_time_seconds": 111.94936680793762,
  "videos_per_second": 2.1259611089030734,
  "train_rows": 240,
  "val_rows": 26,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_8_to_4__rgb__efficientnet_b0__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_8_to_4__rgb__efficientnet_b0__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_8_to_4__rgb__efficientnet_b0__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_B_8_to_4__rgb__efficientnet_b0__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_8_to_4 | frame_source=RGB | model=mobilenet_v3_small
====================================================================================================
train=240, val=26, test=238
Epoch 01 | train_macro_f1=0.1082 | val_macro_f1=0.1289
Epoch 02 | train_macro_f1=0.2769 | val_macro_f1=0.1745
Epoch 03 | train_macro_f1=0.3741 | val_macro_f1=0.0952
Epoch 04 | train_macro_f1=0.4555 | val_macro_f1=0.0429
Epoch 05 | train_macro_f1=0.5332 | val_macro_f1=0.0429
Epoch 06 | train_macro_f1=0.6199 | val_macro_f1=0.1647
Early stopping triggered.
{
  "protocol_name": "protocol_B_8_to_4",
  "frame_source": "RGB",
  "model_name": "mobilenet_v3_small",
  "num_sample_frames": 32,
  "batch_size": 32,
  "best_epoch": 2,
  "best_val_macro_f1": 0.17448979591836736,
  "test_accuracy": 0.21008403361344538,
  "test_macro_f1": 0.15000389140165532,
  "test_weighted_f1": 0.15000389140165532,
  "per_class_f1": {
    "doctor": 0.22448979591836735,
    "emergency": 0.1568627450980392,
    "fire": 0.1,
    "help": 0.0,
    "robbery": 0.1686746987951807,
    "sit_down": 0.0,
    "stand_up": 0.4
  },
  "train_time_minutes": 38.456384440263115,
  "inference_time_seconds": 114.76205325126648,
  "videos_per_second": 2.073856237818519,
  "train_rows": 240,
  "val_rows": 26,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_8_to_4__rgb__mobilenet_v3_small__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_8_to_4__rgb__mobilenet_v3_small__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_8_to_4__rgb__mobilenet_v3_small__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_B_8_to_4__rgb__mobilenet_v3_small__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_6_to_8 | frame_source=RGB | model=resnet18
====================================================================================================
train=435, val=48, test=266
Epoch 01 | train_macro_f1=0.2157 | val_macro_f1=0.4242
Epoch 02 | train_macro_f1=0.7702 | val_macro_f1=0.5274
Epoch 03 | train_macro_f1=0.8985 | val_macro_f1=0.6653
Epoch 04 | train_macro_f1=0.9664 | val_macro_f1=0.6352
Epoch 05 | train_macro_f1=0.9568 | val_macro_f1=0.7055
Epoch 06 | train_macro_f1=0.9879 | val_macro_f1=0.7345
Epoch 07 | train_macro_f1=0.9813 | val_macro_f1=0.7377
Epoch 08 | train_macro_f1=0.9977 | val_macro_f1=0.7175
Epoch 09 | train_macro_f1=0.9955 | val_macro_f1=0.6876
Epoch 10 | train_macro_f1=1.0000 | val_macro_f1=0.7114
Epoch 11 | train_macro_f1=1.0000 | val_macro_f1=0.7252
Early stopping triggered.
{
  "protocol_name": "protocol_B_4_6_to_8",
  "frame_source": "RGB",
  "model_name": "resnet18",
  "num_sample_frames": 32,
  "batch_size": 24,
  "best_epoch": 7,
  "best_val_macro_f1": 0.7377096587622903,
  "test_accuracy": 0.5526315789473685,
  "test_macro_f1": 0.5528999454811825,
  "test_weighted_f1": 0.5528999454811825,
  "per_class_f1": {
    "doctor": 0.6075949367088608,
    "emergency": 0.6461538461538462,
    "fire": 0.5535714285714286,
    "help": 0.5,
    "robbery": 0.463768115942029,
    "sit_down": 0.4931506849315068,
    "stand_up": 0.6060606060606061
  },
  "train_time_minutes": 76.98733601967494,
  "inference_time_seconds": 432.9834406375885,
  "videos_per_second": 0.6143422011897325,
  "train_rows": 435,
  "val_rows": 48,
  "test_rows": 266,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_6_to_8__rgb__resnet18__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_6_to_8__rgb__resnet18__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_6_to_8__rgb__resnet18__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_B_4_6_to_8__rgb__resnet18__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_6_to_8 | frame_source=RGB | model=efficientnet_b0
====================================================================================================
train=435, val=48, test=266
Epoch 01 | train_macro_f1=0.1579 | val_macro_f1=0.1670
Epoch 02 | train_macro_f1=0.5431 | val_macro_f1=0.3360
Epoch 03 | train_macro_f1=0.7364 | val_macro_f1=0.4297
Epoch 04 | train_macro_f1=0.8016 | val_macro_f1=0.6723
Epoch 05 | train_macro_f1=0.8855 | val_macro_f1=0.7731
Epoch 06 | train_macro_f1=0.9051 | val_macro_f1=0.8158
Epoch 07 | train_macro_f1=0.9387 | val_macro_f1=0.7811
Epoch 08 | train_macro_f1=0.9514 | val_macro_f1=0.8029
Epoch 09 | train_macro_f1=0.9788 | val_macro_f1=0.8129

In [1]:
# ============================================================
# 05_stage5_master_rgb_singlecell.ipynb
# ONE-CELL, RESUMABLE, STABLE STAGE-5 RGB BENCHMARK
# ============================================================

import os
import gc
import json
import time
import copy
import math
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision.models import (
    resnet18, ResNet18_Weights,
    efficientnet_b0, EfficientNet_B0_Weights,
    mobilenet_v3_small, MobileNet_V3_Small_Weights,
)

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 300)

# ============================================================
# 1. SETTINGS
# ============================================================
SEED = 42

IMG_SIZE = 224
NUM_SAMPLE_FRAMES = 32

# 400 is not practical here. Use stable values.
BATCH_SIZE_BY_MODEL = {
    "resnet18": 24,
    "efficientnet_b0": 16,
    "mobilenet_v3_small": 32,
}

EPOCHS = 12
LR = 1e-4
WEIGHT_DECAY = 1e-4
PATIENCE = 4

USE_AMP = True
USE_PRETRAINED = True

# Jupyter-safe
NUM_WORKERS = 0
PIN_MEMORY = False

# Optional quick debugging
LIMIT_TRAIN = None
LIMIT_VAL = None
LIMIT_TEST = None

# Smart sampling from middle useful region
SAMPLE_START_FRAC = 0.10
SAMPLE_END_FRAC = 0.90

# Resume / skip finished runs automatically
SKIP_IF_METRICS_EXISTS = True

# Run all Stage 5 combinations
FRAME_SOURCES = [
    "RGB",
    "RGB_BGREM",
]

MODELS_TO_RUN = [
    "resnet18",
    "efficientnet_b0",
    "mobilenet_v3_small",
]

# protocol_name, train_csv, val_csv, test_csv
SPLIT_CONFIGS = [
    ("protocol_A",          "protocol_A_train.csv",          "protocol_A_val.csv",          "protocol_A_test.csv"),
    ("protocol_B_4_to_8",   "protocol_B_train_4_test_8.csv", None,                          "protocol_B_test_8.csv"),
    ("protocol_B_8_to_4",   "protocol_B_train_8_test_4.csv", None,                          "protocol_B_test_4.csv"),
    ("protocol_B_4_6_to_8", "protocol_B_train_4_6_test_8.csv", None,                        "protocol_B_test_8_from_4_6.csv"),
    ("protocol_B_4_8_to_6", "protocol_B_train_4_8_test_6.csv", None,                        "protocol_B_test_6_from_4_8.csv"),
    ("protocol_B_6_8_to_4", "protocol_B_train_6_8_test_4.csv", None,                        "protocol_B_test_4_from_6_8.csv"),
]

CLASS_NAMES = [
    "doctor",
    "emergency",
    "fire",
    "help",
    "robbery",
    "sit_down",
    "stand_up",
]
label2id = {c: i for i, c in enumerate(CLASS_NAMES)}
id2label = {i: c for c, i in label2id.items()}
NUM_CLASSES = len(CLASS_NAMES)

# ============================================================
# 2. REPRODUCIBILITY
# ============================================================
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(SEED)

# ============================================================
# 3. PATHS
# ============================================================
cwd = Path.cwd()
ROOT = cwd.parent if cwd.name == "notebooks" else cwd

SPLIT_DIR = ROOT / "data" / "processed" / "splits"
MANIFEST_DIR = ROOT / "data" / "processed" / "manifests"

RESULTS_ROOT = ROOT / "results" / "stage5_rgb_master"
CHECKPOINT_ROOT = ROOT / "checkpoints" / "stage5_rgb_master"
LOG_ROOT = ROOT / "logs" / "stage5_rgb_master"

RESULTS_ROOT.mkdir(parents=True, exist_ok=True)
CHECKPOINT_ROOT.mkdir(parents=True, exist_ok=True)
LOG_ROOT.mkdir(parents=True, exist_ok=True)

FRAME_SUMMARY_CSV = MANIFEST_DIR / "frame_extraction_trimmed_summary.csv"
if not FRAME_SUMMARY_CSV.exists():
    raise FileNotFoundError(f"Missing file: {FRAME_SUMMARY_CSV}")

print("ROOT:", ROOT)
print("FRAME_SUMMARY_CSV:", FRAME_SUMMARY_CSV)
print("CLASS_NAMES:", CLASS_NAMES)

# ============================================================
# 4. DEVICE
# ============================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
torch.backends.cudnn.benchmark = False

# ============================================================
# 5. FRAME SUMMARY
# ============================================================
frame_df_all = pd.read_csv(FRAME_SUMMARY_CSV)
frame_df_all = frame_df_all[frame_df_all["status"] == "success"].copy()
frame_df_all = frame_df_all[["pair_id", "modality", "output_dir", "frames_extracted"]].drop_duplicates()

# ============================================================
# 6. HELPERS
# ============================================================
def sample_indices_middle_region(n_total, n_samples, start_frac=0.10, end_frac=0.90):
    if n_total <= 0:
        return [0] * n_samples

    start_idx = int(round(start_frac * (n_total - 1)))
    end_idx = int(round(end_frac * (n_total - 1)))

    start_idx = max(0, min(start_idx, n_total - 1))
    end_idx = max(start_idx, min(end_idx, n_total - 1))

    idxs = np.linspace(start_idx, end_idx, n_samples)
    idxs = np.round(idxs).astype(int)
    return np.clip(idxs, 0, n_total - 1).tolist()

def frame_index_to_path(frame_dir, idx):
    return Path(frame_dir) / f"frame_{idx+1:06d}.jpg"

def load_split_df(csv_name):
    csv_path = SPLIT_DIR / csv_name
    if not csv_path.exists():
        raise FileNotFoundError(f"Missing split file: {csv_path}")
    df = pd.read_csv(csv_path)
    if "is_valid_pair" in df.columns:
        df = df[df["is_valid_pair"] == True].copy()
    return df.reset_index(drop=True)

def attach_labels(df_):
    out = df_.copy()
    out = out[out["gesture"].isin(CLASS_NAMES)].copy()
    out["label"] = out["gesture"].map(label2id)
    return out.reset_index(drop=True)

def attach_frame_info(df_, frame_source):
    sub = frame_df_all[frame_df_all["modality"] == frame_source].copy()
    sub = sub.rename(columns={
        "output_dir": "frame_dir",
        "frames_extracted": "num_frames_available"
    })
    sub = sub[["pair_id", "frame_dir", "num_frames_available"]].drop_duplicates()

    out = df_.merge(sub, on="pair_id", how="left")
    out = out[out["num_frames_available"].fillna(0) > 0].copy().reset_index(drop=True)
    out["num_frames_available"] = out["num_frames_available"].astype(int)
    return out

# ============================================================
# 7. TRANSFORMS
# ============================================================
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    ),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    ),
])

# ============================================================
# 8. DATASET
# ============================================================
class FrameVotingDataset(Dataset):
    def __init__(self, df, transform, num_sample_frames=32, start_frac=0.10, end_frac=0.90):
        self.df = df.reset_index(drop=True).copy()
        self.transform = transform
        self.sampled_paths = []

        for _, row in self.df.iterrows():
            idxs = sample_indices_middle_region(
                int(row["num_frames_available"]),
                num_sample_frames,
                start_frac,
                end_frac
            )
            self.sampled_paths.append([frame_index_to_path(row["frame_dir"], i) for i in idxs])

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        paths = self.sampled_paths[idx]

        frames = []
        for p in paths:
            try:
                with Image.open(p) as f:
                    img = f.convert("RGB")
            except Exception:
                img = Image.fromarray(np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8))
            frames.append(self.transform(img))

        frames = torch.stack(frames, dim=0)
        label = int(row["label"])

        meta = {
            "pair_id": row["pair_id"],
            "subject_id": row["subject_id"],
            "distance": row["distance"],
            "gesture": row["gesture"],
            "frame_dir": row["frame_dir"],
        }
        return frames, label, meta

def collate_fn(batch):
    frames = torch.stack([x[0] for x in batch], dim=0)
    labels = torch.tensor([x[1] for x in batch], dtype=torch.long)
    metas = [x[2] for x in batch]
    return frames, labels, metas

# ============================================================
# 9. MODEL FACTORY
# ============================================================
def create_model(model_name, num_classes, use_pretrained=True):
    if model_name == "resnet18":
        model = resnet18(weights=ResNet18_Weights.DEFAULT if use_pretrained else None)
        model.fc = nn.Linear(model.fc.in_features, num_classes)

    elif model_name == "efficientnet_b0":
        model = efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT if use_pretrained else None)
        model.classifier[1] = nn.Linear(model.classifier[1].in_features, num_classes)

    elif model_name == "mobilenet_v3_small":
        model = mobilenet_v3_small(weights=MobileNet_V3_Small_Weights.DEFAULT if use_pretrained else None)
        model.classifier[3] = nn.Linear(model.classifier[3].in_features, num_classes)

    else:
        raise ValueError(f"Unsupported model: {model_name}")

    return model

def forward_video_voting(model, frames):
    B, T, C, H, W = frames.shape
    frames = frames.view(B * T, C, H, W)
    frame_logits = model(frames)
    frame_logits = frame_logits.view(B, T, -1)
    video_logits = frame_logits.mean(dim=1)
    return video_logits

# ============================================================
# 10. TRAIN / EVAL
# ============================================================
def run_one_epoch(model, loader, criterion, optimizer=None, scaler=None, train=True):
    model.train() if train else model.eval()

    total_loss = 0.0
    all_labels = []
    all_preds = []

    for frames, labels, metas in loader:
        frames, labels = frames.to(device), labels.to(device)

        if train:
            optimizer.zero_grad(set_to_none=True)

        with torch.set_grad_enabled(train):
            with torch.autocast(
                device_type="cuda",
                dtype=torch.float16,
                enabled=(USE_AMP and device.type == "cuda")
            ):
                video_logits = forward_video_voting(model, frames)
                loss = criterion(video_logits, labels)

            if train:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()

        preds = video_logits.argmax(dim=1)

        total_loss += loss.item() * labels.size(0)
        all_labels.extend(labels.detach().cpu().numpy().tolist())
        all_preds.extend(preds.detach().cpu().numpy().tolist())

    return {
        "loss": total_loss / len(loader.dataset),
        "accuracy": accuracy_score(all_labels, all_preds),
        "macro_f1": f1_score(all_labels, all_preds, average="macro"),
        "weighted_f1": f1_score(all_labels, all_preds, average="weighted"),
    }

@torch.no_grad()
def predict_with_metadata(model, loader):
    model.eval()

    all_labels = []
    all_preds = []
    rows = []

    start_time = time.time()
    total_samples = 0

    for frames, labels, metas in loader:
        frames, labels = frames.to(device), labels.to(device)

        with torch.autocast(
            device_type="cuda",
            dtype=torch.float16,
            enabled=(USE_AMP and device.type == "cuda")
        ):
            video_logits = forward_video_voting(model, frames)
            probs = torch.softmax(video_logits, dim=1)
            preds = probs.argmax(dim=1)

        probs_np = probs.detach().cpu().numpy()
        preds_np = preds.detach().cpu().numpy()
        labels_np = labels.detach().cpu().numpy()

        total_samples += len(labels_np)

        all_labels.extend(labels_np.tolist())
        all_preds.extend(preds_np.tolist())

        for i, meta in enumerate(metas):
            row = {
                "pair_id": meta["pair_id"],
                "subject_id": meta["subject_id"],
                "distance": meta["distance"],
                "gesture_true": id2label[int(labels_np[i])],
                "gesture_pred": id2label[int(preds_np[i])],
                "frame_dir": meta["frame_dir"],
            }
            for c_idx, c_name in id2label.items():
                row[f"prob_{c_name}"] = float(probs_np[i][c_idx])
            rows.append(row)

    elapsed = time.time() - start_time
    videos_per_sec = total_samples / elapsed if elapsed > 0 else None
    return all_labels, all_preds, pd.DataFrame(rows), elapsed, videos_per_sec

# ============================================================
# 11. RUN ONE EXPERIMENT
# ============================================================
def run_experiment(protocol_name, train_csv_name, val_csv_name, test_csv_name, frame_source, model_name):
    print("\n" + "=" * 100)
    print(f"RUNNING | protocol={protocol_name} | frame_source={frame_source} | model={model_name}")
    print("=" * 100)

    train_df = load_split_df(train_csv_name)
    test_df = load_split_df(test_csv_name)

    if val_csv_name is None:
        train_df = train_df.sample(frac=1.0, random_state=SEED).reset_index(drop=True)
        n_val = max(1, int(0.10 * len(train_df)))
        val_df = train_df.iloc[:n_val].copy().reset_index(drop=True)
        train_df = train_df.iloc[n_val:].copy().reset_index(drop=True)
    else:
        val_df = load_split_df(val_csv_name)

    if LIMIT_TRAIN is not None:
        train_df = train_df.head(LIMIT_TRAIN).copy()
    if LIMIT_VAL is not None:
        val_df = val_df.head(LIMIT_VAL).copy()
    if LIMIT_TEST is not None:
        test_df = test_df.head(LIMIT_TEST).copy()

    train_df = attach_labels(train_df)
    val_df = attach_labels(val_df)
    test_df = attach_labels(test_df)

    train_df = attach_frame_info(train_df, frame_source)
    val_df = attach_frame_info(val_df, frame_source)
    test_df = attach_frame_info(test_df, frame_source)

    print(f"train={len(train_df)}, val={len(val_df)}, test={len(test_df)}")

    batch_size = BATCH_SIZE_BY_MODEL[model_name]

    train_loader = DataLoader(
        FrameVotingDataset(train_df, train_transform, NUM_SAMPLE_FRAMES, SAMPLE_START_FRAC, SAMPLE_END_FRAC),
        batch_size=batch_size,
        shuffle=True,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        collate_fn=collate_fn
    )
    val_loader = DataLoader(
        FrameVotingDataset(val_df, eval_transform, NUM_SAMPLE_FRAMES, SAMPLE_START_FRAC, SAMPLE_END_FRAC),
        batch_size=batch_size,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        collate_fn=collate_fn
    )
    test_loader = DataLoader(
        FrameVotingDataset(test_df, eval_transform, NUM_SAMPLE_FRAMES, SAMPLE_START_FRAC, SAMPLE_END_FRAC),
        batch_size=batch_size,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
        collate_fn=collate_fn
    )

    run_name = f"{protocol_name}__{frame_source.lower()}__{model_name}__f{NUM_SAMPLE_FRAMES}__img{IMG_SIZE}"
    results_dir = RESULTS_ROOT / run_name
    checkpoint_dir = CHECKPOINT_ROOT / run_name
    log_dir = LOG_ROOT / run_name

    results_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)

    metrics_json = results_dir / "metrics.json"
    if SKIP_IF_METRICS_EXISTS and metrics_json.exists():
        print("Skipping, already finished:", run_name)
        with open(metrics_json, "r") as f:
            return json.load(f)

    model = create_model(model_name, NUM_CLASSES, use_pretrained=USE_PRETRAINED).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    scaler = torch.amp.GradScaler("cuda", enabled=(USE_AMP and device.type == "cuda"))

    best_val_f1 = -1.0
    best_epoch = -1
    epochs_without_improvement = 0
    history = []

    best_ckpt_path = checkpoint_dir / "best_model.pt"
    best_state_dict = None

    train_start = time.time()

    for epoch in range(1, EPOCHS + 1):
        train_metrics = run_one_epoch(model, train_loader, criterion, optimizer, scaler, train=True)
        val_metrics = run_one_epoch(model, val_loader, criterion, optimizer=None, scaler=scaler, train=False)

        history.append({
            "epoch": epoch,
            "train_loss": train_metrics["loss"],
            "train_acc": train_metrics["accuracy"],
            "train_macro_f1": train_metrics["macro_f1"],
            "train_weighted_f1": train_metrics["weighted_f1"],
            "val_loss": val_metrics["loss"],
            "val_acc": val_metrics["accuracy"],
            "val_macro_f1": val_metrics["macro_f1"],
            "val_weighted_f1": val_metrics["weighted_f1"],
        })

        print(
            f"Epoch {epoch:02d} | "
            f"train_macro_f1={train_metrics['macro_f1']:.4f} | "
            f"val_macro_f1={val_metrics['macro_f1']:.4f}"
        )

        if val_metrics["macro_f1"] > best_val_f1:
            best_val_f1 = val_metrics["macro_f1"]
            best_epoch = epoch
            epochs_without_improvement = 0
            best_state_dict = copy.deepcopy(model.state_dict())
            torch.save({
                "epoch": epoch,
                "model_state_dict": best_state_dict,
                "model_name": model_name,
                "frame_source": frame_source,
                "protocol_name": protocol_name,
                "label2id": label2id,
                "id2label": id2label,
            }, best_ckpt_path)
        else:
            epochs_without_improvement += 1

        if epochs_without_improvement >= PATIENCE:
            print("Early stopping triggered.")
            break

    train_elapsed = time.time() - train_start
    pd.DataFrame(history).to_csv(log_dir / "training_log.csv", index=False)

    if best_state_dict is None:
        raise RuntimeError("No best model was saved.")

    model.load_state_dict(best_state_dict)

    test_labels, test_preds, pred_df, infer_elapsed, videos_per_sec = predict_with_metadata(model, test_loader)

    test_acc = accuracy_score(test_labels, test_preds)
    test_macro_f1 = f1_score(test_labels, test_preds, average="macro")
    test_weighted_f1 = f1_score(test_labels, test_preds, average="weighted")

    cm = confusion_matrix(test_labels, test_preds)
    report_dict = classification_report(
        test_labels,
        test_preds,
        target_names=[id2label[i] for i in range(NUM_CLASSES)],
        output_dict=True,
        zero_division=0
    )
    report_df = pd.DataFrame(report_dict).transpose()

    pred_csv = results_dir / "test_predictions.csv"
    report_csv = results_dir / "classification_report.csv"
    cm_png = results_dir / "confusion_matrix.png"

    pred_df.to_csv(pred_csv, index=False)
    report_df.to_csv(report_csv)

    plt.figure(figsize=(8, 6))
    plt.imshow(cm, interpolation="nearest")
    plt.title(f"{protocol_name} | {frame_source} | {model_name}")
    plt.colorbar()
    ticks = np.arange(NUM_CLASSES)
    plt.xticks(ticks, [id2label[i] for i in range(NUM_CLASSES)], rotation=45, ha="right")
    plt.yticks(ticks, [id2label[i] for i in range(NUM_CLASSES)])
    plt.xlabel("Predicted")
    plt.ylabel("True")
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, str(cm[i, j]), ha="center", va="center")
    plt.tight_layout()
    plt.savefig(cm_png, dpi=200, bbox_inches="tight")
    plt.close()

    per_class_f1 = {}
    for cls in CLASS_NAMES:
        if cls in report_df.index:
            per_class_f1[cls] = float(report_df.loc[cls, "f1-score"])

    metrics = {
        "protocol_name": protocol_name,
        "frame_source": frame_source,
        "model_name": model_name,
        "num_sample_frames": NUM_SAMPLE_FRAMES,
        "batch_size": batch_size,
        "best_epoch": int(best_epoch),
        "best_val_macro_f1": float(best_val_f1),
        "test_accuracy": float(test_acc),
        "test_macro_f1": float(test_macro_f1),
        "test_weighted_f1": float(test_weighted_f1),
        "per_class_f1": per_class_f1,
        "train_time_minutes": float(train_elapsed / 60.0),
        "inference_time_seconds": float(infer_elapsed),
        "videos_per_second": float(videos_per_sec) if videos_per_sec is not None else None,
        "train_rows": int(len(train_df)),
        "val_rows": int(len(val_df)),
        "test_rows": int(len(test_df)),
        "predictions_csv": str(pred_csv),
        "classification_report_csv": str(report_csv),
        "confusion_matrix_png": str(cm_png),
        "checkpoint_best": str(best_ckpt_path),
    }

    with open(metrics_json, "w") as f:
        json.dump(metrics, f, indent=4)

    print(json.dumps(metrics, indent=2))

    del model, train_loader, val_loader, test_loader, best_state_dict
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return metrics

# ============================================================
# 12. RUN ALL EXPERIMENTS
# ============================================================
summary_csv = RESULTS_ROOT / "stage5_rgb_master_summary.csv"

all_metrics = []
if summary_csv.exists():
    try:
        prev = pd.read_csv(summary_csv)
        all_metrics = prev.to_dict(orient="records")
    except Exception:
        all_metrics = []

done_keys = set()
for m in all_metrics:
    done_keys.add((m["protocol_name"], m["frame_source"], m["model_name"]))

for frame_source in FRAME_SOURCES:
    for protocol_name, train_csv_name, val_csv_name, test_csv_name in SPLIT_CONFIGS:
        for model_name in MODELS_TO_RUN:
            key = (protocol_name, frame_source, model_name)
            if SKIP_IF_METRICS_EXISTS and key in done_keys:
                print("Already in summary, skipping:", key)
                continue

            metrics = run_experiment(
                protocol_name=protocol_name,
                train_csv_name=train_csv_name,
                val_csv_name=val_csv_name,
                test_csv_name=test_csv_name,
                frame_source=frame_source,
                model_name=model_name
            )
            all_metrics.append(metrics)
            done_keys.add(key)

            pd.DataFrame(all_metrics).to_csv(summary_csv, index=False)

final_df = pd.DataFrame(all_metrics)
final_df.to_csv(summary_csv, index=False)

print("\nDONE.")
print("Saved summary to:", summary_csv)
display(
    final_df[[
        "protocol_name",
        "frame_source",
        "model_name",
        "best_val_macro_f1",
        "test_accuracy",
        "test_macro_f1",
        "test_weighted_f1",
        "train_time_minutes",
        "videos_per_second"
    ]].sort_values(["protocol_name", "frame_source", "test_macro_f1"], ascending=[True, True, False])
)

ROOT: /data/Sajjan_Singh/gesture_recognition
FRAME_SUMMARY_CSV: /data/Sajjan_Singh/gesture_recognition/data/processed/manifests/frame_extraction_trimmed_summary.csv
CLASS_NAMES: ['doctor', 'emergency', 'fire', 'help', 'robbery', 'sit_down', 'stand_up']
Using device: cuda
GPU name: NVIDIA H100 NVL
Already in summary, skipping: ('protocol_A', 'RGB', 'resnet18')
Already in summary, skipping: ('protocol_A', 'RGB', 'efficientnet_b0')
Already in summary, skipping: ('protocol_A', 'RGB', 'mobilenet_v3_small')
Already in summary, skipping: ('protocol_B_4_to_8', 'RGB', 'resnet18')
Already in summary, skipping: ('protocol_B_4_to_8', 'RGB', 'efficientnet_b0')
Already in summary, skipping: ('protocol_B_4_to_8', 'RGB', 'mobilenet_v3_small')
Already in summary, skipping: ('protocol_B_8_to_4', 'RGB', 'resnet18')
Already in summary, skipping: ('protocol_B_8_to_4', 'RGB', 'efficientnet_b0')
Already in summary, skipping: ('protocol_B_8_to_4', 'RGB', 'mobilenet_v3_small')
Already in summary, skipping: ('protocol_B_4_6_to_8', 'RGB', 'resnet18')
Already in summary, skipping: ('protocol_B_4_6_to_8', 'RGB', 'efficientnet_b0')
Already in summary, skipping: ('protocol_B_4_6_to_8', 'RGB', 'mobilenet_v3_small')
Already in summary, skipping: ('protocol_B_4_8_to_6', 'RGB', 'resnet18')
Already in summary, skipping: ('protocol_B_4_8_to_6', 'RGB', 'efficientnet_b0')
Already in summary, skipping: ('protocol_B_4_8_to_6', 'RGB', 'mobilenet_v3_small')
Already in summary, skipping: ('protocol_B_6_8_to_4', 'RGB', 'resnet18')

====================================================================================================
RUNNING | protocol=protocol_B_6_8_to_4 | frame_source=RGB | model=efficientnet_b0
====================================================================================================
train=460, val=51, test=238
Epoch 01 | train_macro_f1=0.1289 | val_macro_f1=0.0865
Epoch 02 | train_macro_f1=0.4242 | val_macro_f1=0.1873
Epoch 03 | train_macro_f1=0.5701 | val_macro_f1=0.2867
Epoch 04 | train_macro_f1=0.7121 | val_macro_f1=0.3942
Epoch 05 | train_macro_f1=0.7650 | val_macro_f1=0.4767
Epoch 06 | train_macro_f1=0.8022 | val_macro_f1=0.5860
Epoch 07 | train_macro_f1=0.8839 | val_macro_f1=0.6519
Epoch 08 | train_macro_f1=0.9322 | val_macro_f1=0.7006
Epoch 09 | train_macro_f1=0.9611 | val_macro_f1=0.6355
Epoch 10 | train_macro_f1=0.9624 | val_macro_f1=0.6080
Epoch 11 | train_macro_f1=0.9781 | val_macro_f1=0.6367
Epoch 12 | train_macro_f1=0.9720 | val_macro_f1=0.7370
{
  "protocol_name": "protocol_B_6_8_to_4",
  "frame_source": "RGB",
  "model_name": "efficientnet_b0",
  "num_sample_frames": 32,
  "batch_size": 16,
  "best_epoch": 12,
  "best_val_macro_f1": 0.7369813422445002,
  "test_accuracy": 0.680672268907563,
  "test_macro_f1": 0.6940423173424063,
  "test_weighted_f1": 0.6940423173424062,
  "per_class_f1": {
    "doctor": 0.7384615384615385,
    "emergency": 0.8484848484848485,
    "fire": 0.75,
    "help": 0.7586206896551724,
    "robbery": 0.5862068965517241,
    "sit_down": 0.5535714285714286,
    "stand_up": 0.6229508196721312
  },
  "train_time_minutes": 148.82902094523112,
  "inference_time_seconds": 182.90621161460876,
  "videos_per_second": 1.3012133262126504,
  "train_rows": 460,
  "val_rows": 51,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_6_8_to_4__rgb__efficientnet_b0__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_6_8_to_4__rgb__efficientnet_b0__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_6_8_to_4__rgb__efficientnet_b0__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_B_6_8_to_4__rgb__efficientnet_b0__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_6_8_to_4 | frame_source=RGB | model=mobilenet_v3_small
====================================================================================================
train=460, val=51, test=238
Epoch 01 | train_macro_f1=0.1215 | val_macro_f1=0.1448
Epoch 02 | train_macro_f1=0.2936 | val_macro_f1=0.1901
Epoch 03 | train_macro_f1=0.4041 | val_macro_f1=0.2006
Epoch 04 | train_macro_f1=0.5021 | val_macro_f1=0.2147
Epoch 05 | train_macro_f1=0.5412 | val_macro_f1=0.2182
Epoch 06 | train_macro_f1=0.6148 | val_macro_f1=0.2809
Epoch 07 | train_macro_f1=0.6987 | val_macro_f1=0.2708
Epoch 08 | train_macro_f1=0.7241 | val_macro_f1=0.3092
Epoch 09 | train_macro_f1=0.7606 | val_macro_f1=0.2784
Epoch 10 | train_macro_f1=0.8078 | val_macro_f1=0.3481
Epoch 11 | train_macro_f1=0.8812 | val_macro_f1=0.3156
Epoch 12 | train_macro_f1=0.8865 | val_macro_f1=0.3090
{
  "protocol_name": "protocol_B_6_8_to_4",
  "frame_source": "RGB",
  "model_name": "mobilenet_v3_small",
  "num_sample_frames": 32,
  "batch_size": 32,
  "best_epoch": 10,
  "best_val_macro_f1": 0.34810383863614663,
  "test_accuracy": 0.36554621848739494,
  "test_macro_f1": 0.34333493397469356,
  "test_weighted_f1": 0.34333493397469356,
  "per_class_f1": {
    "doctor": 0.35294117647058826,
    "emergency": 0.4090909090909091,
    "fire": 0.5333333333333333,
    "help": 0.15384615384615385,
    "robbery": 0.16216216216216217,
    "sit_down": 0.291970802919708,
    "stand_up": 0.5
  },
  "train_time_minutes": 163.8530912121137,
  "inference_time_seconds": 148.7048351764679,
  "videos_per_second": 1.600485954054995,
  "train_rows": 460,
  "val_rows": 51,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_6_8_to_4__rgb__mobilenet_v3_small__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_6_8_to_4__rgb__mobilenet_v3_small__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_6_8_to_4__rgb__mobilenet_v3_small__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_B_6_8_to_4__rgb__mobilenet_v3_small__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_A | frame_source=RGB_BGREM | model=resnet18
====================================================================================================
train=525, val=77, test=147
Epoch 01 | train_macro_f1=0.3226 | val_macro_f1=0.6315
Epoch 02 | train_macro_f1=0.7594 | val_macro_f1=0.8042
Epoch 03 | train_macro_f1=0.8801 | val_macro_f1=0.7434
Epoch 04 | train_macro_f1=0.9370 | val_macro_f1=0.8425
Epoch 05 | train_macro_f1=0.9543 | val_macro_f1=0.8073
Epoch 06 | train_macro_f1=0.9772 | val_macro_f1=0.8284
Epoch 07 | train_macro_f1=0.9867 | val_macro_f1=0.8354
Epoch 08 | train_macro_f1=0.9886 | val_macro_f1=0.7771
Early stopping triggered.
{
  "protocol_name": "protocol_A",
  "frame_source": "RGB_BGREM",
  "model_name": "resnet18",
  "num_sample_frames": 32,
  "batch_size": 24,
  "best_epoch": 4,
  "best_val_macro_f1": 0.84245396098943,
  "test_accuracy": 0.8299319727891157,
  "test_macro_f1": 0.828292011005623,
  "test_weighted_f1": 0.828292011005623,
  "per_class_f1": {
    "doctor": 0.926829268292683,
    "emergency": 0.926829268292683,
    "fire": 0.85,
    "help": 0.9130434782608695,
    "robbery": 0.8,
    "sit_down": 0.6153846153846154,
    "stand_up": 0.7659574468085106
  },
  "train_time_minutes": 87.9463072180748,
  "inference_time_seconds": 311.49955654144287,
  "videos_per_second": 0.4719107841825857,
  "train_rows": 525,
  "val_rows": 77,
  "test_rows": 147,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb_bgrem__resnet18__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb_bgrem__resnet18__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb_bgrem__resnet18__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_A__rgb_bgrem__resnet18__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_A | frame_source=RGB_BGREM | model=efficientnet_b0
====================================================================================================
train=525, val=77, test=147
Epoch 01 | train_macro_f1=0.2437 | val_macro_f1=0.4278
Epoch 02 | train_macro_f1=0.6062 | val_macro_f1=0.5756
Epoch 03 | train_macro_f1=0.7283 | val_macro_f1=0.7668
Epoch 04 | train_macro_f1=0.8421 | val_macro_f1=0.7942
Epoch 05 | train_macro_f1=0.8830 | val_macro_f1=0.8174
Epoch 06 | train_macro_f1=0.9084 | val_macro_f1=0.8310
Epoch 07 | train_macro_f1=0.9256 | val_macro_f1=0.8328
Epoch 08 | train_macro_f1=0.9505 | val_macro_f1=0.8584
Epoch 09 | train_macro_f1=0.9542 | val_macro_f1=0.8579
Epoch 10 | train_macro_f1=0.9600 | val_macro_f1=0.8448
Epoch 11 | train_macro_f1=0.9810 | val_macro_f1=0.8429
Epoch 12 | train_macro_f1=0.9790 | val_macro_f1=0.8429
Early stopping triggered.
{
  "protocol_name": "protocol_A",
  "frame_source": "RGB_BGREM",
  "model_name": "efficientnet_b0",
  "num_sample_frames": 32,
  "batch_size": 16,
  "best_epoch": 8,
  "best_val_macro_f1": 0.8584119813933478,
  "test_accuracy": 0.8163265306122449,
  "test_macro_f1": 0.8198763818901119,
  "test_weighted_f1": 0.8198763818901118,
  "per_class_f1": {
    "doctor": 0.9545454545454546,
    "emergency": 0.8421052631578947,
    "fire": 0.782608695652174,
    "help": 0.8648648648648649,
    "robbery": 0.9,
    "sit_down": 0.6923076923076923,
    "stand_up": 0.7027027027027027
  },
  "train_time_minutes": 120.517467101415,
  "inference_time_seconds": 354.0031042098999,
  "videos_per_second": 0.4152505959745453,
  "train_rows": 525,
  "val_rows": 77,
  "test_rows": 147,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb_bgrem__efficientnet_b0__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb_bgrem__efficientnet_b0__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb_bgrem__efficientnet_b0__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_A__rgb_bgrem__efficientnet_b0__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_A | frame_source=RGB_BGREM | model=mobilenet_v3_small
====================================================================================================
train=525, val=77, test=147
Epoch 01 | train_macro_f1=0.1996 | val_macro_f1=0.1929
Epoch 02 | train_macro_f1=0.4222 | val_macro_f1=0.2019
Epoch 03 | train_macro_f1=0.5429 | val_macro_f1=0.2143
Epoch 04 | train_macro_f1=0.6385 | val_macro_f1=0.2365
Epoch 05 | train_macro_f1=0.7063 | val_macro_f1=0.3688
Epoch 06 | train_macro_f1=0.7801 | val_macro_f1=0.4166
Epoch 07 | train_macro_f1=0.7815 | val_macro_f1=0.3814
Epoch 08 | train_macro_f1=0.7684 | val_macro_f1=0.4665
Epoch 09 | train_macro_f1=0.8264 | val_macro_f1=0.3640
Epoch 10 | train_macro_f1=0.8512 | val_macro_f1=0.4331
Epoch 11 | train_macro_f1=0.8705 | val_macro_f1=0.4909
Epoch 12 | train_macro_f1=0.9009 | val_macro_f1=0.3619
{
  "protocol_name": "protocol_A",
  "frame_source": "RGB_BGREM",
  "model_name": "mobilenet_v3_small",
  "num_sample_frames": 32,
  "batch_size": 32,
  "best_epoch": 11,
  "best_val_macro_f1": 0.4909090909090909,
  "test_accuracy": 0.5102040816326531,
  "test_macro_f1": 0.48194695126410186,
  "test_weighted_f1": 0.4819469512641018,
  "per_class_f1": {
    "doctor": 0.6842105263157895,
    "emergency": 0.8717948717948718,
    "fire": 0.08333333333333333,
    "help": 0.5517241379310345,
    "robbery": 0.40625,
    "sit_down": 0.5263157894736842,
    "stand_up": 0.25
  },
  "train_time_minutes": 193.39762298266092,
  "inference_time_seconds": 365.126407623291,
  "videos_per_second": 0.40260029658458213,
  "train_rows": 525,
  "val_rows": 77,
  "test_rows": 147,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb_bgrem__mobilenet_v3_small__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb_bgrem__mobilenet_v3_small__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_A__rgb_bgrem__mobilenet_v3_small__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_A__rgb_bgrem__mobilenet_v3_small__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_8 | frame_source=RGB_BGREM | model=resnet18
====================================================================================================
train=215, val=23, test=266
Epoch 01 | train_macro_f1=0.2774 | val_macro_f1=0.3012
Epoch 02 | train_macro_f1=0.7579 | val_macro_f1=0.2936
Epoch 03 | train_macro_f1=0.9062 | val_macro_f1=0.3333
Epoch 04 | train_macro_f1=0.9480 | val_macro_f1=0.3673
Epoch 05 | train_macro_f1=1.0000 | val_macro_f1=0.4331
Epoch 06 | train_macro_f1=0.9952 | val_macro_f1=0.4474
Epoch 07 | train_macro_f1=0.9952 | val_macro_f1=0.4814
Epoch 08 | train_macro_f1=1.0000 | val_macro_f1=0.4721
Epoch 09 | train_macro_f1=1.0000 | val_macro_f1=0.5061
Epoch 10 | train_macro_f1=1.0000 | val_macro_f1=0.5259
Epoch 11 | train_macro_f1=1.0000 | val_macro_f1=0.4533
Epoch 12 | train_macro_f1=1.0000 | val_macro_f1=0.5259
{
  "protocol_name": "protocol_B_4_to_8",
  "frame_source": "RGB_BGREM",
  "model_name": "resnet18",
  "num_sample_frames": 32,
  "batch_size": 24,
  "best_epoch": 10,
  "best_val_macro_f1": 0.5258503401360544,
  "test_accuracy": 0.5150375939849624,
  "test_macro_f1": 0.5107822736848916,
  "test_weighted_f1": 0.5107822736848916,
  "per_class_f1": {
    "doctor": 0.37735849056603776,
    "emergency": 0.75,
    "fire": 0.6236559139784946,
    "help": 0.49122807017543857,
    "robbery": 0.46715328467153283,
    "sit_down": 0.2903225806451613,
    "stand_up": 0.5757575757575758
  },
  "train_time_minutes": 38.410233132044475,
  "inference_time_seconds": 388.912148475647,
  "videos_per_second": 0.6839590921564037,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 266,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb_bgrem__resnet18__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb_bgrem__resnet18__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb_bgrem__resnet18__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_B_4_to_8__rgb_bgrem__resnet18__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_8 | frame_source=RGB_BGREM | model=efficientnet_b0
====================================================================================================
train=215, val=23, test=266
Epoch 01 | train_macro_f1=0.1603 | val_macro_f1=0.1359
Epoch 02 | train_macro_f1=0.5813 | val_macro_f1=0.1020
Epoch 03 | train_macro_f1=0.7617 | val_macro_f1=0.2850
Epoch 04 | train_macro_f1=0.8096 | val_macro_f1=0.2262
Epoch 05 | train_macro_f1=0.8730 | val_macro_f1=0.3048
Epoch 06 | train_macro_f1=0.9102 | val_macro_f1=0.4272
Epoch 07 | train_macro_f1=0.9191 | val_macro_f1=0.3753
Epoch 08 | train_macro_f1=0.9486 | val_macro_f1=0.4918
Epoch 09 | train_macro_f1=0.9526 | val_macro_f1=0.4210
Epoch 10 | train_macro_f1=0.9669 | val_macro_f1=0.4711
Epoch 11 | train_macro_f1=0.9717 | val_macro_f1=0.4779
Epoch 12 | train_macro_f1=0.9908 | val_macro_f1=0.4721
Early stopping triggered.
{
  "protocol_name": "protocol_B_4_to_8",
  "frame_source": "RGB_BGREM",
  "model_name": "efficientnet_b0",
  "num_sample_frames": 32,
  "batch_size": 16,
  "best_epoch": 8,
  "best_val_macro_f1": 0.49177489177489175,
  "test_accuracy": 0.5150375939849624,
  "test_macro_f1": 0.5054733615295542,
  "test_weighted_f1": 0.5054733615295544,
  "per_class_f1": {
    "doctor": 0.5671641791044776,
    "emergency": 0.6086956521739131,
    "fire": 0.611764705882353,
    "help": 0.4489795918367347,
    "robbery": 0.47863247863247865,
    "sit_down": 0.4,
    "stand_up": 0.4230769230769231
  },
  "train_time_minutes": 29.33093376159668,
  "inference_time_seconds": 424.3489820957184,
  "videos_per_second": 0.626842554649983,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 266,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb_bgrem__efficientnet_b0__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb_bgrem__efficientnet_b0__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_rgb_master/protocol_B_4_to_8__rgb_bgrem__efficientnet_b0__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_rgb_master/protocol_B_4_to_8__rgb_bgrem__efficientnet_b0__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_8 | frame_source=RGB_BGREM | model=mobilenet_v3_small
====================================================================================================
train=215, val=23, test=266
Epoch 01 | train_macro_f1=0.1767 | val_macro_f1=0.0655
Epoch 02 | train_macro_f1=0.3205 | val_macro_f1=0.1847
Epoch 03 | train_macro_f1=0.5032 | val_macro_f1=0.2006
Epoch 04 | train_macro_f1=0.5854 | val_macro_f1=0.1905
Epoch 05 | train_macro_f1=0.6656 | val_macro_f1=0.1905
Epoch 06 | train_macro_f1=0.7398 | val_macro_f1=0.1099
Epoch 07 | train_macro_f1=0.7356 | val_macro_f1=0.2313
Epoch 08 | train_macro_f1=0.7976 | val_macro_f1=0.2313
Epoch 09 | train_macro_f1=0.8429 | val_macro_f1=0.2619
Epoch 10 | train_macro_f1=0.8607 | val_macro_f1=0.2540
Epoch 11 | train_macro_f1=0.8965 | val_macro_f1=0.2424
Epoch 12 | train_macro_f1=0.9145 | val_macro_f1=0.2381
{
  "protocol_name": "protocol_B_4_to_8",
  "frame_source": "RGB_BGREM",
  "model_name": "mobilenet_v3_small",
  "num_sample_frames": 32,
  "batch_size": 32,
  "best_epoch": 9,
  "best_val_macro_f1": 0.2619047619047619,
  "test_accuracy": 0.32706766917293234,
  "test_macro_f1": 0.2935112788231069,
  "test_weighted_f1": 0.2935112788231069,
  "per_class_f1": {
    "doctor": 0.22580645161290322,
    "emergency": 0.43478260869565216,
    "fire": 0.21875,
    "help": 0.0,
    "robbery": 0.3119266055045872,
    "sit_down": 0.3548387096774194,
    "stand_up": 0.5084745762711864
  },
  "train_time_minutes": 22.97058074871699,
  "inference_time_seconds": 344.10753774642944,
  "videos_per_second": 0.7730141622065065,

,protocol_name,frame_source,model_name,best_val_macro_f1,test_accuracy,test_macro_f1,test_weighted_f1,train_time_minutes,videos_per_second
1,protocol_A,RGB,efficientnet_b0,0.841927,0.884354,0.885118,0.885118,135.243664,0.972483
0,protocol_A,RGB,resnet18,0.894154,0.809524,0.807739,0.807739,148.005852,0.456316
2,protocol_A,RGB,mobilenet_v3_small,0.570384,0.619048,0.622501,0.622501,150.136283,0.476967
18,protocol_A,RGB_BGREM,resnet18,0.842454,0.829932,0.828292,0.828292,87.946307,0.471911
19,protocol_A,RGB_BGREM,efficientnet_b0,0.858412,0.816327,0.819876,0.819876,120.517467,0.415251
20,protocol_A,RGB_BGREM,mobilenet_v3_small,0.490909,0.510204,0.481947,0.481947,193.397623,0.402600
10,protocol_B_4_6_to_8,RGB,efficientnet_b0,0.815767,0.560150,0.559856,0.559856,67.651529,0.680196
9,protocol_B_4_6_to_8,RGB,resnet18,0.737710,0.552632,0.552900,0.552900,76.987336,0.614342
11,protocol_B_4_6_to_8,RGB,mobilenet_v3_small,0.610794,0.327068,0.294327,0.294327,80.402574,0.671377
28,protocol_B_4_6_to_8,RGB_BGREM,efficientnet_b0,0.756854,0.624060,0.624181,0.624181,98.401112,0.410089
27,protocol_B_4_6_to_8,RGB_BGREM,resnet18,0.769171,0.597744,0.589881,0.589881,71.179382,0.777980
29,protocol_B_4_6_to_8,RGB_BGREM,mobilenet_v3_small,0.518397,0.409774,0.384273,0.384273,110.033513,0.743201
13,protocol_B_4_8_to_6,RGB,efficientnet_b0,0.642114,0.767347,0.768886,0.768886,100.943306,0.816108
12,protocol_B_4_8_to_6,RGB,resnet18,0.587541,0.673469,0.672417,0.672417,82.431879,0.808589
14,protocol_B_4_8_to_6,RGB,mobilenet_v3_small,0.422902,0.400000,0.396515,0.396515,99.826090,0.854402
30,protocol_B_4_8_to_6,RGB_BGREM,resnet18,0.813345,0.812245,0.811072,0.811072,100.707012,0.899594
31,protocol_B_4_8_to_6,RGB_BGREM,efficientnet_b0,0.716114,0.820408,0.806697,0.806697,94.106188,0.975310
32,protocol_B_4_8_to_6,RGB_BGREM,mobilenet_v3_small,0.346249,0.395918,0.343619,0.343619,69.301031,0.887080
4,protocol_B_4_to_8,RGB,efficientnet_b0,0.622902,0.428571,0.401573,0.401573,21.344228,0.631743
3,protocol_B_4_to_8,RGB,resnet18,0.457143,0.353383,0.310273,0.310273,12.415574,0.681964
5,protocol_B_4_to_8,RGB,mobilenet_v3_small,0.170040,0.203008,0.151835,0.151835,12.241811,0.677576
21,protocol_B_4_to_8,RGB_BGREM,resnet18,0.525850,0.515038,0.510782,0.510782,38.410233,0.683959
22,protocol_B_4_to_8,RGB_BGREM,efficientnet_b0,0.491775,0.515038,0.505473,0.505473,29.330934,0.626843
23,protocol_B_4_to_8,RGB_BGREM,mobilenet_v3_small,0.261905,0.327068,0.293511,0.293511,22.970581,0.773014
16,protocol_B_6_8_to_4,RGB,efficientnet_b0,0.736981,0.680672,0.694042,0.694042,148.829021,1.301213
15,protocol_B_6_8_to_4,RGB,resnet18,0.702693,0.630252,0.629467,0.629467,159.460447,1.398954
17,protocol_B_6_8_to_4,RGB,mobilenet_v3_small,0.348104,0.365546,0.343335,0.343335,163.853091,1.600486
34,protocol_B_6_8_to_4,RGB_BGREM,efficientnet_b0,0.747850,0.731092,0.741071,0.741071,127.056121,1.754664
33,protocol_B_6_8_to_4,RGB_BGREM,resnet18,0.791419,0.739496,0.735547,0.735547,125.469908,1.932176
35,protocol_B_6_8_to_4,RGB_BGREM,mobilenet_v3_small,0.450175,0.373950,0.338014,0.338014,97.932822,2.478183
6,protocol_B_8_to_4,RGB,resnet18,0.422902,0.285714,0.248994,0.248994,53.808546,2.395093
7,protocol_B_8_to_4,RGB,efficientnet_b0,0.447907,0.273109,0.208281,0.208281,83.125010,2.125961
8,protocol_B_8_to_4,RGB,mobilenet_v3_small,0.174490,0.210084,0.150004,0.150004,38.456384,2.073856
25,protocol_B_8_to_4,RGB_BGREM,efficientnet_b0,0.650588,0.361345,0.328651,0.328651,71.331436,2.040977
24,protocol_B_8_to_4,RGB_BGREM,resnet18,0.661255,0.327731,0.315314,0.315314,69.763214,2.162447
26,protocol_B_8_to_4,RGB_BGREM,mobilenet_v3_small,0.271429,0.247899,0.195508,0.195508,78.354738,2.157320

In [1]:
# ============================================================
# CREATE ALL REMAINING PROTOCOL CSVs
# ============================================================
# Input:
#   data/processed/manifests/paired_manifest_with_subjects.csv
#
# Output:
#   data/processed/splits/*.csv
#   data/processed/splits/all_protocols_summary.csv
# ============================================================

import json
from pathlib import Path
import pandas as pd

# ============================================================
# 1. PATHS
# ============================================================
cwd = Path.cwd()
ROOT = cwd.parent if cwd.name == "notebooks" else cwd

MANIFEST_PATH = ROOT / "data" / "processed" / "manifests" / "paired_manifest_with_subjects.csv"
SPLIT_DIR = ROOT / "data" / "processed" / "splits"
SPLIT_DIR.mkdir(parents=True, exist_ok=True)

if not MANIFEST_PATH.exists():
    raise FileNotFoundError(f"Missing manifest: {MANIFEST_PATH}")

print("ROOT:", ROOT)
print("MANIFEST_PATH:", MANIFEST_PATH)
print("SPLIT_DIR:", SPLIT_DIR)

# ============================================================
# 2. LOAD MANIFEST
# ============================================================
df = pd.read_csv(MANIFEST_PATH)

if "is_valid_pair" in df.columns:
    df = df[df["is_valid_pair"] == True].copy()

required_cols = ["pair_id", "subject_id", "gesture", "distance"]
for col in required_cols:
    if col not in df.columns:
        raise ValueError(f"Missing required column: {col}")

df = df.reset_index(drop=True)

print("\nLoaded manifest shape:", df.shape)
print("Unique distances:", sorted(df["distance"].dropna().unique().tolist()))
print("Unique gestures:", sorted(df["gesture"].dropna().unique().tolist()))
print("Unique subjects:", df["subject_id"].nunique())

print("\nCount by distance:")
print(df["distance"].value_counts().sort_index())

# ============================================================
# 3. DISTANCE NORMALIZATION
# ============================================================
DISTANCE_ALIASES = {
    "4_feet": "4_feet",
    "4 feet": "4_feet",
    "6_feet": "6_feet",
    "6 feet": "6_feet",
    "8_feet": "8_feet",
    "8 feet": "8_feet",
}

df["distance"] = df["distance"].map(lambda x: DISTANCE_ALIASES.get(str(x), str(x)))

VALID_DISTANCES = ["4_feet", "6_feet", "8_feet"]
df = df[df["distance"].isin(VALID_DISTANCES)].copy().reset_index(drop=True)

print("\nAfter normalization:")
print(df["distance"].value_counts().sort_index())

# ============================================================
# 4. HELPER TO SAVE SPLITS
# ============================================================
def save_csv_if_missing(df_out, filename):
    path = SPLIT_DIR / filename
    if path.exists():
        return path, False
    df_out.to_csv(path, index=False)
    return path, True

def make_name(dist_list):
    # ["4_feet"] -> "4"
    # ["4_feet","6_feet"] -> "4_6"
    # ["4_feet","6_feet","8_feet"] -> "4_6_8"
    return "_".join([d.split("_")[0] for d in dist_list])

# ============================================================
# 5. DEFINE FULL PROTOCOL SET
# ============================================================
# We will create:
# 1-distance train -> all 3 tests
# 2-distance train -> all 3 tests
# 3-distance train -> all 3 tests

full_protocols = [
    # single-distance train
    (["4_feet"], ["4_feet"]),
    (["4_feet"], ["6_feet"]),
    (["4_feet"], ["8_feet"]),

    (["6_feet"], ["4_feet"]),
    (["6_feet"], ["6_feet"]),
    (["6_feet"], ["8_feet"]),

    (["8_feet"], ["4_feet"]),
    (["8_feet"], ["6_feet"]),
    (["8_feet"], ["8_feet"]),

    # two-distance train
    (["4_feet", "6_feet"], ["4_feet"]),
    (["4_feet", "6_feet"], ["6_feet"]),
    (["4_feet", "6_feet"], ["8_feet"]),

    (["4_feet", "8_feet"], ["4_feet"]),
    (["4_feet", "8_feet"], ["6_feet"]),
    (["4_feet", "8_feet"], ["8_feet"]),

    (["6_feet", "8_feet"], ["4_feet"]),
    (["6_feet", "8_feet"], ["6_feet"]),
    (["6_feet", "8_feet"], ["8_feet"]),

    # three-distance train
    (["4_feet", "6_feet", "8_feet"], ["4_feet"]),
    (["4_feet", "6_feet", "8_feet"], ["6_feet"]),
    (["4_feet", "6_feet", "8_feet"], ["8_feet"]),
]

# ============================================================
# 6. CREATE SPLITS
# ============================================================
rows = []

for train_distances, test_distances in full_protocols:
    train_name = make_name(train_distances)
    test_name = make_name(test_distances)

    train_df = df[df["distance"].isin(train_distances)].copy().reset_index(drop=True)
    test_df = df[df["distance"].isin(test_distances)].copy().reset_index(drop=True)

    train_file = f"protocol_B_train_{train_name}_test_{test_name}.csv"

    # test filenames keep compatibility with your earlier naming style
    if len(train_distances) == 1 and train_distances == test_distances:
        test_file = f"protocol_B_test_{test_name}_same.csv"
    elif len(train_distances) == 1:
        test_file = f"protocol_B_test_{test_name}.csv"
    else:
        test_file = f"protocol_B_test_{test_name}_from_{train_name}.csv"

    train_path, train_created = save_csv_if_missing(train_df, train_file)
    test_path, test_created = save_csv_if_missing(test_df, test_file)

    rows.append({
        "train_distances": ",".join(train_distances),
        "test_distances": ",".join(test_distances),
        "train_file": str(train_path),
        "test_file": str(test_path),
        "train_rows": len(train_df),
        "test_rows": len(test_df),
        "train_subjects": train_df["subject_id"].nunique(),
        "test_subjects": test_df["subject_id"].nunique(),
        "train_created_now": train_created,
        "test_created_now": test_created,
    })

summary_df = pd.DataFrame(rows)

# ============================================================
# 7. SAVE SUMMARY
# ============================================================
summary_csv = SPLIT_DIR / "all_protocols_summary.csv"
summary_df.to_csv(summary_csv, index=False)

print("\nSaved protocol summary to:", summary_csv)

print("\nAll protocol rows:")
display(summary_df)

print("\nNewly created files only:")
display(summary_df[(summary_df["train_created_now"] == True) | (summary_df["test_created_now"] == True)])

print("\nDone.")

ROOT: /data/Sajjan_Singh/gesture_recognition
MANIFEST_PATH: /data/Sajjan_Singh/gesture_recognition/data/processed/manifests/paired_manifest_with_subjects.csv
SPLIT_DIR: /data/Sajjan_Singh/gesture_recognition/data/processed/splits

Loaded manifest shape: (749, 26)
Unique distances: ['4_feet', '6_feet', '8_feet']
Unique gestures: ['doctor', 'emergency', 'fire', 'help', 'robbery', 'sit_down', 'stand_up']
Unique subjects: 107

Count by distance:
distance
4_feet    238
6_feet    245
8_feet    266
Name: count, dtype: int64

After normalization:
distance
4_feet    238
6_feet    245
8_feet    266
Name: count, dtype: int64

Saved protocol summary to: /data/Sajjan_Singh/gesture_recognition/data/processed/splits/all_protocols_summary.csv

All protocol rows:

,train_distances,test_distances,train_file,test_file,train_rows,test_rows,train_subjects,test_subjects,train_created_now,test_created_now
0,4_feet,4_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,238,238,34,34,False,False
1,4_feet,6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,238,245,34,35,True,True
2,4_feet,8_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,238,266,34,38,False,False
3,6_feet,4_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,245,238,35,34,True,False
4,6_feet,6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,245,245,35,35,False,False
5,6_feet,8_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,245,266,35,38,True,False
6,8_feet,4_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,266,238,38,34,False,False
7,8_feet,6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,266,245,38,35,True,False
8,8_feet,8_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,266,266,38,38,False,False
9,"4_feet,6_feet",4_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,483,238,69,34,True,True
10,"4_feet,6_feet",6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,483,245,69,35,True,True
11,"4_feet,6_feet",8_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,483,266,69,38,False,False
12,"4_feet,8_feet",4_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,504,238,72,34,True,True
13,"4_feet,8_feet",6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,504,245,72,35,False,False
14,"4_feet,8_feet",8_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,504,266,72,38,True,True
15,"6_feet,8_feet",4_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,511,238,73,34,False,False
16,"6_feet,8_feet",6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,511,245,73,35,True,True
17,"6_feet,8_feet",8_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,511,266,73,38,True,True
18,"4_feet,6_feet,8_feet",4_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,749,238,107,34,True,True
19,"4_feet,6_feet,8_feet",6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,749,245,107,35,True,True
20,"4_feet,6_feet,8_feet",8_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,749,266,107,38,True,True

Newly created files only:

,train_distances,test_distances,train_file,test_file,train_rows,test_rows,train_subjects,test_subjects,train_created_now,test_created_now
1,4_feet,6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,238,245,34,35,True,True
3,6_feet,4_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,245,238,35,34,True,False
5,6_feet,8_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,245,266,35,38,True,False
7,8_feet,6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,266,245,38,35,True,False
9,"4_feet,6_feet",4_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,483,238,69,34,True,True
10,"4_feet,6_feet",6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,483,245,69,35,True,True
12,"4_feet,8_feet",4_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,504,238,72,34,True,True
14,"4_feet,8_feet",8_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,504,266,72,38,True,True
16,"6_feet,8_feet",6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,511,245,73,35,True,True
17,"6_feet,8_feet",8_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,511,266,73,38,True,True
18,"4_feet,6_feet,8_feet",4_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,749,238,107,34,True,True
19,"4_feet,6_feet,8_feet",6_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,749,245,107,35,True,True
20,"4_feet,6_feet,8_feet",8_feet,/data/Sajjan_Singh/gesture_recognition/data/pr...,/data/Sajjan_Singh/gesture_recognition/data/pr...,749,266,107,38,True,True

Done.

In [ ]:
# ============================================================
# 05_stage5_remaining_protocols_only.ipynb
# TRAIN ONLY THE REMAINING RGB PROTOCOLS
# ============================================================

import os
import gc
import json
import time
import copy
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision.models import (
    resnet18, ResNet18_Weights,
    efficientnet_b0, EfficientNet_B0_Weights,
    mobilenet_v3_small, MobileNet_V3_Small_Weights,
)

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 300)

# ============================================================
# 1. SETTINGS
# ============================================================
SEED = 42

IMG_SIZE = 224
NUM_SAMPLE_FRAMES = 32

BATCH_SIZE_BY_MODEL = {
    "resnet18": 24,
    "efficientnet_b0": 16,
    "mobilenet_v3_small": 32,
}

EPOCHS = 12
LR = 1e-4
WEIGHT_DECAY = 1e-4
PATIENCE = 4

USE_AMP = True
USE_PRETRAINED = True

NUM_WORKERS = 0
PIN_MEMORY = False

LIMIT_TRAIN = None
LIMIT_VAL = None
LIMIT_TEST = None

SAMPLE_START_FRAC = 0.10
SAMPLE_END_FRAC = 0.90

SKIP_IF_METRICS_EXISTS = True

FRAME_SOURCES = [
    "RGB",
    "RGB_BGREM",
]

MODELS_TO_RUN = [
    "resnet18",
    "efficientnet_b0",
    "mobilenet_v3_small",
]

# ============================================================
# ONLY REMAINING PROTOCOLS
# ============================================================
REMAINING_SPLIT_CONFIGS = [
    ("protocol_B_4_to_4",     "protocol_B_train_4_test_4.csv",     None, "protocol_B_test_4_same.csv"),
    ("protocol_B_4_to_6",     "protocol_B_train_4_test_6.csv",     None, "protocol_B_test_6.csv"),
    ("protocol_B_6_to_6",     "protocol_B_train_6_test_6.csv",     None, "protocol_B_test_6_same.csv"),
    ("protocol_B_6_to_8",     "protocol_B_train_6_test_8.csv",     None, "protocol_B_test_8.csv"),
    ("protocol_B_8_to_6",     "protocol_B_train_8_test_6.csv",     None, "protocol_B_test_6.csv"),
    ("protocol_B_8_to_8",     "protocol_B_train_8_test_8.csv",     None, "protocol_B_test_8_same.csv"),

    ("protocol_B_4_6_to_4",   "protocol_B_train_4_6_test_4.csv",   None, "protocol_B_test_4_from_4_6.csv"),
    ("protocol_B_4_6_to_6",   "protocol_B_train_4_6_test_6.csv",   None, "protocol_B_test_6_from_4_6.csv"),

    ("protocol_B_4_8_to_4",   "protocol_B_train_4_8_test_4.csv",   None, "protocol_B_test_4_from_4_8.csv"),
    ("protocol_B_4_8_to_8",   "protocol_B_train_4_8_test_8.csv",   None, "protocol_B_test_8_from_4_8.csv"),

    ("protocol_B_6_8_to_6",   "protocol_B_train_6_8_test_6.csv",   None, "protocol_B_test_6_from_6_8.csv"),
    ("protocol_B_6_8_to_8",   "protocol_B_train_6_8_test_8.csv",   None, "protocol_B_test_8_from_6_8.csv"),

    ("protocol_B_4_6_8_to_4", "protocol_B_train_4_6_8_test_4.csv", None, "protocol_B_test_4_from_4_6_8.csv"),
    ("protocol_B_4_6_8_to_6", "protocol_B_train_4_6_8_test_6.csv", None, "protocol_B_test_6_from_4_6_8.csv"),
    ("protocol_B_4_6_8_to_8", "protocol_B_train_4_6_8_test_8.csv", None, "protocol_B_test_8_from_4_6_8.csv"),
]

CLASS_NAMES = [
    "doctor",
    "emergency",
    "fire",
    "help",
    "robbery",
    "sit_down",
    "stand_up",
]
label2id = {c: i for i, c in enumerate(CLASS_NAMES)}
id2label = {i: c for c, i in label2id.items()}
NUM_CLASSES = len(CLASS_NAMES)

# ============================================================
# 2. REPRODUCIBILITY
# ============================================================
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(SEED)

# ============================================================
# 3. PATHS
# ============================================================
cwd = Path.cwd()
ROOT = cwd.parent if cwd.name == "notebooks" else cwd

SPLIT_DIR = ROOT / "data" / "processed" / "splits"
MANIFEST_DIR = ROOT / "data" / "processed" / "manifests"

RESULTS_ROOT = ROOT / "results" / "stage5_remaining_protocols"
CHECKPOINT_ROOT = ROOT / "checkpoints" / "stage5_remaining_protocols"
LOG_ROOT = ROOT / "logs" / "stage5_remaining_protocols"

RESULTS_ROOT.mkdir(parents=True, exist_ok=True)
CHECKPOINT_ROOT.mkdir(parents=True, exist_ok=True)
LOG_ROOT.mkdir(parents=True, exist_ok=True)

FRAME_SUMMARY_CSV = MANIFEST_DIR / "frame_extraction_trimmed_summary.csv"
if not FRAME_SUMMARY_CSV.exists():
    raise FileNotFoundError(f"Missing file: {FRAME_SUMMARY_CSV}")

print("ROOT:", ROOT)
print("RESULTS_ROOT:", RESULTS_ROOT)
print("FRAME_SUMMARY_CSV:", FRAME_SUMMARY_CSV)

# ============================================================
# 4. DEVICE
# ============================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
torch.backends.cudnn.benchmark = False

# ============================================================
# 5. FRAME SUMMARY
# ============================================================
frame_df_all = pd.read_csv(FRAME_SUMMARY_CSV)
frame_df_all = frame_df_all[frame_df_all["status"] == "success"].copy()
frame_df_all = frame_df_all[["pair_id", "modality", "output_dir", "frames_extracted"]].drop_duplicates()

# ============================================================
# 6. HELPERS
# ============================================================
def sample_indices_middle_region(n_total, n_samples, start_frac=0.10, end_frac=0.90):
    if n_total <= 0:
        return [0] * n_samples
    start_idx = int(round(start_frac * (n_total - 1)))
    end_idx = int(round(end_frac * (n_total - 1)))
    start_idx = max(0, min(start_idx, n_total - 1))
    end_idx = max(start_idx, min(end_idx, n_total - 1))
    idxs = np.linspace(start_idx, end_idx, n_samples)
    idxs = np.round(idxs).astype(int)
    return np.clip(idxs, 0, n_total - 1).tolist()

def frame_index_to_path(frame_dir, idx):
    return Path(frame_dir) / f"frame_{idx+1:06d}.jpg"

def load_split_df(csv_name):
    csv_path = SPLIT_DIR / csv_name
    if not csv_path.exists():
        raise FileNotFoundError(f"Missing split file: {csv_path}")
    df = pd.read_csv(csv_path)
    if "is_valid_pair" in df.columns:
        df = df[df["is_valid_pair"] == True].copy()
    return df.reset_index(drop=True)

def attach_labels(df_):
    out = df_.copy()
    out = out[out["gesture"].isin(CLASS_NAMES)].copy()
    out["label"] = out["gesture"].map(label2id)
    return out.reset_index(drop=True)

def attach_frame_info(df_, frame_source):
    sub = frame_df_all[frame_df_all["modality"] == frame_source].copy()
    sub = sub.rename(columns={
        "output_dir": "frame_dir",
        "frames_extracted": "num_frames_available"
    })
    sub = sub[["pair_id", "frame_dir", "num_frames_available"]].drop_duplicates()

    out = df_.merge(sub, on="pair_id", how="left")
    out = out[out["num_frames_available"].fillna(0) > 0].copy().reset_index(drop=True)
    out["num_frames_available"] = out["num_frames_available"].astype(int)
    return out

# ============================================================
# 7. TRANSFORMS
# ============================================================
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

# ============================================================
# 8. DATASET
# ============================================================
class FrameVotingDataset(Dataset):
    def __init__(self, df, transform, num_sample_frames=32, start_frac=0.10, end_frac=0.90):
        self.df = df.reset_index(drop=True).copy()
        self.transform = transform
        self.sampled_paths = []

        print(f"Building sampled frame paths for {len(self.df)} samples...")
        for _, row in self.df.iterrows():
            idxs = sample_indices_middle_region(
                int(row["num_frames_available"]),
                num_sample_frames,
                start_frac,
                end_frac
            )
            self.sampled_paths.append([frame_index_to_path(row["frame_dir"], i) for i in idxs])

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        paths = self.sampled_paths[idx]

        frames = []
        for p in paths:
            try:
                with Image.open(p) as f:
                    img = f.convert("RGB")
            except Exception:
                img = Image.fromarray(np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8))
            frames.append(self.transform(img))

        frames = torch.stack(frames, dim=0)
        label = int(row["label"])

        meta = {
            "pair_id": row["pair_id"],
            "subject_id": row["subject_id"],
            "distance": row["distance"],
            "gesture": row["gesture"],
            "frame_dir": row["frame_dir"],
        }
        return frames, label, meta

def collate_fn(batch):
    frames = torch.stack([x[0] for x in batch], dim=0)
    labels = torch.tensor([x[1] for x in batch], dtype=torch.long)
    metas = [x[2] for x in batch]
    return frames, labels, metas

# ============================================================
# 9. MODEL FACTORY
# ============================================================
def create_model(model_name, num_classes, use_pretrained=True):
    if model_name == "resnet18":
        model = resnet18(weights=ResNet18_Weights.DEFAULT if use_pretrained else None)
        model.fc = nn.Linear(model.fc.in_features, num_classes)
    elif model_name == "efficientnet_b0":
        model = efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT if use_pretrained else None)
        model.classifier[1] = nn.Linear(model.classifier[1].in_features, num_classes)
    elif model_name == "mobilenet_v3_small":
        model = mobilenet_v3_small(weights=MobileNet_V3_Small_Weights.DEFAULT if use_pretrained else None)
        model.classifier[3] = nn.Linear(model.classifier[3].in_features, num_classes)
    else:
        raise ValueError(f"Unsupported model: {model_name}")
    return model

def forward_video_voting(model, frames):
    B, T, C, H, W = frames.shape
    frames = frames.view(B * T, C, H, W)
    frame_logits = model(frames)
    frame_logits = frame_logits.view(B, T, -1)
    return frame_logits.mean(dim=1)

# ============================================================
# 10. TRAIN / EVAL
# ============================================================
def run_one_epoch(model, loader, criterion, optimizer=None, scaler=None, train=True):
    model.train() if train else model.eval()

    total_loss = 0.0
    all_labels = []
    all_preds = []

    total_batches = len(loader)

    for batch_idx, (frames, labels, metas) in enumerate(loader):
        frames, labels = frames.to(device), labels.to(device)

        if train:
            optimizer.zero_grad(set_to_none=True)

        with torch.set_grad_enabled(train):
            with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=(USE_AMP and device.type == "cuda")):
                logits = forward_video_voting(model, frames)
                loss = criterion(logits, labels)

            if train:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()

        preds = logits.argmax(dim=1)

        total_loss += loss.item() * labels.size(0)
        all_labels.extend(labels.detach().cpu().numpy().tolist())
        all_preds.extend(preds.detach().cpu().numpy().tolist())

        if batch_idx % 10 == 0 or batch_idx == total_batches - 1:
            mode = "train" if train else "val"
            print(f"   [{mode}] batch {batch_idx+1}/{total_batches} | loss={loss.item():.4f}")

    return {
        "loss": total_loss / len(loader.dataset),
        "accuracy": accuracy_score(all_labels, all_preds),
        "macro_f1": f1_score(all_labels, all_preds, average="macro"),
        "weighted_f1": f1_score(all_labels, all_preds, average="weighted"),
    }

@torch.no_grad()
def predict_with_metadata(model, loader):
    model.eval()

    all_labels = []
    all_preds = []
    rows = []

    start_time = time.time()
    total_samples = 0

    for frames, labels, metas in loader:
        frames, labels = frames.to(device), labels.to(device)

        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=(USE_AMP and device.type == "cuda")):
            logits = forward_video_voting(model, frames)
            probs = torch.softmax(logits, dim=1)
            preds = probs.argmax(dim=1)

        probs_np = probs.detach().cpu().numpy()
        preds_np = preds.detach().cpu().numpy()
        labels_np = labels.detach().cpu().numpy()

        total_samples += len(labels_np)
        all_labels.extend(labels_np.tolist())
        all_preds.extend(preds_np.tolist())

        for i, meta in enumerate(metas):
            row = {
                "pair_id": meta["pair_id"],
                "subject_id": meta["subject_id"],
                "distance": meta["distance"],
                "gesture_true": id2label[int(labels_np[i])],
                "gesture_pred": id2label[int(preds_np[i])],
                "frame_dir": meta["frame_dir"],
            }
            for c_idx, c_name in id2label.items():
                row[f"prob_{c_name}"] = float(probs_np[i][c_idx])
            rows.append(row)

    elapsed = time.time() - start_time
    videos_per_sec = total_samples / elapsed if elapsed > 0 else None
    return all_labels, all_preds, pd.DataFrame(rows), elapsed, videos_per_sec

# ============================================================
# 11. RUN ONE EXPERIMENT
# ============================================================
def run_experiment(protocol_name, train_csv_name, val_csv_name, test_csv_name, frame_source, model_name):
    print("\n" + "=" * 100)
    print(f"RUNNING | protocol={protocol_name} | frame_source={frame_source} | model={model_name}")
    print("=" * 100)

    train_df = load_split_df(train_csv_name)
    test_df = load_split_df(test_csv_name)

    if val_csv_name is None:
        train_df = train_df.sample(frac=1.0, random_state=SEED).reset_index(drop=True)
        n_val = max(1, int(0.10 * len(train_df)))
        val_df = train_df.iloc[:n_val].copy().reset_index(drop=True)
        train_df = train_df.iloc[n_val:].copy().reset_index(drop=True)
    else:
        val_df = load_split_df(val_csv_name)

    train_df = attach_labels(train_df)
    val_df = attach_labels(val_df)
    test_df = attach_labels(test_df)

    train_df = attach_frame_info(train_df, frame_source)
    val_df = attach_frame_info(val_df, frame_source)
    test_df = attach_frame_info(test_df, frame_source)

    if LIMIT_TRAIN is not None:
        train_df = train_df.head(LIMIT_TRAIN).copy()
    if LIMIT_VAL is not None:
        val_df = val_df.head(LIMIT_VAL).copy()
    if LIMIT_TEST is not None:
        test_df = test_df.head(LIMIT_TEST).copy()

    print(f"train={len(train_df)}, val={len(val_df)}, test={len(test_df)}")

    batch_size = BATCH_SIZE_BY_MODEL[model_name]

    train_loader = DataLoader(
        FrameVotingDataset(train_df, train_transform, NUM_SAMPLE_FRAMES, SAMPLE_START_FRAC, SAMPLE_END_FRAC),
        batch_size=batch_size, shuffle=True, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY, collate_fn=collate_fn
    )
    val_loader = DataLoader(
        FrameVotingDataset(val_df, eval_transform, NUM_SAMPLE_FRAMES, SAMPLE_START_FRAC, SAMPLE_END_FRAC),
        batch_size=batch_size, shuffle=False, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY, collate_fn=collate_fn
    )
    test_loader = DataLoader(
        FrameVotingDataset(test_df, eval_transform, NUM_SAMPLE_FRAMES, SAMPLE_START_FRAC, SAMPLE_END_FRAC),
        batch_size=batch_size, shuffle=False, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY, collate_fn=collate_fn
    )

    run_name = f"{protocol_name}__{frame_source.lower()}__{model_name}__f{NUM_SAMPLE_FRAMES}__img{IMG_SIZE}"
    results_dir = RESULTS_ROOT / run_name
    checkpoint_dir = CHECKPOINT_ROOT / run_name
    log_dir = LOG_ROOT / run_name

    results_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)

    metrics_json = results_dir / "metrics.json"
    if SKIP_IF_METRICS_EXISTS and metrics_json.exists():
        print("Skipping, already finished:", run_name)
        with open(metrics_json, "r") as f:
            return json.load(f)

    model = create_model(model_name, NUM_CLASSES, use_pretrained=USE_PRETRAINED).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    scaler = torch.amp.GradScaler("cuda", enabled=(USE_AMP and device.type == "cuda"))

    best_val_f1 = -1.0
    best_epoch = -1
    epochs_without_improvement = 0
    history = []
    best_state_dict = None
    best_ckpt_path = checkpoint_dir / "best_model.pt"

    train_start = time.time()

    for epoch in range(1, EPOCHS + 1):
        print(f"\nEpoch {epoch}/{EPOCHS}")
        train_metrics = run_one_epoch(model, train_loader, criterion, optimizer, scaler, train=True)
        val_metrics = run_one_epoch(model, val_loader, criterion, optimizer=None, scaler=scaler, train=False)

        history.append({
            "epoch": epoch,
            "train_loss": train_metrics["loss"],
            "train_acc": train_metrics["accuracy"],
            "train_macro_f1": train_metrics["macro_f1"],
            "train_weighted_f1": train_metrics["weighted_f1"],
            "val_loss": val_metrics["loss"],
            "val_acc": val_metrics["accuracy"],
            "val_macro_f1": val_metrics["macro_f1"],
            "val_weighted_f1": val_metrics["weighted_f1"],
        })

        print(
            f"Epoch {epoch:02d} | "
            f"train_macro_f1={train_metrics['macro_f1']:.4f} | "
            f"val_macro_f1={val_metrics['macro_f1']:.4f}"
        )

        if val_metrics["macro_f1"] > best_val_f1:
            best_val_f1 = val_metrics["macro_f1"]
            best_epoch = epoch
            epochs_without_improvement = 0
            best_state_dict = copy.deepcopy(model.state_dict())
            torch.save({
                "epoch": epoch,
                "model_state_dict": best_state_dict,
                "model_name": model_name,
                "frame_source": frame_source,
                "protocol_name": protocol_name,
                "label2id": label2id,
                "id2label": id2label,
            }, best_ckpt_path)
        else:
            epochs_without_improvement += 1

        if epochs_without_improvement >= PATIENCE:
            print("Early stopping triggered.")
            break

    train_elapsed = time.time() - train_start
    pd.DataFrame(history).to_csv(log_dir / "training_log.csv", index=False)

    if best_state_dict is None:
        raise RuntimeError("No best model was saved.")

    model.load_state_dict(best_state_dict)

    test_labels, test_preds, pred_df, infer_elapsed, videos_per_sec = predict_with_metadata(model, test_loader)

    test_acc = accuracy_score(test_labels, test_preds)
    test_macro_f1 = f1_score(test_labels, test_preds, average="macro")
    test_weighted_f1 = f1_score(test_labels, test_preds, average="weighted")

    cm = confusion_matrix(test_labels, test_preds)
    report_dict = classification_report(
        test_labels, test_preds,
        target_names=[id2label[i] for i in range(NUM_CLASSES)],
        output_dict=True,
        zero_division=0
    )
    report_df = pd.DataFrame(report_dict).transpose()

    pred_csv = results_dir / "test_predictions.csv"
    report_csv = results_dir / "classification_report.csv"
    cm_png = results_dir / "confusion_matrix.png"

    pred_df.to_csv(pred_csv, index=False)
    report_df.to_csv(report_csv)

    plt.figure(figsize=(8, 6))
    plt.imshow(cm, interpolation="nearest")
    plt.title(f"{protocol_name} | {frame_source} | {model_name}")
    plt.colorbar()
    ticks = np.arange(NUM_CLASSES)
    plt.xticks(ticks, [id2label[i] for i in range(NUM_CLASSES)], rotation=45, ha="right")
    plt.yticks(ticks, [id2label[i] for i in range(NUM_CLASSES)])
    plt.xlabel("Predicted")
    plt.ylabel("True")
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, str(cm[i, j]), ha="center", va="center")
    plt.tight_layout()
    plt.savefig(cm_png, dpi=200, bbox_inches="tight")
    plt.close()

    per_class_f1 = {}
    for cls in CLASS_NAMES:
        if cls in report_df.index:
            per_class_f1[cls] = float(report_df.loc[cls, "f1-score"])

    metrics = {
        "protocol_name": protocol_name,
        "frame_source": frame_source,
        "model_name": model_name,
        "num_sample_frames": NUM_SAMPLE_FRAMES,
        "batch_size": batch_size,
        "best_epoch": int(best_epoch),
        "best_val_macro_f1": float(best_val_f1),
        "test_accuracy": float(test_acc),
        "test_macro_f1": float(test_macro_f1),
        "test_weighted_f1": float(test_weighted_f1),
        "per_class_f1": per_class_f1,
        "train_time_minutes": float(train_elapsed / 60.0),
        "inference_time_seconds": float(infer_elapsed),
        "videos_per_second": float(videos_per_sec) if videos_per_sec is not None else None,
        "train_rows": int(len(train_df)),
        "val_rows": int(len(val_df)),
        "test_rows": int(len(test_df)),
        "predictions_csv": str(pred_csv),
        "classification_report_csv": str(report_csv),
        "confusion_matrix_png": str(cm_png),
        "checkpoint_best": str(best_ckpt_path),
    }

    with open(metrics_json, "w") as f:
        json.dump(metrics, f, indent=4)

    print(json.dumps(metrics, indent=2))

    del model, train_loader, val_loader, test_loader, best_state_dict
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return metrics

# ============================================================
# 12. RUN ONLY REMAINING PROTOCOLS
# ============================================================
summary_csv = RESULTS_ROOT / "remaining_protocols_summary.csv"

all_metrics = []
if summary_csv.exists():
    try:
        prev = pd.read_csv(summary_csv)
        all_metrics = prev.to_dict(orient="records")
    except Exception:
        all_metrics = []

done_keys = set((m["protocol_name"], m["frame_source"], m["model_name"]) for m in all_metrics)

for frame_source in FRAME_SOURCES:
    for protocol_name, train_csv_name, val_csv_name, test_csv_name in REMAINING_SPLIT_CONFIGS:
        for model_name in MODELS_TO_RUN:
            key = (protocol_name, frame_source, model_name)
            if SKIP_IF_METRICS_EXISTS and key in done_keys:
                print("Already in summary, skipping:", key)
                continue

            metrics = run_experiment(
                protocol_name=protocol_name,
                train_csv_name=train_csv_name,
                val_csv_name=val_csv_name,
                test_csv_name=test_csv_name,
                frame_source=frame_source,
                model_name=model_name
            )
            all_metrics.append(metrics)
            done_keys.add(key)
            pd.DataFrame(all_metrics).to_csv(summary_csv, index=False)

final_df = pd.DataFrame(all_metrics)
final_df.to_csv(summary_csv, index=False)

print("\nDONE.")
print("Saved summary to:", summary_csv)
display(final_df[[
    "protocol_name",
    "frame_source",
    "model_name",
    "best_val_macro_f1",
    "test_accuracy",
    "test_macro_f1",
    "test_weighted_f1",
    "train_time_minutes",
    "videos_per_second"
]].sort_values(["protocol_name", "frame_source", "test_macro_f1"], ascending=[True, True, False]))

ROOT: /data/Sajjan_Singh/gesture_recognition
RESULTS_ROOT: /data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols
FRAME_SUMMARY_CSV: /data/Sajjan_Singh/gesture_recognition/data/processed/manifests/frame_extraction_trimmed_summary.csv
Using device: cuda
GPU name: NVIDIA H100 NVL

====================================================================================================
RUNNING | protocol=protocol_B_4_to_4 | frame_source=RGB | model=resnet18
====================================================================================================
train=215, val=23, test=238
Building sampled frame paths for 215 samples...
Building sampled frame paths for 23 samples...
Building sampled frame paths for 238 samples...

Epoch 1/12
   [train] batch 1/9 | loss=2.1320
   [train] batch 9/9 | loss=1.6647
   [val] batch 1/1 | loss=1.7063
Epoch 01 | train_macro_f1=0.2066 | val_macro_f1=0.2192

Epoch 2/12
   [train] batch 1/9 | loss=1.0526
   [train] batch 9/9 | loss=0.8097
   [val] batch 1/1 | loss=1.3123
Epoch 02 | train_macro_f1=0.7427 | val_macro_f1=0.2971

Epoch 3/12
   [train] batch 1/9 | loss=0.6380
   [train] batch 9/9 | loss=0.5332
   [val] batch 1/1 | loss=1.1465
Epoch 03 | train_macro_f1=0.9296 | val_macro_f1=0.4859

Epoch 4/12
   [train] batch 1/9 | loss=0.3363
   [train] batch 9/9 | loss=0.2473
   [val] batch 1/1 | loss=1.3396
Epoch 04 | train_macro_f1=0.9578 | val_macro_f1=0.4189

Epoch 5/12
   [train] batch 1/9 | loss=0.1983
   [train] batch 9/9 | loss=0.1414
   [val] batch 1/1 | loss=1.3502
Epoch 05 | train_macro_f1=0.9857 | val_macro_f1=0.3991

Epoch 6/12
   [train] batch 1/9 | loss=0.1126
   [train] batch 9/9 | loss=0.1072
   [val] batch 1/1 | loss=1.3427
Epoch 06 | train_macro_f1=1.0000 | val_macro_f1=0.3991

Epoch 7/12
   [train] batch 1/9 | loss=0.0925
   [train] batch 9/9 | loss=0.0610
   [val] batch 1/1 | loss=1.3445
Epoch 07 | train_macro_f1=1.0000 | val_macro_f1=0.3912
Early stopping triggered.
{
  "protocol_name": "protocol_B_4_to_4",
  "frame_source": "RGB",
  "model_name": "resnet18",
  "num_sample_frames": 32,
  "batch_size": 24,
  "best_epoch": 3,
  "best_val_macro_f1": 0.4859410430839003,
  "test_accuracy": 0.9201680672268907,
  "test_macro_f1": 0.9196645507215802,
  "test_weighted_f1": 0.9196645507215803,
  "per_class_f1": {
    "doctor": 0.9230769230769231,
    "emergency": 0.9855072463768116,
    "fire": 0.9565217391304348,
    "help": 0.9393939393939394,
    "robbery": 0.9295774647887324,
    "sit_down": 0.8387096774193549,
    "stand_up": 0.8648648648648649
  },
  "train_time_minutes": 109.87225390672684,
  "inference_time_seconds": 258.6606664657593,
  "videos_per_second": 0.9201244365907707,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_4__rgb__resnet18__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_4__rgb__resnet18__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_4__rgb__resnet18__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_remaining_protocols/protocol_B_4_to_4__rgb__resnet18__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_4 | frame_source=RGB | model=efficientnet_b0
====================================================================================================
train=215, val=23, test=238
Building sampled frame paths for 215 samples...
Building sampled frame paths for 23 samples...
Building sampled frame paths for 238 samples...

Epoch 1/12
   [train] batch 1/14 | loss=1.9207
   [train] batch 11/14 | loss=1.9991
   [train] batch 14/14 | loss=1.9901
   [val] batch 1/2 | loss=1.8912
   [val] batch 2/2 | loss=1.9799
Epoch 01 | train_macro_f1=0.1182 | val_macro_f1=0.0762

Epoch 2/12
   [train] batch 1/14 | loss=1.7562
   [train] batch 11/14 | loss=1.7949
   [train] batch 14/14 | loss=1.7153
   [val] batch 1/2 | loss=1.9177
   [val] batch 2/2 | loss=1.9572
Epoch 02 | train_macro_f1=0.5260 | val_macro_f1=0.0519

Epoch 3/12
   [train] batch 1/14 | loss=1.5406
   [train] batch 11/14 | loss=1.4965
   [train] batch 14/14 | loss=1.6568
   [val] batch 1/2 | loss=1.8138
   [val] batch 2/2 | loss=1.8333
Epoch 03 | train_macro_f1=0.7624 | val_macro_f1=0.1071

Epoch 4/12
   [train] batch 1/14 | loss=1.3896
   [train] batch 11/14 | loss=1.2720
   [train] batch 14/14 | loss=1.1821
   [val] batch 1/2 | loss=1.6412
   [val] batch 2/2 | loss=1.6786
Epoch 04 | train_macro_f1=0.8223 | val_macro_f1=0.1043

Epoch 5/12
   [train] batch 1/14 | loss=1.1818
   [train] batch 11/14 | loss=0.9253
   [train] batch 14/14 | loss=0.9259
   [val] batch 1/2 | loss=1.5775
   [val] batch 2/2 | loss=1.5254
Epoch 05 | train_macro_f1=0.8302 | val_macro_f1=0.0952

Epoch 6/12
   [train] batch 1/14 | loss=0.8504
   [train] batch 11/14 | loss=0.6633
   [train] batch 14/14 | loss=0.9255
   [val] batch 1/2 | loss=1.4437
   [val] batch 2/2 | loss=1.4912
Epoch 06 | train_macro_f1=0.8874 | val_macro_f1=0.3095

Epoch 7/12
   [train] batch 1/14 | loss=0.6870
   [train] batch 11/14 | loss=0.4653
   [train] batch 14/14 | loss=0.6361
   [val] batch 1/2 | loss=1.3350
   [val] batch 2/2 | loss=1.5377
Epoch 07 | train_macro_f1=0.9199 | val_macro_f1=0.3571

Epoch 8/12
   [train] batch 1/14 | loss=0.4864
   [train] batch 11/14 | loss=0.4211
   [train] batch 14/14 | loss=0.3756
   [val] batch 1/2 | loss=1.3540
   [val] batch 2/2 | loss=1.2825
Epoch 08 | train_macro_f1=0.9392 | val_macro_f1=0.3186

Epoch 9/12
   [train] batch 1/14 | loss=0.3428
   [train] batch 11/14 | loss=0.3475
   [train] batch 14/14 | loss=0.3563
   [val] batch 1/2 | loss=1.2655
   [val] batch 2/2 | loss=1.2342
Epoch 09 | train_macro_f1=0.9618 | val_macro_f1=0.3452

Epoch 10/12
   [train] batch 1/14 | loss=0.3615
   [train] batch 11/14 | loss=0.2544
   [train] batch 14/14 | loss=0.6075
   [val] batch 1/2 | loss=1.0846
   [val] batch 2/2 | loss=1.2759
Epoch 10 | train_macro_f1=0.9576 | val_macro_f1=0.4373

Epoch 11/12
   [train] batch 1/14 | loss=0.1865
   [train] batch 11/14 | loss=0.1687
   [train] batch 14/14 | loss=0.2485
   [val] batch 1/2 | loss=1.3808
   [val] batch 2/2 | loss=1.2400
Epoch 11 | train_macro_f1=0.9809 | val_macro_f1=0.3800

Epoch 12/12
   [train] batch 1/14 | loss=0.1253
   [train] batch 11/14 | loss=0.1432
   [train] batch 14/14 | loss=0.4794
   [val] batch 1/2 | loss=1.2476
   [val] batch 2/2 | loss=1.2203
Epoch 12 | train_macro_f1=0.9905 | val_macro_f1=0.4757
{
  "protocol_name": "protocol_B_4_to_4",
  "frame_source": "RGB",
  "model_name": "efficientnet_b0",
  "num_sample_frames": 32,
  "batch_size": 16,
  "best_epoch": 12,
  "best_val_macro_f1": 0.4757369614512471,
  "test_accuracy": 0.9495798319327731,
  "test_macro_f1": 0.9497035690076286,
  "test_weighted_f1": 0.9497035690076286,
  "per_class_f1": {
    "doctor": 0.9393939393939394,
    "emergency": 1.0,
    "fire": 0.9705882352941176,
    "help": 0.9696969696969697,
    "robbery": 0.9295774647887324,
    "sit_down": 0.9295774647887324,
    "stand_up": 0.9090909090909091
  },
  "train_time_minutes": 23.6880752325058,
  "inference_time_seconds": 100.2842116355896,
  "videos_per_second": 2.3732549333372512,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_4__rgb__efficientnet_b0__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_4__rgb__efficientnet_b0__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_4__rgb__efficientnet_b0__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_remaining_protocols/protocol_B_4_to_4__rgb__efficientnet_b0__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_4 | frame_source=RGB | model=mobilenet_v3_small
====================================================================================================
train=215, val=23, test=238
Building sampled frame paths for 215 samples...
Building sampled frame paths for 23 samples...
Building sampled frame paths for 238 samples...

Epoch 1/12
   [train] batch 1/7 | loss=1.9935
   [train] batch 7/7 | loss=1.9903
   [val] batch 1/1 | loss=1.9423
Epoch 01 | train_macro_f1=0.1254 | val_macro_f1=0.0260

Epoch 2/12
   [train] batch 1/7 | loss=1.8684
   [train] batch 7/7 | loss=1.9071
   [val] batch 1/1 | loss=1.9178
Epoch 02 | train_macro_f1=0.2763 | val_macro_f1=0.0476

Epoch 3/12
   [train] batch 1/7 | loss=1.7856
   [train] batch 7/7 | loss=1.7773
   [val] batch 1/1 | loss=1.8784
Epoch 03 | train_macro_f1=0.4385 | val_macro_f1=0.2000

Epoch 4/12
   [train] batch 1/7 | loss=1.7592
   [train] batch 7/7 | loss=1.5592
   [val] batch 1/1 | loss=1.8467
Epoch 04 | train_macro_f1=0.5201 | val_macro_f1=0.2395

Epoch 5/12
   [train] batch 1/7 | loss=1.6341
   [train] batch 7/7 | loss=1.5859
   [val] batch 1/1 | loss=1.8088
Epoch 05 | train_macro_f1=0.6315 | val_macro_f1=0.1643

Epoch 6/12
   [train] batch 1/7 | loss=1.4955
   [train] batch 7/7 | loss=1.5089
   [val] batch 1/1 | loss=1.7496
Epoch 06 | train_macro_f1=0.6299 | val_macro_f1=0.1585

Epoch 7/12
   [train] batch 1/7 | loss=1.4504
   [train] batch 7/7 | loss=1.3927
   [val] batch 1/1 | loss=1.6739
Epoch 07 | train_macro_f1=0.6888 | val_macro_f1=0.1878

Epoch 8/12
   [train] batch 1/7 | loss=1.3086
   [train] batch 7/7 | loss=1.2221
   [val] batch 1/1 | loss=1.6178
Epoch 08 | train_macro_f1=0.7376 | val_macro_f1=0.1893
Early stopping triggered.
{
  "protocol_name": "protocol_B_4_to_4",
  "frame_source": "RGB",
  "model_name": "mobilenet_v3_small",
  "num_sample_frames": 32,
  "batch_size": 32,
  "best_epoch": 4,
  "best_val_macro_f1": 0.23953823953823955,
  "test_accuracy": 0.3067226890756303,
  "test_macro_f1": 0.2634504078795686,
  "test_weighted_f1": 0.2634504078795685,
  "per_class_f1": {
    "doctor": 0.3291139240506329,
    "emergency": 0.48,
    "fire": 0.05714285714285714,
    "help": 0.2545454545454545,
    "robbery": 0.25,
    "sit_down": 0.10256410256410256,
    "stand_up": 0.3707865168539326
  },
  "train_time_minutes": 15.1691197514534,
  "inference_time_seconds": 139.66842246055603,
  "videos_per_second": 1.7040358572619658,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_4__rgb__mobilenet_v3_small__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_4__rgb__mobilenet_v3_small__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_4__rgb__mobilenet_v3_small__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_remaining_protocols/protocol_B_4_to_4__rgb__mobilenet_v3_small__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_6 | frame_source=RGB | model=resnet18
====================================================================================================
train=215, val=23, test=245
Building sampled frame paths for 215 samples...
Building sampled frame paths for 23 samples...
Building sampled frame paths for 245 samples...

Epoch 1/12
   [train] batch 1/9 | loss=2.0939
   [train] batch 9/9 | loss=1.7276
   [val] batch 1/1 | loss=1.6237
Epoch 01 | train_macro_f1=0.1836 | val_macro_f1=0.2050

Epoch 2/12
   [train] batch 1/9 | loss=1.2406
   [train] batch 9/9 | loss=0.7730
   [val] batch 1/1 | loss=1.2861
Epoch 02 | train_macro_f1=0.7582 | val_macro_f1=0.3039

Epoch 3/12
   [train] batch 1/9 | loss=0.5648
   [train] batch 9/9 | loss=0.5415
   [val] batch 1/1 | loss=1.0937
Epoch 03 | train_macro_f1=0.9148 | val_macro_f1=0.4589

Epoch 4/12
   [train] batch 1/9 | loss=0.3910
   [train] batch 9/9 | loss=0.3202
   [val] batch 1/1 | loss=1.0660
Epoch 04 | train_macro_f1=0.9952 | val_macro_f1=0.4841

Epoch 5/12
   [train] batch 1/9 | loss=0.2084
   [train] batch 9/9 | loss=0.1761
   [val] batch 1/1 | loss=1.1984
Epoch 05 | train_macro_f1=1.0000 | val_macro_f1=0.3869

Epoch 6/12
   [train] batch 1/9 | loss=0.1363
   [train] batch 9/9 | loss=0.1256
   [val] batch 1/1 | loss=1.3897
Epoch 06 | train_macro_f1=1.0000 | val_macro_f1=0.3955

Epoch 7/12
   [train] batch 1/9 | loss=0.0955
   [train] batch 9/9 | loss=0.1114
   [val] batch 1/1 | loss=1.3522
Epoch 07 | train_macro_f1=1.0000 | val_macro_f1=0.3490

Epoch 8/12
   [train] batch 1/9 | loss=0.0600
   [train] batch 9/9 | loss=0.0298
   [val] batch 1/1 | loss=1.3732
Epoch 08 | train_macro_f1=1.0000 | val_macro_f1=0.4245
Early stopping triggered.
{
  "protocol_name": "protocol_B_4_to_6",
  "frame_source": "RGB",
  "model_name": "resnet18",
  "num_sample_frames": 32,
  "batch_size": 24,
  "best_epoch": 4,
  "best_val_macro_f1": 0.48412698412698413,
  "test_accuracy": 0.5551020408163265,
  "test_macro_f1": 0.5570250565281891,
  "test_weighted_f1": 0.5570250565281891,
  "per_class_f1": {
    "doctor": 0.5,
    "emergency": 0.7941176470588235,
    "fire": 0.6666666666666666,
    "help": 0.4827586206896552,
    "robbery": 0.41975308641975306,
    "sit_down": 0.4935064935064935,
    "stand_up": 0.5423728813559322
  },
  "train_time_minutes": 15.180778181552887,
  "inference_time_seconds": 604.7154569625854,
  "videos_per_second": 0.40514922709369156,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 245,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_6__rgb__resnet18__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_6__rgb__resnet18__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_6__rgb__resnet18__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_remaining_protocols/protocol_B_4_to_6__rgb__resnet18__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_6 | frame_source=RGB | model=efficientnet_b0
====================================================================================================
train=215, val=23, test=245
Building sampled frame paths for 215 samples...
Building sampled frame paths for 23 samples...
Building sampled frame paths for 245 samples...

Epoch 1/12
   [train] batch 1/14 | loss=1.9230
   [train] batch 11/14 | loss=1.9532
   [train] batch 14/14 | loss=1.9240
   [val] batch 1/2 | loss=1.9276
   [val] batch 2/2 | loss=1.8531
Epoch 01 | train_macro_f1=0.1598 | val_macro_f1=0.1476

Epoch 2/12
   [train] batch 1/14 | loss=1.7748
   [train] batch 11/14 | loss=1.5443
   [train] batch 14/14 | loss=1.6056
   [val] batch 1/2 | loss=1.8383
   [val] batch 2/2 | loss=1.7706
Epoch 02 | train_macro_f1=0.5230 | val_macro_f1=0.2381

Epoch 3/12
   [train] batch 1/14 | loss=1.5666
   [train] batch 11/14 | loss=1.4078
   [train] batch 14/14 | loss=1.3962
   [val] batch 1/2 | loss=1.6870
   [val] batch 2/2 | loss=1.6238
Epoch 03 | train_macro_f1=0.7110 | val_macro_f1=0.2381

Epoch 4/12
   [train] batch 1/14 | loss=1.3744
   [train] batch 11/14 | loss=1.3080
   [train] batch 14/14 | loss=1.3140
   [val] batch 1/2 | loss=1.5202
   [val] batch 2/2 | loss=1.5089
Epoch 04 | train_macro_f1=0.7940 | val_macro_f1=0.2833

Epoch 5/12
   [train] batch 1/14 | loss=1.1332
   [train] batch 11/14 | loss=0.9299
   [train] batch 14/14 | loss=1.1374
   [val] batch 1/2 | loss=1.4201
   [val] batch 2/2 | loss=1.4473
Epoch 05 | train_macro_f1=0.8382 | val_macro_f1=0.3039

Epoch 6/12
   [train] batch 1/14 | loss=0.8186
   [train] batch 11/14 | loss=1.0131
   [train] batch 14/14 | loss=0.6952
   [val] batch 1/2 | loss=1.2698
   [val] batch 2/2 | loss=1.3721
Epoch 06 | train_macro_f1=0.8487 | val_macro_f1=0.3810

Epoch 7/12
   [train] batch 1/14 | loss=0.7358
   [train] batch 11/14 | loss=0.5203
   [train] batch 14/14 | loss=0.7395
   [val] batch 1/2 | loss=1.1480
   [val] batch 2/2 | loss=1.2030
Epoch 07 | train_macro_f1=0.9146 | val_macro_f1=0.5111

Epoch 8/12
   [train] batch 1/14 | loss=0.4154
   [train] batch 11/14 | loss=0.2962
   [train] batch 14/14 | loss=0.5704
   [val] batch 1/2 | loss=1.0428
   [val] batch 2/2 | loss=1.1270
Epoch 08 | train_macro_f1=0.9486 | val_macro_f1=0.4785

Epoch 9/12
   [train] batch 1/14 | loss=0.3273
   [train] batch 11/14 | loss=0.4670
   [train] batch 14/14 | loss=0.7328
   [val] batch 1/2 | loss=1.0329
   [val] batch 2/2 | loss=1.0053
Epoch 09 | train_macro_f1=0.9526 | val_macro_f1=0.5257

Epoch 10/12
   [train] batch 1/14 | loss=0.2882
   [train] batch 11/14 | loss=0.5290
   [train] batch 14/14 | loss=0.3359
   [val] batch 1/2 | loss=0.9479
   [val] batch 2/2 | loss=1.1267
Epoch 10 | train_macro_f1=0.9714 | val_macro_f1=0.5214

Epoch 11/12
   [train] batch 1/14 | loss=0.2559
   [train] batch 11/14 | loss=0.2553
   [train] batch 14/14 | loss=0.1789
   [val] batch 1/2 | loss=1.1050
   [val] batch 2/2 | loss=1.2289
Epoch 11 | train_macro_f1=0.9905 | val_macro_f1=0.4332

Epoch 12/12
   [train] batch 1/14 | loss=0.1693
   [train] batch 11/14 | loss=0.2259
   [train] batch 14/14 | loss=0.1410
   [val] batch 1/2 | loss=1.0901
   [val] batch 2/2 | loss=1.0194
Epoch 12 | train_macro_f1=0.9952 | val_macro_f1=0.4968
{
  "protocol_name": "protocol_B_4_to_6",
  "frame_source": "RGB",
  "model_name": "efficientnet_b0",
  "num_sample_frames": 32,
  "batch_size": 16,
  "best_epoch": 9,
  "best_val_macro_f1": 0.525664811379097,
  "test_accuracy": 0.5551020408163265,
  "test_macro_f1": 0.5469690539708439,
  "test_weighted_f1": 0.546969053970844,
  "per_class_f1": {
    "doctor": 0.43137254901960786,
    "emergency": 0.5614035087719298,
    "fire": 0.7654320987654321,
    "help": 0.5,
    "robbery": 0.49557522123893805,
    "sit_down": 0.575,
    "stand_up": 0.5
  },
  "train_time_minutes": 23.302898879845937,
  "inference_time_seconds": 331.42071080207825,
  "videos_per_second": 0.7392416708269991,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 245,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_6__rgb__efficientnet_b0__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_6__rgb__efficientnet_b0__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_remaining_protocols/protocol_B_4_to_6__rgb__efficientnet_b0__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_remaining_protocols/protocol_B_4_to_6__rgb__efficientnet_b0__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_6 | frame_source=RGB | model=mobilenet_v3_small
====================================================================================================

In [1]:
# ============================================================
# FAST RESUME-ONLY STAGE-5 RUNNER
# Skips finished runs automatically using existing metrics.json
# ============================================================

import os
import gc
import json
import time
import copy
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision.models import (
    resnet18, ResNet18_Weights,
    efficientnet_b0, EfficientNet_B0_Weights,
    mobilenet_v3_small, MobileNet_V3_Small_Weights,
)

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 300)

# ============================================================
# 1. SETTINGS
# ============================================================
SEED = 42
IMG_SIZE = 224
NUM_SAMPLE_FRAMES = 32

# Keep these practical; much larger can slow or OOM.
BATCH_SIZE_BY_MODEL = {
    "resnet18": 24,
    "efficientnet_b0": 16,
    "mobilenet_v3_small": 32,
}

EPOCHS = 12
LR = 1e-4
WEIGHT_DECAY = 1e-4
PATIENCE = 4

USE_AMP = True
USE_PRETRAINED = True
USE_TORCH_COMPILE = True   # if PyTorch 2.x; if unstable, set False

# Faster data loading. If notebook hangs, reduce NUM_WORKERS to 0.
NUM_WORKERS = 4
PIN_MEMORY = True
PERSISTENT_WORKERS = True
PREFETCH_FACTOR = 4

SAMPLE_START_FRAC = 0.10
SAMPLE_END_FRAC = 0.90

FRAME_SOURCES = ["RGB", "RGB_BGREM"]
MODELS_TO_RUN = ["resnet18", "efficientnet_b0", "mobilenet_v3_small"]

# Full protocol list. Finished runs will be skipped automatically.
SPLIT_CONFIGS = [
    ("protocol_A", "protocol_A_train.csv", "protocol_A_val.csv", "protocol_A_test.csv"),

    ("protocol_B_4_to_4", "protocol_B_train_4_test_4.csv", None, "protocol_B_test_4_same.csv"),
    ("protocol_B_4_to_6", "protocol_B_train_4_test_6.csv", None, "protocol_B_test_6.csv"),
    ("protocol_B_4_to_8", "protocol_B_train_4_test_8.csv", None, "protocol_B_test_8.csv"),

    ("protocol_B_6_to_4", "protocol_B_train_6_test_4.csv", None, "protocol_B_test_4.csv"),
    ("protocol_B_6_to_6", "protocol_B_train_6_test_6.csv", None, "protocol_B_test_6_same.csv"),
    ("protocol_B_6_to_8", "protocol_B_train_6_test_8.csv", None, "protocol_B_test_8.csv"),

    ("protocol_B_8_to_4", "protocol_B_train_8_test_4.csv", None, "protocol_B_test_4.csv"),
    ("protocol_B_8_to_6", "protocol_B_train_8_test_6.csv", None, "protocol_B_test_6.csv"),
    ("protocol_B_8_to_8", "protocol_B_train_8_test_8.csv", None, "protocol_B_test_8_same.csv"),

    ("protocol_B_4_6_to_4", "protocol_B_train_4_6_test_4.csv", None, "protocol_B_test_4_from_4_6.csv"),
    ("protocol_B_4_6_to_6", "protocol_B_train_4_6_test_6.csv", None, "protocol_B_test_6_from_4_6.csv"),
    ("protocol_B_4_6_to_8", "protocol_B_train_4_6_test_8.csv", None, "protocol_B_test_8_from_4_6.csv"),

    ("protocol_B_4_8_to_4", "protocol_B_train_4_8_test_4.csv", None, "protocol_B_test_4_from_4_8.csv"),
    ("protocol_B_4_8_to_6", "protocol_B_train_4_8_test_6.csv", None, "protocol_B_test_6_from_4_8.csv"),
    ("protocol_B_4_8_to_8", "protocol_B_train_4_8_test_8.csv", None, "protocol_B_test_8_from_4_8.csv"),

    ("protocol_B_6_8_to_4", "protocol_B_train_6_8_test_4.csv", None, "protocol_B_test_4_from_6_8.csv"),
    ("protocol_B_6_8_to_6", "protocol_B_train_6_8_test_6.csv", None, "protocol_B_test_6_from_6_8.csv"),
    ("protocol_B_6_8_to_8", "protocol_B_train_6_8_test_8.csv", None, "protocol_B_test_8_from_6_8.csv"),

    ("protocol_B_4_6_8_to_4", "protocol_B_train_4_6_8_test_4.csv", None, "protocol_B_test_4_from_4_6_8.csv"),
    ("protocol_B_4_6_8_to_6", "protocol_B_train_4_6_8_test_6.csv", None, "protocol_B_test_6_from_4_6_8.csv"),
    ("protocol_B_4_6_8_to_8", "protocol_B_train_4_6_8_test_8.csv", None, "protocol_B_test_8_from_4_6_8.csv"),
]

CLASS_NAMES = ["doctor", "emergency", "fire", "help", "robbery", "sit_down", "stand_up"]
label2id = {c: i for i, c in enumerate(CLASS_NAMES)}
id2label = {i: c for c, i in label2id.items()}
NUM_CLASSES = len(CLASS_NAMES)

# ============================================================
# 2. REPRODUCIBILITY
# ============================================================
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(SEED)

# ============================================================
# 3. PATHS
# ============================================================
cwd = Path.cwd()
ROOT = cwd.parent if cwd.name == "notebooks" else cwd

SPLIT_DIR = ROOT / "data" / "processed" / "splits"
MANIFEST_DIR = ROOT / "data" / "processed" / "manifests"
FRAME_SUMMARY_CSV = MANIFEST_DIR / "frame_extraction_trimmed_summary.csv"

# IMPORTANT: look for finished runs in ALL prior results roots too
SEARCH_RESULTS_DIRS = [
    ROOT / "results" / "stage5_rgb_master",
    ROOT / "results" / "stage5_remaining_protocols",
    ROOT / "results" / "stage5_resume_all",
]

RESULTS_ROOT = ROOT / "results" / "stage5_resume_all"
CHECKPOINT_ROOT = ROOT / "checkpoints" / "stage5_resume_all"
LOG_ROOT = ROOT / "logs" / "stage5_resume_all"

RESULTS_ROOT.mkdir(parents=True, exist_ok=True)
CHECKPOINT_ROOT.mkdir(parents=True, exist_ok=True)
LOG_ROOT.mkdir(parents=True, exist_ok=True)

print("ROOT:", ROOT)
print("RESULTS_ROOT:", RESULTS_ROOT)

# ============================================================
# 4. DEVICE / SPEED FLAGS
# ============================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))

torch.backends.cudnn.benchmark = True
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
try:
    torch.set_float32_matmul_precision("high")
except Exception:
    pass

# ============================================================
# 5. LOAD FRAME SUMMARY
# ============================================================
frame_df_all = pd.read_csv(FRAME_SUMMARY_CSV)
frame_df_all = frame_df_all[frame_df_all["status"] == "success"].copy()
frame_df_all = frame_df_all[["pair_id", "modality", "output_dir", "frames_extracted"]].drop_duplicates()

# ============================================================
# 6. DISCOVER FINISHED RUNS FROM OLD RESULTS
# ============================================================
finished_keys = set()

for base in SEARCH_RESULTS_DIRS:
    if not base.exists():
        continue
    for mf in base.rglob("metrics.json"):
        try:
            with open(mf, "r") as f:
                m = json.load(f)
            key = (m.get("protocol_name"), m.get("frame_source"), m.get("model_name"))
            if all(key):
                finished_keys.add(key)
        except Exception:
            pass

print("Already finished runs discovered:", len(finished_keys))

# ============================================================
# 7. HELPERS
# ============================================================
def sample_indices_middle_region(n_total, n_samples, start_frac=0.10, end_frac=0.90):
    if n_total <= 0:
        return [0] * n_samples
    start_idx = int(round(start_frac * (n_total - 1)))
    end_idx = int(round(end_frac * (n_total - 1)))
    start_idx = max(0, min(start_idx, n_total - 1))
    end_idx = max(start_idx, min(end_idx, n_total - 1))
    idxs = np.linspace(start_idx, end_idx, n_samples)
    idxs = np.round(idxs).astype(int)
    return np.clip(idxs, 0, n_total - 1).tolist()

def frame_index_to_path(frame_dir, idx):
    return Path(frame_dir) / f"frame_{idx+1:06d}.jpg"

def load_split_df(csv_name):
    csv_path = SPLIT_DIR / csv_name
    if not csv_path.exists():
        raise FileNotFoundError(f"Missing split file: {csv_path}")
    df = pd.read_csv(csv_path)
    if "is_valid_pair" in df.columns:
        df = df[df["is_valid_pair"] == True].copy()
    return df.reset_index(drop=True)

def attach_labels(df_):
    out = df_.copy()
    out = out[out["gesture"].isin(CLASS_NAMES)].copy()
    out["label"] = out["gesture"].map(label2id)
    return out.reset_index(drop=True)

def attach_frame_info(df_, frame_source):
    sub = frame_df_all[frame_df_all["modality"] == frame_source].copy()
    sub = sub.rename(columns={"output_dir": "frame_dir", "frames_extracted": "num_frames_available"})
    sub = sub[["pair_id", "frame_dir", "num_frames_available"]].drop_duplicates()
    out = df_.merge(sub, on="pair_id", how="left")
    out = out[out["num_frames_available"].fillna(0) > 0].copy().reset_index(drop=True)
    out["num_frames_available"] = out["num_frames_available"].astype(int)
    return out

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225]),
])

class FrameVotingDataset(Dataset):
    def __init__(self, df, transform, num_sample_frames=32):
        self.df = df.reset_index(drop=True).copy()
        self.transform = transform
        self.sampled_paths = []
        for _, row in self.df.iterrows():
            idxs = sample_indices_middle_region(
                int(row["num_frames_available"]),
                num_sample_frames,
                SAMPLE_START_FRAC,
                SAMPLE_END_FRAC
            )
            self.sampled_paths.append([frame_index_to_path(row["frame_dir"], i) for i in idxs])

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        frames = []
        for p in self.sampled_paths[idx]:
            try:
                with Image.open(p) as f:
                    img = f.convert("RGB")
            except Exception:
                img = Image.fromarray(np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8))
            frames.append(self.transform(img))
        frames = torch.stack(frames, dim=0)
        meta = {
            "pair_id": row["pair_id"],
            "subject_id": row["subject_id"],
            "distance": row["distance"],
            "gesture": row["gesture"],
            "frame_dir": row["frame_dir"],
        }
        return frames, int(row["label"]), meta

def collate_fn(batch):
    frames = torch.stack([x[0] for x in batch], dim=0)
    labels = torch.tensor([x[1] for x in batch], dtype=torch.long)
    metas = [x[2] for x in batch]
    return frames, labels, metas

def create_model(model_name):
    if model_name == "resnet18":
        model = resnet18(weights=ResNet18_Weights.DEFAULT if USE_PRETRAINED else None)
        model.fc = nn.Linear(model.fc.in_features, NUM_CLASSES)
    elif model_name == "efficientnet_b0":
        model = efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT if USE_PRETRAINED else None)
        model.classifier[1] = nn.Linear(model.classifier[1].in_features, NUM_CLASSES)
    elif model_name == "mobilenet_v3_small":
        model = mobilenet_v3_small(weights=MobileNet_V3_Small_Weights.DEFAULT if USE_PRETRAINED else None)
        model.classifier[3] = nn.Linear(model.classifier[3].in_features, NUM_CLASSES)
    else:
        raise ValueError(model_name)

    model = model.to(device)
    model = model.to(memory_format=torch.channels_last)

    if USE_TORCH_COMPILE and hasattr(torch, "compile"):
        try:
            model = torch.compile(model, mode="reduce-overhead")
        except Exception:
            pass

    return model

def forward_video_voting(model, frames):
    B, T, C, H, W = frames.shape
    frames = frames.view(B * T, C, H, W).contiguous(memory_format=torch.channels_last)
    logits = model(frames)
    logits = logits.view(B, T, -1)
    return logits.mean(dim=1)

def make_loader(dataset, batch_size, shuffle):
    kwargs = dict(
        dataset=dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY and device.type == "cuda",
        collate_fn=collate_fn,
    )
    if NUM_WORKERS > 0:
        kwargs["persistent_workers"] = PERSISTENT_WORKERS
        kwargs["prefetch_factor"] = PREFETCH_FACTOR
    return DataLoader(**kwargs)

def run_one_epoch(model, loader, criterion, optimizer=None, scaler=None, train=True):
    model.train() if train else model.eval()
    total_loss = 0.0
    all_labels, all_preds = [], []

    for batch_idx, (frames, labels, metas) in enumerate(loader):
        frames = frames.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        if train:
            optimizer.zero_grad(set_to_none=True)

        with torch.set_grad_enabled(train):
            with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=(USE_AMP and device.type == "cuda")):
                logits = forward_video_voting(model, frames)
                loss = criterion(logits, labels)

            if train:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()

        preds = logits.argmax(dim=1)
        total_loss += loss.item() * labels.size(0)
        all_labels.extend(labels.detach().cpu().tolist())
        all_preds.extend(preds.detach().cpu().tolist())

        if batch_idx % 10 == 0 or batch_idx == len(loader) - 1:
            mode = "train" if train else "val"
            print(f"   [{mode}] batch {batch_idx+1}/{len(loader)} | loss={loss.item():.4f}")

    return {
        "loss": total_loss / len(loader.dataset),
        "accuracy": accuracy_score(all_labels, all_preds),
        "macro_f1": f1_score(all_labels, all_preds, average="macro"),
        "weighted_f1": f1_score(all_labels, all_preds, average="weighted"),
    }

@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    all_labels, all_preds, rows = [], [], []
    start = time.time()
    total_samples = 0

    for frames, labels, metas in loader:
        frames = frames.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=(USE_AMP and device.type == "cuda")):
            logits = forward_video_voting(model, frames)
            probs = torch.softmax(logits, dim=1)
            preds = probs.argmax(dim=1)

        labels_np = labels.detach().cpu().numpy()
        preds_np = preds.detach().cpu().numpy()
        probs_np = probs.detach().cpu().numpy()

        total_samples += len(labels_np)
        all_labels.extend(labels_np.tolist())
        all_preds.extend(preds_np.tolist())

        for i, meta in enumerate(metas):
            row = {
                "pair_id": meta["pair_id"],
                "subject_id": meta["subject_id"],
                "distance": meta["distance"],
                "gesture_true": id2label[int(labels_np[i])],
                "gesture_pred": id2label[int(preds_np[i])],
                "frame_dir": meta["frame_dir"],
            }
            for c_idx, c_name in id2label.items():
                row[f"prob_{c_name}"] = float(probs_np[i][c_idx])
            rows.append(row)

    infer_time = time.time() - start
    videos_per_second = total_samples / infer_time if infer_time > 0 else None
    return all_labels, all_preds, pd.DataFrame(rows), infer_time, videos_per_second

def run_experiment(protocol_name, train_csv_name, val_csv_name, test_csv_name, frame_source, model_name):
    run_name = f"{protocol_name}__{frame_source.lower()}__{model_name}__f{NUM_SAMPLE_FRAMES}__img{IMG_SIZE}"
    results_dir = RESULTS_ROOT / run_name
    checkpoint_dir = CHECKPOINT_ROOT / run_name
    log_dir = LOG_ROOT / run_name
    results_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)

    print("\n" + "="*100)
    print(f"RUNNING | protocol={protocol_name} | frame_source={frame_source} | model={model_name}")
    print("="*100)

    train_df = load_split_df(train_csv_name)
    test_df = load_split_df(test_csv_name)
    if val_csv_name is None:
        train_df = train_df.sample(frac=1.0, random_state=SEED).reset_index(drop=True)
        n_val = max(1, int(0.10 * len(train_df)))
        val_df = train_df.iloc[:n_val].copy().reset_index(drop=True)
        train_df = train_df.iloc[n_val:].copy().reset_index(drop=True)
    else:
        val_df = load_split_df(val_csv_name)

    train_df = attach_frame_info(attach_labels(train_df), frame_source)
    val_df = attach_frame_info(attach_labels(val_df), frame_source)
    test_df = attach_frame_info(attach_labels(test_df), frame_source)

    print(f"train={len(train_df)}, val={len(val_df)}, test={len(test_df)}")

    batch_size = BATCH_SIZE_BY_MODEL[model_name]

    train_loader = make_loader(FrameVotingDataset(train_df, train_transform, NUM_SAMPLE_FRAMES), batch_size, True)
    val_loader = make_loader(FrameVotingDataset(val_df, eval_transform, NUM_SAMPLE_FRAMES), batch_size, False)
    test_loader = make_loader(FrameVotingDataset(test_df, eval_transform, NUM_SAMPLE_FRAMES), batch_size, False)

    model = create_model(model_name)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    scaler = torch.amp.GradScaler("cuda", enabled=(USE_AMP and device.type == "cuda"))

    best_val_f1 = -1.0
    best_epoch = -1
    best_state_dict = None
    patience_ctr = 0
    history = []

    train_start = time.time()
    for epoch in range(1, EPOCHS + 1):
        print(f"\nEpoch {epoch}/{EPOCHS}")
        train_m = run_one_epoch(model, train_loader, criterion, optimizer, scaler, True)
        val_m = run_one_epoch(model, val_loader, criterion, None, scaler, False)

        history.append({
            "epoch": epoch,
            "train_loss": train_m["loss"],
            "train_acc": train_m["accuracy"],
            "train_macro_f1": train_m["macro_f1"],
            "train_weighted_f1": train_m["weighted_f1"],
            "val_loss": val_m["loss"],
            "val_acc": val_m["accuracy"],
            "val_macro_f1": val_m["macro_f1"],
            "val_weighted_f1": val_m["weighted_f1"],
        })

        if val_m["macro_f1"] > best_val_f1:
            best_val_f1 = val_m["macro_f1"]
            best_epoch = epoch
            patience_ctr = 0
            best_state_dict = copy.deepcopy(model.state_dict())
            torch.save({
                "epoch": epoch,
                "model_state_dict": best_state_dict,
                "protocol_name": protocol_name,
                "frame_source": frame_source,
                "model_name": model_name,
            }, checkpoint_dir / "best_model.pt")
        else:
            patience_ctr += 1

        print(f"Epoch {epoch:02d} | train_macro_f1={train_m['macro_f1']:.4f} | val_macro_f1={val_m['macro_f1']:.4f}")

        if patience_ctr >= PATIENCE:
            print("Early stopping triggered.")
            break

    train_minutes = (time.time() - train_start) / 60.0
    pd.DataFrame(history).to_csv(log_dir / "training_log.csv", index=False)

    model.load_state_dict(best_state_dict)
    test_labels, test_preds, pred_df, infer_seconds, videos_per_second = evaluate(model, test_loader)

    test_accuracy = accuracy_score(test_labels, test_preds)
    test_macro_f1 = f1_score(test_labels, test_preds, average="macro")
    test_weighted_f1 = f1_score(test_labels, test_preds, average="weighted")

    report = classification_report(
        test_labels, test_preds,
        target_names=[id2label[i] for i in range(NUM_CLASSES)],
        output_dict=True, zero_division=0
    )
    report_df = pd.DataFrame(report).transpose()

    pred_csv = results_dir / "test_predictions.csv"
    report_csv = results_dir / "classification_report.csv"
    metrics_json = results_dir / "metrics.json"

    pred_df.to_csv(pred_csv, index=False)
    report_df.to_csv(report_csv)

    per_class_f1 = {}
    for cls in CLASS_NAMES:
        if cls in report_df.index:
            per_class_f1[cls] = float(report_df.loc[cls, "f1-score"])

    metrics = {
        "protocol_name": protocol_name,
        "frame_source": frame_source,
        "model_name": model_name,
        "num_sample_frames": NUM_SAMPLE_FRAMES,
        "batch_size": batch_size,
        "best_epoch": int(best_epoch),
        "best_val_macro_f1": float(best_val_f1),
        "test_accuracy": float(test_accuracy),
        "test_macro_f1": float(test_macro_f1),
        "test_weighted_f1": float(test_weighted_f1),
        "per_class_f1": per_class_f1,
        "train_time_minutes": float(train_minutes),
        "inference_time_seconds": float(infer_seconds),
        "videos_per_second": float(videos_per_second) if videos_per_second is not None else None,
        "train_rows": int(len(train_df)),
        "val_rows": int(len(val_df)),
        "test_rows": int(len(test_df)),
        "predictions_csv": str(pred_csv),
        "classification_report_csv": str(report_csv),
        "checkpoint_best": str(checkpoint_dir / "best_model.pt"),
    }

    with open(metrics_json, "w") as f:
        json.dump(metrics, f, indent=2)

    del model, train_loader, val_loader, test_loader, best_state_dict
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return metrics

# ============================================================
# 8. RUN ONLY MISSING
# ============================================================
summary_csv = RESULTS_ROOT / "resume_summary.csv"
all_metrics = []
if summary_csv.exists():
    try:
        all_metrics = pd.read_csv(summary_csv).to_dict(orient="records")
    except Exception:
        all_metrics = []

done_keys = set((m["protocol_name"], m["frame_source"], m["model_name"]) for m in all_metrics if "protocol_name" in m)
done_keys |= finished_keys

pending = []
for frame_source in FRAME_SOURCES:
    for protocol_name, train_csv_name, val_csv_name, test_csv_name in SPLIT_CONFIGS:
        for model_name in MODELS_TO_RUN:
            key = (protocol_name, frame_source, model_name)
            if key not in done_keys:
                pending.append((protocol_name, train_csv_name, val_csv_name, test_csv_name, frame_source, model_name))

print("\nPending runs:", len(pending))
for p in pending[:20]:
    print(" ", (p[0], p[4], p[5]))

for protocol_name, train_csv_name, val_csv_name, test_csv_name, frame_source, model_name in pending:
    metrics = run_experiment(protocol_name, train_csv_name, val_csv_name, test_csv_name, frame_source, model_name)
    all_metrics.append(metrics)
    done_keys.add((protocol_name, frame_source, model_name))
    pd.DataFrame(all_metrics).to_csv(summary_csv, index=False)

print("\nResume finished.")
print("Saved:", summary_csv)

ROOT: /data/Sajjan_Singh/gesture_recognition
RESULTS_ROOT: /data/Sajjan_Singh/gesture_recognition/results/stage5_resume_all
Using device: cuda
GPU name: NVIDIA H100 NVL
Already finished runs discovered: 76

Pending runs: 56
  ('protocol_B_6_to_4', 'RGB', 'resnet18')
  ('protocol_B_6_to_4', 'RGB', 'efficientnet_b0')
  ('protocol_B_6_to_4', 'RGB', 'mobilenet_v3_small')
  ('protocol_B_4_6_8_to_6', 'RGB', 'efficientnet_b0')
  ('protocol_B_4_6_8_to_6', 'RGB', 'mobilenet_v3_small')
  ('protocol_B_4_6_8_to_8', 'RGB', 'resnet18')
  ('protocol_B_4_6_8_to_8', 'RGB', 'efficientnet_b0')
  ('protocol_B_4_6_8_to_8', 'RGB', 'mobilenet_v3_small')
  ('protocol_B_4_to_4', 'RGB_BGREM', 'resnet18')
  ('protocol_B_4_to_4', 'RGB_BGREM', 'efficientnet_b0')
  ('protocol_B_4_to_4', 'RGB_BGREM', 'mobilenet_v3_small')
  ('protocol_B_4_to_6', 'RGB_BGREM', 'resnet18')
  ('protocol_B_4_to_6', 'RGB_BGREM', 'efficientnet_b0')
  ('protocol_B_4_to_6', 'RGB_BGREM', 'mobilenet_v3_small')
  ('protocol_B_6_to_4', 'RGB_BGREM', 'resnet18')
  ('protocol_B_6_to_4', 'RGB_BGREM', 'efficientnet_b0')
  ('protocol_B_6_to_4', 'RGB_BGREM', 'mobilenet_v3_small')
  ('protocol_B_6_to_6', 'RGB_BGREM', 'resnet18')
  ('protocol_B_6_to_6', 'RGB_BGREM', 'efficientnet_b0')
  ('protocol_B_6_to_6', 'RGB_BGREM', 'mobilenet_v3_small')

====================================================================================================
RUNNING | protocol=protocol_B_6_to_4 | frame_source=RGB | model=resnet18
====================================================================================================
train=221, val=24, test=238

Epoch 1/12
   [train] batch 1/10 | loss=2.0588
   [train] batch 10/10 | loss=1.7982
   [val] batch 1/1 | loss=1.9280
Epoch 01 | train_macro_f1=0.1616 | val_macro_f1=0.3117

Epoch 2/12
   [train] batch 1/10 | loss=1.2751
   [train] batch 10/10 | loss=1.4274
   [val] batch 1/1 | loss=1.5740
Epoch 02 | train_macro_f1=0.6775 | val_macro_f1=0.5531

Epoch 3/12
   [train] batch 1/10 | loss=0.7483
   [train] batch 10/10 | loss=0.6840
   [val] batch 1/1 | loss=1.4461
Epoch 03 | train_macro_f1=0.8855 | val_macro_f1=0.5225

Epoch 4/12
   [train] batch 1/10 | loss=0.3393
   [train] batch 10/10 | loss=0.6204
   [val] batch 1/1 | loss=1.4198
Epoch 04 | train_macro_f1=0.9331 | val_macro_f1=0.4916

Epoch 5/12
   [train] batch 1/10 | loss=0.2537
   [train] batch 10/10 | loss=0.2268
   [val] batch 1/1 | loss=1.1390
Epoch 05 | train_macro_f1=0.9635 | val_macro_f1=0.5673

Epoch 6/12
   [train] batch 1/10 | loss=0.1771
   [train] batch 10/10 | loss=0.2009
   [val] batch 1/1 | loss=1.0665
Epoch 06 | train_macro_f1=0.9955 | val_macro_f1=0.5238

Epoch 7/12
   [train] batch 1/10 | loss=0.0899
   [train] batch 10/10 | loss=0.1817
   [val] batch 1/1 | loss=1.1448
Epoch 07 | train_macro_f1=1.0000 | val_macro_f1=0.4643

Epoch 8/12
   [train] batch 1/10 | loss=0.0464
   [train] batch 10/10 | loss=0.1442
   [val] batch 1/1 | loss=1.0749
Epoch 08 | train_macro_f1=1.0000 | val_macro_f1=0.4793

Epoch 9/12
   [train] batch 1/10 | loss=0.0546
   [train] batch 10/10 | loss=0.1686
   [val] batch 1/1 | loss=1.0944
Epoch 09 | train_macro_f1=1.0000 | val_macro_f1=0.4383
Early stopping triggered.

====================================================================================================
RUNNING | protocol=protocol_B_6_to_4 | frame_source=RGB | model=efficientnet_b0
====================================================================================================
train=221, val=24, test=238

Epoch 1/12
   [train] batch 1/14 | loss=1.9295
   [train] batch 11/14 | loss=1.9714
   [train] batch 14/14 | loss=1.9292
   [val] batch 1/2 | loss=1.9069
   [val] batch 2/2 | loss=1.8068
Epoch 01 | train_macro_f1=0.1342 | val_macro_f1=0.0973

Epoch 2/12
   [train] batch 1/14 | loss=1.7316
   [train] batch 11/14 | loss=1.6940
   [train] batch 14/14 | loss=1.7461
   [val] batch 1/2 | loss=1.8725
   [val] batch 2/2 | loss=1.8851
Epoch 02 | train_macro_f1=0.5665 | val_macro_f1=0.1050

Epoch 3/12
   [train] batch 1/14 | loss=1.5458
   [train] batch 11/14 | loss=1.4409
   [train] batch 14/14 | loss=1.4788
   [val] batch 1/2 | loss=1.7718
   [val] batch 2/2 | loss=1.9122
Epoch 03 | train_macro_f1=0.7028 | val_macro_f1=0.1744

Epoch 4/12
   [train] batch 1/14 | loss=1.2596
   [train] batch 11/14 | loss=1.2446
   [train] batch 14/14 | loss=1.1698
   [val] batch 1/2 | loss=1.5992
   [val] batch 2/2 | loss=1.7278
Epoch 04 | train_macro_f1=0.7489 | val_macro_f1=0.2906

Epoch 5/12
   [train] batch 1/14 | loss=1.0107
   [train] batch 11/14 | loss=0.8824
   [train] batch 14/14 | loss=0.9902
   [val] batch 1/2 | loss=1.3477
   [val] batch 2/2 | loss=1.5079
Epoch 05 | train_macro_f1=0.8376 | val_macro_f1=0.3293

Epoch 6/12
   [train] batch 1/14 | loss=0.7300
   [train] batch 11/14 | loss=0.5518
   [train] batch 14/14 | loss=0.6414
   [val] batch 1/2 | loss=1.0333
   [val] batch 2/2 | loss=1.1889
Epoch 06 | train_macro_f1=0.8913 | val_macro_f1=0.6476

Epoch 7/12
   [train] batch 1/14 | loss=0.5638
   [train] batch 11/14 | loss=0.3539
   [train] batch 14/14 | loss=0.5728
   [val] batch 1/2 | loss=0.8925
   [val] batch 2/2 | loss=0.9825
Epoch 07 | train_macro_f1=0.9117 | val_macro_f1=0.6245

Epoch 8/12
   [train] batch 1/14 | loss=0.2926
   [train] batch 11/14 | loss=0.3464
   [train] batch 14/14 | loss=0.2695
   [val] batch 1/2 | loss=0.7160
   [val] batch 2/2 | loss=0.9069
Epoch 08 | train_macro_f1=0.9447 | val_macro_f1=0.7851

Epoch 9/12
   [train] batch 1/14 | loss=0.2693
   [train] batch 11/14 | loss=0.1986
   [train] batch 14/14 | loss=0.1796
   [val] batch 1/2 | loss=0.6483
   [val] batch 2/2 | loss=0.8115
Epoch 09 | train_macro_f1=0.9635 | val_macro_f1=0.7605

Epoch 10/12
   [train] batch 1/14 | loss=0.3377
   [train] batch 11/14 | loss=0.2944
   [train] batch 14/14 | loss=0.4062
   [val] batch 1/2 | loss=0.5895
   [val] batch 2/2 | loss=0.5700
Epoch 10 | train_macro_f1=0.9460 | val_macro_f1=0.7905

Epoch 11/12
   [train] batch 1/14 | loss=0.1237
   [train] batch 11/14 | loss=0.1644
   [train] batch 14/14 | loss=0.0759
   [val] batch 1/2 | loss=0.5549
   [val] batch 2/2 | loss=0.5832
Epoch 11 | train_macro_f1=0.9955 | val_macro_f1=0.6701

Epoch 12/12
   [train] batch 1/14 | loss=0.0975
   [train] batch 11/14 | loss=0.0767
   [train] batch 14/14 | loss=0.0977
   [val] batch 1/2 | loss=0.5001
   [val] batch 2/2 | loss=0.3503
Epoch 12 | train_macro_f1=0.9635 | val_macro_f1=0.8320

====================================================================================================
RUNNING | protocol=protocol_B_6_to_4 | frame_source=RGB | model=mobilenet_v3_small
====================================================================================================
train=221, val=24, test=238

Epoch 1/12
   [train] batch 1/7 | loss=1.9514
   [train] batch 7/7 | loss=1.9472
   [val] batch 1/1 | loss=1.9090
Epoch 01 | train_macro_f1=0.0936 | val_macro_f1=0.2540

Epoch 2/12
   [train] batch 1/7 | loss=1.9048
   [train] batch 7/7 | loss=1.8477
   [val] batch 1/1 | loss=1.9384
Epoch 02 | train_macro_f1=0.2576 | val_macro_f1=0.0748

Epoch 3/12
   [train] batch 1/7 | loss=1.7987
   [train] batch 7/7 | loss=1.7784
   [val] batch 1/1 | loss=1.9666
Epoch 03 | train_macro_f1=0.3875 | val_macro_f1=0.0736

Epoch 4/12
   [train] batch 1/7 | loss=1.6299
   [train] batch 7/7 | loss=1.7220
   [val] batch 1/1 | loss=1.9670
Epoch 04 | train_macro_f1=0.4814 | val_macro_f1=0.0736

Epoch 5/12
   [train] batch 1/7 | loss=1.6404
   [train] batch 7/7 | loss=1.5773
   [val] batch 1/1 | loss=1.9519
Epoch 05 | train_macro_f1=0.5863 | val_macro_f1=0.0736
Early stopping triggered.

====================================================================================================
RUNNING | protocol=protocol_B_4_6_8_to_6 | frame_source=RGB | model=efficientnet_b0
====================================================================================================
train=675, val=74, test=245

Epoch 1/12
   [train] batch 1/43 | loss=1.9568
   [train] batch 11/43 | loss=1.9763
   [train] batch 21/43 | loss=1.9194
   [train] batch 31/43 | loss=1.9362
   [train] batch 41/43 | loss=1.9092
   [train] batch 43/43 | loss=1.7090
   [val] batch 1/5 | loss=1.6961
   [val] batch 5/5 | loss=1.8229
Epoch 01 | train_macro_f1=0.1708 | val_macro_f1=0.2824

Epoch 2/12
   [train] batch 1/43 | loss=1.7134
   [train] batch 11/43 | loss=1.6341
   [train] batch 21/43 | loss=1.5906
   [train] batch 31/43 | loss=1.4255
   [train] batch 41/43 | loss=1.3206
   [train] batch 43/43 | loss=1.4723
   [val] batch 1/5 | loss=1.0850
   [val] batch 5/5 | loss=1.1992
Epoch 02 | train_macro_f1=0.5656 | val_macro_f1=0.6196

Epoch 3/12
   [train] batch 1/43 | loss=1.2743
   [train] batch 11/43 | loss=1.2067
   [train] batch 21/43 | loss=1.0209
   [train] batch 31/43 | loss=0.7905
   [train] batch 41/43 | loss=0.6734
   [train] batch 43/43 | loss=1.7244
   [val] batch 1/5 | loss=0.4427
   [val] batch 5/5 | loss=0.8084
Epoch 03 | train_macro_f1=0.7155 | val_macro_f1=0.7145

Epoch 4/12
   [train] batch 1/43 | loss=0.7058
   [train] batch 11/43 | loss=0.7375
   [train] batch 21/43 | loss=0.7496
   [train] batch 31/43 | loss=0.6074
   [train] batch 41/43 | loss=0.6138
   [train] batch 43/43 | loss=0.6131
   [val] batch 1/5 | loss=0.2433
   [val] batch 5/5 | loss=0.6977
Epoch 04 | train_macro_f1=0.8099 | val_macro_f1=0.7388

Epoch 5/12
   [train] batch 1/43 | loss=0.3879
   [train] batch 11/43 | loss=0.3991
   [train] batch 21/43 | loss=0.4838
   [train] batch 31/43 | loss=0.6302
   [train] batch 41/43 | loss=0.3274
   [train] batch 43/43 | loss=0.3573
   [val] batch 1/5 | loss=0.2786
   [val] batch 5/5 | loss=0.4922
Epoch 05 | train_macro_f1=0.8860 | val_macro_f1=0.7793

Epoch 6/12
   [train] batch 1/43 | loss=0.3273
   [train] batch 11/43 | loss=0.2104
   [train] batch 21/43 | loss=0.1615
   [train] batch 31/43 | loss=0.3712
   [train] batch 41/43 | loss=0.3599
   [train] batch 43/43 | loss=0.2573
   [val] batch 1/5 | loss=0.1774
   [val] batch 5/5 | loss=0.4787
Epoch 06 | train_macro_f1=0.9229 | val_macro_f1=0.8192

Epoch 7/12
   [train] batch 1/43 | loss=0.1935
   [train] batch 11/43 | loss=0.1698
   [train] batch 21/43 | loss=0.2235
   [train] batch 31/43 | loss=0.2870
   [train] batch 41/43 | loss=0.2176
   [train] batch 43/43 | loss=2.2334
   [val] batch 1/5 | loss=0.1421
   [val] batch 5/5 | loss=0.4266
Epoch 07 | train_macro_f1=0.9329 | val_macro_f1=0.8082

Epoch 8/12
   [train] batch 1/43 | loss=0.1303
   [train] batch 11/43 | loss=0.2286
   [train] batch 21/43 | loss=0.1325
   [train] batch 31/43 | loss=0.1150
   [train] batch 41/43 | loss=0.1718
   [train] batch 43/43 | loss=0.2602
   [val] batch 1/5 | loss=0.2636
   [val] batch 5/5 | loss=0.5183
Epoch 08 | train_macro_f1=0.9583 | val_macro_f1=0.7927

Epoch 9/12
   [train] batch 1/43 | loss=0.0963
   [train] batch 11/43 | loss=0.3206
   [train] batch 21/43 | loss=0.3002
   [train] batch 31/43 | loss=0.1118
   [train] batch 41/43 | loss=0.0732
   [train] batch 43/43 | loss=1.1709
   [val] batch 1/5 | loss=0.2688
   [val] batch 5/5 | loss=0.5169
Epoch 09 | train_macro_f1=0.9567 | val_macro_f1=0.7757

Epoch 10/12
   [train] batch 1/43 | loss=0.0638
   [train] batch 11/43 | loss=0.0907
   [train] batch 21/43 | loss=0.1006
   [train] batch 31/43 | loss=0.0443
   [train] batch 41/43 | loss=0.0454
   [train] batch 43/43 | loss=0.2242
   [val] batch 1/5 | loss=0.1146
   [val] batch 5/5 | loss=0.4482
Epoch 10 | train_macro_f1=0.9807 | val_macro_f1=0.7888
Early stopping triggered.

====================================================================================================
RUNNING | protocol=protocol_B_4_6_8_to_6 | frame_source=RGB | model=mobilenet_v3_small
====================================================================================================
train=675, val=74, test=245

Epoch 1/12
   [train] batch 1/22 | loss=1.9774
   [train] batch 11/22 | loss=1.9243
   [train] batch 21/22 | loss=1.9007
   [train] batch 22/22 | loss=1.9176
   [val] batch 1/3 | loss=1.9168
   [val] batch 3/3 | loss=1.7204
Epoch 01 | train_macro_f1=0.1640 | val_macro_f1=0.1957

Epoch 2/12
   [train] batch 1/22 | loss=1.8514
   [train] batch 11/22 | loss=1.7558
   [train] batch 21/22 | loss=1.7626
   [train] batch 22/22 | loss=1.8529
   [val] batch 1/3 | loss=1.7515
   [val] batch 3/3 | loss=1.6933
Epoch 02 | train_macro_f1=0.3191 | val_macro_f1=0.1922

Epoch 3/12
   [train] batch 1/22 | loss=1.6459
   [train] batch 11/22 | loss=1.6843
   [train] batch 21/22 | loss=1.7074
   [train] batch 22/22 | loss=2.0973
   [val] batch 1/3 | loss=1.5739
   [val] batch 3/3 | loss=1.6364
Epoch 03 | train_macro_f1=0.3987 | val_macro_f1=0.2607

Epoch 4/12
   [train] batch 1/22 | loss=1.5839
   [train] batch 11/22 | loss=1.4876
   [train] batch 21/22 | loss=1.2804
   [train] batch 22/22 | loss=1.4922
   [val] batch 1/3 | loss=1.4204
   [val] batch 3/3 | loss=1.5496
Epoch 04 | train_macro_f1=0.5028 | val_macro_f1=0.2395

Epoch 5/12
   [train] batch 1/22 | loss=1.3661
   [train] batch 11/22 | loss=1.2342
   [train] batch 21/22 | loss=1.3641
   [train] batch 22/22 | loss=1.4478
   [val] batch 1/3 | loss=1.2962
   [val] batch 3/3 | loss=1.4312
Epoch 05 | train_macro_f1=0.5596 | val_macro_f1=0.3825

Epoch 6/12
   [train] batch 1/22 | loss=1.2056
   [train] batch 11/22 | loss=1.2259
   [train] batch 21/22 | loss=0.9576
   [train] batch 22/22 | loss=1.7142
   [val] batch 1/3 | loss=1.1452
   [val] batch 3/3 | loss=1.2979
Epoch 06 | train_macro_f1=0.6496 | val_macro_f1=0.4553

Epoch 7/12
   [train] batch 1/22 | loss=0.9395
   [train] batch 11/22 | loss=1.1087
   [train] batch 21/22 | loss=1.1160
   [train] batch 22/22 | loss=0.9338
   [val] batch 1/3 | loss=0.9739
   [val] batch 3/3 | loss=1.1480
Epoch 07 | train_macro_f1=0.7502 | val_macro_f1=0.5426

Epoch 8/12
   [train] batch 1/22 | loss=0.7903
   [train] batch 11/22 | loss=0.8013
   [train] batch 21/22 | loss=0.6640
   [train] batch 22/22 | loss=1.1064
   [val] batch 1/3 | loss=0.9314
   [val] batch 3/3 | loss=1.0415
Epoch 08 | train_macro_f1=0.7956 | val_macro_f1=0.4814

Epoch 9/12
   [train] batch 1/22 | loss=0.5619
   [train] batch 11/22 | loss=0.6760
   [train] batch 21/22 | loss=0.5864
   [train] batch 22/22 | loss=1.2565
   [val] batch 1/3 | loss=0.8295
   [val] batch 3/3 | loss=0.9661
Epoch 09 | train_macro_f1=0.8169 | val_macro_f1=0.5627

Epoch 10/12
   [train] batch 1/22 | loss=0.4731
   [train] batch 11/22 | loss=0.5453
   [train] batch 21/22 | loss=0.4323
   [train] batch 22/22 | loss=0.9443
   [val] batch 1/3 | loss=0.7377
   [val] batch 3/3 | loss=0.9607
Epoch 10 | train_macro_f1=0.8772 | val_macro_f1=0.5530

Epoch 11/12
   [train] batch 1/22 | loss=0.5592
   [train] batch 11/22 | loss=0.3578
   [train] batch 21/22 | loss=0.3437
   [train] batch 22/22 | loss=0.8439
   [val] batch 1/3 | loss=0.7177
   [val] batch 3/3 | loss=0.9157
Epoch 11 | train_macro_f1=0.8741 | val_macro_f1=0.5768

Epoch 12/12
   [train] batch 1/22 | loss=0.2413
   [train] batch 11/22 | loss=0.3064
   [train] batch 21/22 | loss=0.3529
   [train] batch 22/22 | loss=0.7298
   [val] batch 1/3 | loss=0.7290
   [val] batch 3/3 | loss=0.8734
Epoch 12 | train_macro_f1=0.9040 | val_macro_f1=0.6002

====================================================================================================
RUNNING | protocol=protocol_B_4_6_8_to_8 | frame_source=RGB | model=resnet18
====================================================================================================
train=675, val=74, test=266

Epoch 1/12
   [train] batch 1/29 | loss=2.1862
   [train] batch 11/29 | loss=2.1256
   [train] batch 21/29 | loss=1.4773
   [train] batch 29/29 | loss=1.5885
   [val] batch 1/4 | loss=0.9595
   [val] batch 4/4 | loss=1.4004
Epoch 01 | train_macro_f1=0.2921 | val_macro_f1=0.5008

Epoch 2/12
   [train] batch 1/29 | loss=1.0502
   [train] batch 11/29 | loss=0.9082
   [train] batch 21/29 | loss=0.6154
   [train] batch 29/29 | loss=0.8468
   [val] batch 1/4 | loss=0.4425
   [val] batch 4/4 | loss=1.0569
Epoch 02 | train_macro_f1=0.7700 | val_macro_f1=0.7179

Epoch 3/12
   [train] batch 1/29 | loss=0.4289
   [train] batch 11/29 | loss=0.4092
   [train] batch 21/29 | loss=0.4491
   [train] batch 29/29 | loss=0.5471
   [val] batch 1/4 | loss=0.4237
   [val] batch 4/4 | loss=0.8730
Epoch 03 | train_macro_f1=0.8820 | val_macro_f1=0.7908

Epoch 4/12
   [train] batch 1/29 | loss=0.2622
   [train] batch 11/29 | loss=0.2804
   [train] batch 21/29 | loss=0.3422
   [train] batch 29/29 | loss=0.5329
   [val] batch 1/4 | loss=0.3096
   [val] batch 4/4 | loss=0.6582
Epoch 04 | train_macro_f1=0.9334 | val_macro_f1=0.7738

Epoch 5/12
   [train] batch 1/29 | loss=0.2296
   [train] batch 11/29 | loss=0.4059
   [train] batch 21/29 | loss=0.1432
   [train] batch 29/29 | loss=1.0859
   [val] batch 1/4 | loss=0.4181
   [val] batch 4/4 | loss=0.9009
Epoch 05 | train_macro_f1=0.9553 | val_macro_f1=0.7326

Epoch 6/12
   [train] batch 1/29 | loss=0.1200
   [train] batch 11/29 | loss=0.0667
   [train] batch 21/29 | loss=0.1261
   [train] batch 29/29 | loss=0.2631
   [val] batch 1/4 | loss=0.3029
   [val] batch 4/4 | loss=0.7649
Epoch 06 | train_macro_f1=0.9760 | val_macro_f1=0.7409

Epoch 7/12
   [train] batch 1/29 | loss=0.0731
   [train] batch 11/29 | loss=0.0444
   [train] batch 21/29 | loss=0.0598
   [train] batch 29/29 | loss=0.6780
   [val] batch 1/4 | loss=0.3095
   [val] batch 4/4 | loss=0.4952
Epoch 07 | train_macro_f1=0.9820 | val_macro_f1=0.7834
Early stopping triggered.

====================================================================================================
RUNNING | protocol=protocol_B_4_6_8_to_8 | frame_source=RGB | model=efficientnet_b0
====================================================================================================
train=675, val=74, test=266

Epoch 1/12
   [train] batch 1/43 | loss=1.9460
   [train] batch 11/43 | loss=1.9442
   [train] batch 21/43 | loss=1.9871
   [train] batch 31/43 | loss=1.9291
   [train] batch 41/43 | loss=1.9028
   [train] batch 43/43 | loss=1.8841
   [val] batch 1/5 | loss=1.7636
   [val] batch 5/5 | loss=1.7767
Epoch 01 | train_macro_f1=0.1574 | val_macro_f1=0.2959

Epoch 2/12
   [train] batch 1/43 | loss=1.6559
   [train] batch 11/43 | loss=1.7647
   [train] batch 21/43 | loss=1.5669
   [train] batch 31/43 | loss=1.6035
   [train] batch 41/43 | loss=1.4471
   [train] batch 43/43 | loss=1.8604
   [val] batch 1/5 | loss=1.2534
   [val] batch 5/5 | loss=1.3351
Epoch 02 | train_macro_f1=0.5169 | val_macro_f1=0.4648

Epoch 3/12
   [train] batch 1/43 | loss=1.2724
   [train] batch 11/43 | loss=1.3861
   [train] batch 21/43 | loss=1.4153
   [train] batch 31/43 | loss=1.0017
   [train] batch 41/43 | loss=0.6972
   [train] batch 43/43 | loss=2.1169
   [val] batch 1/5 | loss=0.5530
   [val] batch 5/5 | loss=0.9462
Epoch 03 | train_macro_f1=0.6924 | val_macro_f1=0.7015

Epoch 4/12
   [train] batch 1/43 | loss=0.9455
   [train] batch 11/43 | loss=0.5276
   [train] batch 21/43 | loss=0.5859
   [train] batch 31/43 | loss=0.6681
   [train] batch 41/43 | loss=0.8664
   [train] batch 43/43 | loss=1.0088
   [val] batch 1/5 | loss=0.4078
   [val] batch 5/5 | loss=0.6563
Epoch 04 | train_macro_f1=0.7876 | val_macro_f1=0.7881

Epoch 5/12
   [train] batch 1/43 | loss=0.4644
   [train] batch 11/43 | loss=0.5197
   [train] batch 21/43 | loss=0.4385
   [train] batch 31/43 | loss=0.7424
   [train] batch 41/43 | loss=0.6359
   [train] batch 43/43 | loss=1.2837
   [val] batch 1/5 | loss=0.2865
   [val] batch 5/5 | loss=0.4868
Epoch 05 | train_macro_f1=0.8642 | val_macro_f1=0.8227

Epoch 6/12
   [train] batch 1/43 | loss=0.3473
   [train] batch 11/43 | loss=0.3308
   [train] batch 21/43 | loss=0.2942
   [train] batch 31/43 | loss=0.5349
   [train] batch 41/43 | loss=0.4418
   [train] batch 43/43 | loss=0.4052
   [val] batch 1/5 | loss=0.2672
   [val] batch 5/5 | loss=0.6933
Epoch 06 | train_macro_f1=0.8858 | val_macro_f1=0.7681

Epoch 7/12
   [train] batch 1/43 | loss=0.2003
   [train] batch 11/43 | loss=0.1857

In [ ]:
# ============================================================
# 05_stage5_vit_convnext_all_protocols.ipynb
# ViT-B/16 + ConvNeXt-Tiny on all protocols
# Resumable, GPU-optimized, stage-5 style runner
# ============================================================

import os
import gc
import json
import time
import copy
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision.models import (
    vit_b_16, ViT_B_16_Weights,
    convnext_tiny, ConvNeXt_Tiny_Weights,
)

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_colwidth", 300)

# ============================================================
# 1. SETTINGS
# ============================================================
SEED = 42

IMG_SIZE = 224
NUM_SAMPLE_FRAMES = 32

# ViT is heavier; ConvNeXt-Tiny is lighter but still sizable
BATCH_SIZE_BY_MODEL = {
    "vit_b_16": 8,
    "convnext_tiny": 12,
}

EPOCHS = 12
LR = 1e-4
WEIGHT_DECAY = 1e-4
PATIENCE = 4

USE_AMP = True
USE_PRETRAINED = True
USE_TORCH_COMPILE = True

# If dataloader is unstable in notebook, set NUM_WORKERS=0
NUM_WORKERS = 4
PIN_MEMORY = True
PERSISTENT_WORKERS = True
PREFETCH_FACTOR = 4

SAMPLE_START_FRAC = 0.10
SAMPLE_END_FRAC = 0.90

SKIP_IF_METRICS_EXISTS = True

# Choose one or both
FRAME_SOURCES = [
    "RGB",
    "RGB_BGREM",
]

MODELS_TO_RUN = [
    "vit_b_16",
    "convnext_tiny",
]

SPLIT_CONFIGS = [
    ("protocol_A", "protocol_A_train.csv", "protocol_A_val.csv", "protocol_A_test.csv"),

    ("protocol_B_4_to_4", "protocol_B_train_4_test_4.csv", None, "protocol_B_test_4_same.csv"),
    ("protocol_B_4_to_6", "protocol_B_train_4_test_6.csv", None, "protocol_B_test_6.csv"),
    ("protocol_B_4_to_8", "protocol_B_train_4_test_8.csv", None, "protocol_B_test_8.csv"),

    ("protocol_B_6_to_4", "protocol_B_train_6_test_4.csv", None, "protocol_B_test_4.csv"),
    ("protocol_B_6_to_6", "protocol_B_train_6_test_6.csv", None, "protocol_B_test_6_same.csv"),
    ("protocol_B_6_to_8", "protocol_B_train_6_test_8.csv", None, "protocol_B_test_8.csv"),

    ("protocol_B_8_to_4", "protocol_B_train_8_test_4.csv", None, "protocol_B_test_4.csv"),
    ("protocol_B_8_to_6", "protocol_B_train_8_test_6.csv", None, "protocol_B_test_6.csv"),
    ("protocol_B_8_to_8", "protocol_B_train_8_test_8.csv", None, "protocol_B_test_8_same.csv"),

    ("protocol_B_4_6_to_4", "protocol_B_train_4_6_test_4.csv", None, "protocol_B_test_4_from_4_6.csv"),
    ("protocol_B_4_6_to_6", "protocol_B_train_4_6_test_6.csv", None, "protocol_B_test_6_from_4_6.csv"),
    ("protocol_B_4_6_to_8", "protocol_B_train_4_6_test_8.csv", None, "protocol_B_test_8_from_4_6.csv"),

    ("protocol_B_4_8_to_4", "protocol_B_train_4_8_test_4.csv", None, "protocol_B_test_4_from_4_8.csv"),
    ("protocol_B_4_8_to_6", "protocol_B_train_4_8_test_6.csv", None, "protocol_B_test_6_from_4_8.csv"),
    ("protocol_B_4_8_to_8", "protocol_B_train_4_8_test_8.csv", None, "protocol_B_test_8_from_4_8.csv"),

    ("protocol_B_6_8_to_4", "protocol_B_train_6_8_test_4.csv", None, "protocol_B_test_4_from_6_8.csv"),
    ("protocol_B_6_8_to_6", "protocol_B_train_6_8_test_6.csv", None, "protocol_B_test_6_from_6_8.csv"),
    ("protocol_B_6_8_to_8", "protocol_B_train_6_8_test_8.csv", None, "protocol_B_test_8_from_6_8.csv"),

    ("protocol_B_4_6_8_to_4", "protocol_B_train_4_6_8_test_4.csv", None, "protocol_B_test_4_from_4_6_8.csv"),
    ("protocol_B_4_6_8_to_6", "protocol_B_train_4_6_8_test_6.csv", None, "protocol_B_test_6_from_4_6_8.csv"),
    ("protocol_B_4_6_8_to_8", "protocol_B_train_4_6_8_test_8.csv", None, "protocol_B_test_8_from_4_6_8.csv"),
]

CLASS_NAMES = [
    "doctor",
    "emergency",
    "fire",
    "help",
    "robbery",
    "sit_down",
    "stand_up",
]
label2id = {c: i for i, c in enumerate(CLASS_NAMES)}
id2label = {i: c for c, i in label2id.items()}
NUM_CLASSES = len(CLASS_NAMES)

# ============================================================
# 2. REPRODUCIBILITY
# ============================================================
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(SEED)

# ============================================================
# 3. PATHS
# ============================================================
cwd = Path.cwd()
ROOT = cwd.parent if cwd.name == "notebooks" else cwd

SPLIT_DIR = ROOT / "data" / "processed" / "splits"
MANIFEST_DIR = ROOT / "data" / "processed" / "manifests"
FRAME_SUMMARY_CSV = MANIFEST_DIR / "frame_extraction_trimmed_summary.csv"

RESULTS_ROOT = ROOT / "results" / "stage5_vit_convnext"
CHECKPOINT_ROOT = ROOT / "checkpoints" / "stage5_vit_convnext"
LOG_ROOT = ROOT / "logs" / "stage5_vit_convnext"

RESULTS_ROOT.mkdir(parents=True, exist_ok=True)
CHECKPOINT_ROOT.mkdir(parents=True, exist_ok=True)
LOG_ROOT.mkdir(parents=True, exist_ok=True)

print("ROOT:", ROOT)
print("RESULTS_ROOT:", RESULTS_ROOT)

if not FRAME_SUMMARY_CSV.exists():
    raise FileNotFoundError(f"Missing frame summary: {FRAME_SUMMARY_CSV}")

# ============================================================
# 4. DEVICE
# ============================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))

torch.backends.cudnn.benchmark = True
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
try:
    torch.set_float32_matmul_precision("high")
except Exception:
    pass

# ============================================================
# 5. LOAD FRAME SUMMARY
# ============================================================
frame_df_all = pd.read_csv(FRAME_SUMMARY_CSV)
frame_df_all = frame_df_all[frame_df_all["status"] == "success"].copy()
frame_df_all = frame_df_all[["pair_id", "modality", "output_dir", "frames_extracted"]].drop_duplicates()

# ============================================================
# 6. HELPERS
# ============================================================
def sample_indices_middle_region(n_total, n_samples, start_frac=0.10, end_frac=0.90):
    if n_total <= 0:
        return [0] * n_samples

    start_idx = int(round(start_frac * (n_total - 1)))
    end_idx = int(round(end_frac * (n_total - 1)))

    start_idx = max(0, min(start_idx, n_total - 1))
    end_idx = max(start_idx, min(end_idx, n_total - 1))

    idxs = np.linspace(start_idx, end_idx, n_samples)
    idxs = np.round(idxs).astype(int)
    return np.clip(idxs, 0, n_total - 1).tolist()

def frame_index_to_path(frame_dir, idx):
    return Path(frame_dir) / f"frame_{idx+1:06d}.jpg"

def load_split_df(csv_name):
    csv_path = SPLIT_DIR / csv_name
    if not csv_path.exists():
        raise FileNotFoundError(f"Missing split file: {csv_path}")
    df = pd.read_csv(csv_path)
    if "is_valid_pair" in df.columns:
        df = df[df["is_valid_pair"] == True].copy()
    return df.reset_index(drop=True)

def attach_labels(df_):
    out = df_.copy()
    out = out[out["gesture"].isin(CLASS_NAMES)].copy()
    out["label"] = out["gesture"].map(label2id)
    return out.reset_index(drop=True)

def attach_frame_info(df_, frame_source):
    sub = frame_df_all[frame_df_all["modality"] == frame_source].copy()
    sub = sub.rename(columns={
        "output_dir": "frame_dir",
        "frames_extracted": "num_frames_available"
    })
    sub = sub[["pair_id", "frame_dir", "num_frames_available"]].drop_duplicates()

    out = df_.merge(sub, on="pair_id", how="left")
    out = out[out["num_frames_available"].fillna(0) > 0].copy().reset_index(drop=True)
    out["num_frames_available"] = out["num_frames_available"].astype(int)
    return out

# ============================================================
# 7. TRANSFORMS
# ============================================================
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    ),
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    ),
])

# ============================================================
# 8. DATASET
# ============================================================
class FrameVotingDataset(Dataset):
    def __init__(self, df, transform, num_sample_frames=32):
        self.df = df.reset_index(drop=True).copy()
        self.transform = transform
        self.sampled_paths = []

        print(f"Building sampled frame paths for {len(self.df)} samples...")
        for _, row in self.df.iterrows():
            idxs = sample_indices_middle_region(
                int(row["num_frames_available"]),
                num_sample_frames,
                SAMPLE_START_FRAC,
                SAMPLE_END_FRAC
            )
            self.sampled_paths.append([frame_index_to_path(row["frame_dir"], i) for i in idxs])

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        paths = self.sampled_paths[idx]

        frames = []
        for p in paths:
            try:
                with Image.open(p) as f:
                    img = f.convert("RGB")
            except Exception:
                img = Image.fromarray(np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8))
            frames.append(self.transform(img))

        frames = torch.stack(frames, dim=0)
        label = int(row["label"])

        meta = {
            "pair_id": row["pair_id"],
            "subject_id": row["subject_id"],
            "distance": row["distance"],
            "gesture": row["gesture"],
            "frame_dir": row["frame_dir"],
        }
        return frames, label, meta

def collate_fn(batch):
    frames = torch.stack([x[0] for x in batch], dim=0)
    labels = torch.tensor([x[1] for x in batch], dtype=torch.long)
    metas = [x[2] for x in batch]
    return frames, labels, metas

def make_loader(dataset, batch_size, shuffle):
    kwargs = dict(
        dataset=dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY and device.type == "cuda",
        collate_fn=collate_fn,
    )
    if NUM_WORKERS > 0:
        kwargs["persistent_workers"] = PERSISTENT_WORKERS
        kwargs["prefetch_factor"] = PREFETCH_FACTOR
    return DataLoader(**kwargs)

# ============================================================
# 9. MODEL FACTORY
# ============================================================
def create_model(model_name, num_classes, use_pretrained=True):
    if model_name == "vit_b_16":
        model = vit_b_16(weights=ViT_B_16_Weights.DEFAULT if use_pretrained else None)
        model.heads.head = nn.Linear(model.heads.head.in_features, num_classes)

    elif model_name == "convnext_tiny":
        model = convnext_tiny(weights=ConvNeXt_Tiny_Weights.DEFAULT if use_pretrained else None)
        model.classifier[2] = nn.Linear(model.classifier[2].in_features, num_classes)

    else:
        raise ValueError(f"Unsupported model: {model_name}")

    model = model.to(device)
    model = model.to(memory_format=torch.channels_last)

    if USE_TORCH_COMPILE and hasattr(torch, "compile"):
        try:
            model = torch.compile(model, mode="reduce-overhead")
        except Exception:
            pass

    return model

def forward_video_voting(model, frames):
    B, T, C, H, W = frames.shape
    frames = frames.view(B * T, C, H, W).contiguous(memory_format=torch.channels_last)
    frame_logits = model(frames)
    frame_logits = frame_logits.view(B, T, -1)
    video_logits = frame_logits.mean(dim=1)
    return video_logits

# ============================================================
# 10. TRAIN / EVAL
# ============================================================
def run_one_epoch(model, loader, criterion, optimizer=None, scaler=None, train=True):
    model.train() if train else model.eval()

    total_loss = 0.0
    all_labels = []
    all_preds = []

    total_batches = len(loader)

    for batch_idx, (frames, labels, metas) in enumerate(loader):
        frames = frames.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        if train:
            optimizer.zero_grad(set_to_none=True)

        with torch.set_grad_enabled(train):
            with torch.autocast(
                device_type="cuda",
                dtype=torch.float16,
                enabled=(USE_AMP and device.type == "cuda")
            ):
                video_logits = forward_video_voting(model, frames)
                loss = criterion(video_logits, labels)

            if train:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()

        preds = video_logits.argmax(dim=1)

        total_loss += loss.item() * labels.size(0)
        all_labels.extend(labels.detach().cpu().numpy().tolist())
        all_preds.extend(preds.detach().cpu().numpy().tolist())

        if batch_idx % 10 == 0 or batch_idx == total_batches - 1:
            mode = "train" if train else "val"
            print(f"   [{mode}] batch {batch_idx+1}/{total_batches} | loss={loss.item():.4f}")

    return {
        "loss": total_loss / len(loader.dataset),
        "accuracy": accuracy_score(all_labels, all_preds),
        "macro_f1": f1_score(all_labels, all_preds, average="macro"),
        "weighted_f1": f1_score(all_labels, all_preds, average="weighted"),
    }

@torch.no_grad()
def predict_with_metadata(model, loader):
    model.eval()

    all_labels = []
    all_preds = []
    rows = []

    start_time = time.time()
    total_samples = 0

    for frames, labels, metas in loader:
        frames = frames.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        with torch.autocast(
            device_type="cuda",
            dtype=torch.float16,
            enabled=(USE_AMP and device.type == "cuda")
        ):
            video_logits = forward_video_voting(model, frames)
            probs = torch.softmax(video_logits, dim=1)
            preds = probs.argmax(dim=1)

        probs_np = probs.detach().cpu().numpy()
        preds_np = preds.detach().cpu().numpy()
        labels_np = labels.detach().cpu().numpy()

        total_samples += len(labels_np)
        all_labels.extend(labels_np.tolist())
        all_preds.extend(preds_np.tolist())

        for i, meta in enumerate(metas):
            row = {
                "pair_id": meta["pair_id"],
                "subject_id": meta["subject_id"],
                "distance": meta["distance"],
                "gesture_true": id2label[int(labels_np[i])],
                "gesture_pred": id2label[int(preds_np[i])],
                "frame_dir": meta["frame_dir"],
            }
            for c_idx, c_name in id2label.items():
                row[f"prob_{c_name}"] = float(probs_np[i][c_idx])
            rows.append(row)

    elapsed = time.time() - start_time
    videos_per_sec = total_samples / elapsed if elapsed > 0 else None
    return all_labels, all_preds, pd.DataFrame(rows), elapsed, videos_per_sec

# ============================================================
# 11. RUN ONE EXPERIMENT
# ============================================================
def run_experiment(protocol_name, train_csv_name, val_csv_name, test_csv_name, frame_source, model_name):
    print("\n" + "=" * 100)
    print(f"RUNNING | protocol={protocol_name} | frame_source={frame_source} | model={model_name}")
    print("=" * 100)

    train_df = load_split_df(train_csv_name)
    test_df = load_split_df(test_csv_name)

    if val_csv_name is None:
        train_df = train_df.sample(frac=1.0, random_state=SEED).reset_index(drop=True)
        n_val = max(1, int(0.10 * len(train_df)))
        val_df = train_df.iloc[:n_val].copy().reset_index(drop=True)
        train_df = train_df.iloc[n_val:].copy().reset_index(drop=True)
    else:
        val_df = load_split_df(val_csv_name)

    train_df = attach_labels(train_df)
    val_df = attach_labels(val_df)
    test_df = attach_labels(test_df)

    train_df = attach_frame_info(train_df, frame_source)
    val_df = attach_frame_info(val_df, frame_source)
    test_df = attach_frame_info(test_df, frame_source)

    print(f"train={len(train_df)}, val={len(val_df)}, test={len(test_df)}")

    batch_size = BATCH_SIZE_BY_MODEL[model_name]

    train_loader = make_loader(
        FrameVotingDataset(train_df, train_transform, NUM_SAMPLE_FRAMES),
        batch_size=batch_size,
        shuffle=True
    )
    val_loader = make_loader(
        FrameVotingDataset(val_df, eval_transform, NUM_SAMPLE_FRAMES),
        batch_size=batch_size,
        shuffle=False
    )
    test_loader = make_loader(
        FrameVotingDataset(test_df, eval_transform, NUM_SAMPLE_FRAMES),
        batch_size=batch_size,
        shuffle=False
    )

    run_name = f"{protocol_name}__{frame_source.lower()}__{model_name}__f{NUM_SAMPLE_FRAMES}__img{IMG_SIZE}"
    results_dir = RESULTS_ROOT / run_name
    checkpoint_dir = CHECKPOINT_ROOT / run_name
    log_dir = LOG_ROOT / run_name

    results_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)

    metrics_json = results_dir / "metrics.json"
    if SKIP_IF_METRICS_EXISTS and metrics_json.exists():
        print("Skipping, already finished:", run_name)
        with open(metrics_json, "r") as f:
            return json.load(f)

    model = create_model(model_name, NUM_CLASSES, use_pretrained=USE_PRETRAINED)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    scaler = torch.amp.GradScaler("cuda", enabled=(USE_AMP and device.type == "cuda"))

    best_val_f1 = -1.0
    best_epoch = -1
    epochs_without_improvement = 0
    history = []

    best_ckpt_path = checkpoint_dir / "best_model.pt"
    best_state_dict = None

    train_start = time.time()

    for epoch in range(1, EPOCHS + 1):
        print(f"\nEpoch {epoch}/{EPOCHS}")

        train_metrics = run_one_epoch(model, train_loader, criterion, optimizer, scaler, train=True)
        val_metrics = run_one_epoch(model, val_loader, criterion, optimizer=None, scaler=scaler, train=False)

        history.append({
            "epoch": epoch,
            "train_loss": train_metrics["loss"],
            "train_acc": train_metrics["accuracy"],
            "train_macro_f1": train_metrics["macro_f1"],
            "train_weighted_f1": train_metrics["weighted_f1"],
            "val_loss": val_metrics["loss"],
            "val_acc": val_metrics["accuracy"],
            "val_macro_f1": val_metrics["macro_f1"],
            "val_weighted_f1": val_metrics["weighted_f1"],
        })

        print(
            f"Epoch {epoch:02d} | "
            f"train_macro_f1={train_metrics['macro_f1']:.4f} | "
            f"val_macro_f1={val_metrics['macro_f1']:.4f}"
        )

        if val_metrics["macro_f1"] > best_val_f1:
            best_val_f1 = val_metrics["macro_f1"]
            best_epoch = epoch
            epochs_without_improvement = 0
            best_state_dict = copy.deepcopy(model.state_dict())
            torch.save({
                "epoch": epoch,
                "model_state_dict": best_state_dict,
                "model_name": model_name,
                "frame_source": frame_source,
                "protocol_name": protocol_name,
                "label2id": label2id,
                "id2label": id2label,
            }, best_ckpt_path)
        else:
            epochs_without_improvement += 1

        if epochs_without_improvement >= PATIENCE:
            print("Early stopping triggered.")
            break

    train_elapsed = time.time() - train_start
    pd.DataFrame(history).to_csv(log_dir / "training_log.csv", index=False)

    if best_state_dict is None:
        raise RuntimeError("No best model was saved.")

    model.load_state_dict(best_state_dict)

    test_labels, test_preds, pred_df, infer_elapsed, videos_per_sec = predict_with_metadata(model, test_loader)

    test_acc = accuracy_score(test_labels, test_preds)
    test_macro_f1 = f1_score(test_labels, test_preds, average="macro")
    test_weighted_f1 = f1_score(test_labels, test_preds, average="weighted")

    cm = confusion_matrix(test_labels, test_preds)
    report_dict = classification_report(
        test_labels,
        test_preds,
        target_names=[id2label[i] for i in range(NUM_CLASSES)],
        output_dict=True,
        zero_division=0
    )
    report_df = pd.DataFrame(report_dict).transpose()

    pred_csv = results_dir / "test_predictions.csv"
    report_csv = results_dir / "classification_report.csv"
    cm_png = results_dir / "confusion_matrix.png"

    pred_df.to_csv(pred_csv, index=False)
    report_df.to_csv(report_csv)

    plt.figure(figsize=(8, 6))
    plt.imshow(cm, interpolation="nearest")
    plt.title(f"{protocol_name} | {frame_source} | {model_name}")
    plt.colorbar()
    ticks = np.arange(NUM_CLASSES)
    plt.xticks(ticks, [id2label[i] for i in range(NUM_CLASSES)], rotation=45, ha="right")
    plt.yticks(ticks, [id2label[i] for i in range(NUM_CLASSES)])
    plt.xlabel("Predicted")
    plt.ylabel("True")
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, str(cm[i, j]), ha="center", va="center")
    plt.tight_layout()
    plt.savefig(cm_png, dpi=200, bbox_inches="tight")
    plt.close()

    per_class_f1 = {}
    for cls in CLASS_NAMES:
        if cls in report_df.index:
            per_class_f1[cls] = float(report_df.loc[cls, "f1-score"])

    metrics = {
        "protocol_name": protocol_name,
        "frame_source": frame_source,
        "model_name": model_name,
        "num_sample_frames": NUM_SAMPLE_FRAMES,
        "batch_size": batch_size,
        "best_epoch": int(best_epoch),
        "best_val_macro_f1": float(best_val_f1),
        "test_accuracy": float(test_acc),
        "test_macro_f1": float(test_macro_f1),
        "test_weighted_f1": float(test_weighted_f1),
        "per_class_f1": per_class_f1,
        "train_time_minutes": float(train_elapsed / 60.0),
        "inference_time_seconds": float(infer_elapsed),
        "videos_per_second": float(videos_per_sec) if videos_per_sec is not None else None,
        "train_rows": int(len(train_df)),
        "val_rows": int(len(val_df)),
        "test_rows": int(len(test_df)),
        "predictions_csv": str(pred_csv),
        "classification_report_csv": str(report_csv),
        "confusion_matrix_png": str(cm_png),
        "checkpoint_best": str(best_ckpt_path),
    }

    with open(metrics_json, "w") as f:
        json.dump(metrics, f, indent=4)

    print(json.dumps(metrics, indent=2))

    del model, train_loader, val_loader, test_loader, best_state_dict
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return metrics

# ============================================================
# 12. RUN ALL EXPERIMENTS
# ============================================================
summary_csv = RESULTS_ROOT / "stage5_vit_convnext_summary.csv"

all_metrics = []
if summary_csv.exists():
    try:
        prev = pd.read_csv(summary_csv)
        all_metrics = prev.to_dict(orient="records")
    except Exception:
        all_metrics = []

done_keys = set()
for m in all_metrics:
    done_keys.add((m["protocol_name"], m["frame_source"], m["model_name"]))

for frame_source in FRAME_SOURCES:
    for protocol_name, train_csv_name, val_csv_name, test_csv_name in SPLIT_CONFIGS:
        for model_name in MODELS_TO_RUN:
            key = (protocol_name, frame_source, model_name)
            if SKIP_IF_METRICS_EXISTS and key in done_keys:
                print("Already in summary, skipping:", key)
                continue

            metrics = run_experiment(
                protocol_name=protocol_name,
                train_csv_name=train_csv_name,
                val_csv_name=val_csv_name,
                test_csv_name=test_csv_name,
                frame_source=frame_source,
                model_name=model_name
            )
            all_metrics.append(metrics)
            done_keys.add(key)
            pd.DataFrame(all_metrics).to_csv(summary_csv, index=False)

final_df = pd.DataFrame(all_metrics)
final_df.to_csv(summary_csv, index=False)

print("\nDONE.")
print("Saved summary to:", summary_csv)
display(
    final_df[[
        "protocol_name",
        "frame_source",
        "model_name",
        "best_val_macro_f1",
        "test_accuracy",
        "test_macro_f1",
        "test_weighted_f1",
        "train_time_minutes",
        "videos_per_second"
    ]].sort_values(["protocol_name", "frame_source", "test_macro_f1"], ascending=[True, True, False])
)

ROOT: /data/Sajjan_Singh/gesture_recognition
RESULTS_ROOT: /data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext
Using device: cuda
GPU name: NVIDIA H100 NVL

====================================================================================================
RUNNING | protocol=protocol_A | frame_source=RGB | model=vit_b_16
====================================================================================================
train=525, val=77, test=147
Building sampled frame paths for 525 samples...
Building sampled frame paths for 77 samples...
Building sampled frame paths for 147 samples...

Downloading: "https://download.pytorch.org/models/vit_b_16-c867db91.pth" to /home/sajjan/.cache/torch/hub/checkpoints/vit_b_16-c867db91.pth
100%|██████████| 330M/330M [00:04<00:00, 71.9MB/s]

Epoch 1/12
   [train] batch 1/66 | loss=2.0963
   [train] batch 11/66 | loss=1.7531
   [train] batch 21/66 | loss=1.9482
   [train] batch 31/66 | loss=1.9636
   [train] batch 41/66 | loss=2.0305
   [train] batch 51/66 | loss=1.9194
   [train] batch 61/66 | loss=1.9231
   [train] batch 66/66 | loss=1.9672
   [val] batch 1/10 | loss=1.9976
   [val] batch 10/10 | loss=1.9668
Epoch 01 | train_macro_f1=0.1112 | val_macro_f1=0.0357

Epoch 2/12
   [train] batch 1/66 | loss=1.9410
   [train] batch 11/66 | loss=2.1089
   [train] batch 21/66 | loss=1.9756
   [train] batch 31/66 | loss=2.0322
   [train] batch 41/66 | loss=1.9750
   [train] batch 51/66 | loss=1.9243
   [train] batch 61/66 | loss=1.9894
   [train] batch 66/66 | loss=1.8707
   [val] batch 1/10 | loss=1.8944
   [val] batch 10/10 | loss=1.8609
Epoch 02 | train_macro_f1=0.1237 | val_macro_f1=0.0357

Epoch 3/12
   [train] batch 1/66 | loss=1.9161
   [train] batch 11/66 | loss=1.8944
   [train] batch 21/66 | loss=1.9506
   [train] batch 31/66 | loss=1.8669
   [train] batch 41/66 | loss=1.9980
   [train] batch 51/66 | loss=2.0094
   [train] batch 61/66 | loss=2.0393
   [train] batch 66/66 | loss=2.0002
   [val] batch 1/10 | loss=1.9648
   [val] batch 10/10 | loss=1.8951
Epoch 03 | train_macro_f1=0.0993 | val_macro_f1=0.0357

Epoch 4/12
   [train] batch 1/66 | loss=1.9010
   [train] batch 11/66 | loss=1.9358
   [train] batch 21/66 | loss=1.9851
   [train] batch 31/66 | loss=1.9612
   [train] batch 41/66 | loss=1.9790
   [train] batch 51/66 | loss=1.9424
   [train] batch 61/66 | loss=2.0273
   [train] batch 66/66 | loss=1.9111
   [val] batch 1/10 | loss=1.8435
   [val] batch 10/10 | loss=2.1508
Epoch 04 | train_macro_f1=0.0889 | val_macro_f1=0.0613

Epoch 5/12
   [train] batch 1/66 | loss=1.9515
   [train] batch 11/66 | loss=2.0441
   [train] batch 21/66 | loss=1.8966
   [train] batch 31/66 | loss=1.9321
   [train] batch 41/66 | loss=2.0099
   [train] batch 51/66 | loss=1.9122
   [train] batch 61/66 | loss=2.0114
   [train] batch 66/66 | loss=1.9006
   [val] batch 1/10 | loss=1.9205
   [val] batch 10/10 | loss=2.1309
Epoch 05 | train_macro_f1=0.1408 | val_macro_f1=0.0565

Epoch 6/12
   [train] batch 1/66 | loss=1.9049
   [train] batch 11/66 | loss=2.0128
   [train] batch 21/66 | loss=1.8832
   [train] batch 31/66 | loss=1.9398
   [train] batch 41/66 | loss=1.4513
   [train] batch 51/66 | loss=1.8429
   [train] batch 61/66 | loss=1.9191
   [train] batch 66/66 | loss=1.6078
   [val] batch 1/10 | loss=2.1765
   [val] batch 10/10 | loss=1.9883
Epoch 06 | train_macro_f1=0.2092 | val_macro_f1=0.0336

Epoch 7/12
   [train] batch 1/66 | loss=1.9678
   [train] batch 11/66 | loss=1.6162
   [train] batch 21/66 | loss=1.0276
   [train] batch 31/66 | loss=2.2552
   [train] batch 41/66 | loss=1.8914
   [train] batch 51/66 | loss=1.8545
   [train] batch 61/66 | loss=1.9443
   [train] batch 66/66 | loss=1.9725
   [val] batch 1/10 | loss=2.0140
   [val] batch 10/10 | loss=1.9871
Epoch 07 | train_macro_f1=0.2104 | val_macro_f1=0.0361

Epoch 8/12
   [train] batch 1/66 | loss=1.9083
   [train] batch 11/66 | loss=1.9363
   [train] batch 21/66 | loss=1.8691
   [train] batch 31/66 | loss=1.6726
   [train] batch 41/66 | loss=1.9462
   [train] batch 51/66 | loss=1.7982
   [train] batch 61/66 | loss=1.5780
   [train] batch 66/66 | loss=1.9596
   [val] batch 1/10 | loss=1.8344
   [val] batch 10/10 | loss=2.3688
Epoch 08 | train_macro_f1=0.2473 | val_macro_f1=0.2016

Epoch 9/12
   [train] batch 1/66 | loss=2.0150
   [train] batch 11/66 | loss=2.4363
   [train] batch 21/66 | loss=1.6097
   [train] batch 31/66 | loss=1.4366
   [train] batch 41/66 | loss=1.6220
   [train] batch 51/66 | loss=1.1145
   [train] batch 61/66 | loss=1.4396
   [train] batch 66/66 | loss=1.7990
   [val] batch 1/10 | loss=2.5173
   [val] batch 10/10 | loss=1.2494
Epoch 09 | train_macro_f1=0.3430 | val_macro_f1=0.2279

Epoch 10/12
   [train] batch 1/66 | loss=1.1280
   [train] batch 11/66 | loss=1.0067
   [train] batch 21/66 | loss=1.1759
   [train] batch 31/66 | loss=1.3524
   [train] batch 41/66 | loss=1.2304
   [train] batch 51/66 | loss=1.1126
   [train] batch 61/66 | loss=2.3196
   [train] batch 66/66 | loss=1.8117
   [val] batch 1/10 | loss=1.4852
   [val] batch 10/10 | loss=3.0680
Epoch 10 | train_macro_f1=0.4558 | val_macro_f1=0.2919

Epoch 11/12
   [train] batch 1/66 | loss=1.1119
   [train] batch 11/66 | loss=1.7079
   [train] batch 21/66 | loss=1.7278
   [train] batch 31/66 | loss=1.6973
   [train] batch 41/66 | loss=1.4584
   [train] batch 51/66 | loss=1.1989
   [train] batch 61/66 | loss=0.8800
   [train] batch 66/66 | loss=1.0023
   [val] batch 1/10 | loss=1.5113
   [val] batch 10/10 | loss=1.6945
Epoch 11 | train_macro_f1=0.4639 | val_macro_f1=0.4257

Epoch 12/12
   [train] batch 1/66 | loss=1.2534
   [train] batch 11/66 | loss=1.1393
   [train] batch 21/66 | loss=0.8530
   [train] batch 31/66 | loss=0.9822
   [train] batch 41/66 | loss=1.0585
   [train] batch 51/66 | loss=0.9857
   [train] batch 61/66 | loss=0.7296
   [train] batch 66/66 | loss=0.3576
   [val] batch 1/10 | loss=2.7596
   [val] batch 10/10 | loss=0.9383
Epoch 12 | train_macro_f1=0.6377 | val_macro_f1=0.4495
{
  "protocol_name": "protocol_A",
  "frame_source": "RGB",
  "model_name": "vit_b_16",
  "num_sample_frames": 32,
  "batch_size": 8,
  "best_epoch": 12,
  "best_val_macro_f1": 0.44953368523162573,
  "test_accuracy": 0.5782312925170068,
  "test_macro_f1": 0.5292908130346554,
  "test_weighted_f1": 0.5292908130346554,
  "per_class_f1": {
    "doctor": 0.5517241379310345,
    "emergency": 0.75,
    "fire": 0.6923076923076923,
    "help": 0.6,
    "robbery": 0.0,
    "sit_down": 0.43243243243243246,
    "stand_up": 0.6785714285714286
  },
  "train_time_minutes": 84.56503231525421,
  "inference_time_seconds": 149.88965344429016,
  "videos_per_second": 0.9807214615692993,
  "train_rows": 525,
  "val_rows": 77,
  "test_rows": 147,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_A__rgb__vit_b_16__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_A__rgb__vit_b_16__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_A__rgb__vit_b_16__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_vit_convnext/protocol_A__rgb__vit_b_16__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_A | frame_source=RGB | model=convnext_tiny
====================================================================================================
train=525, val=77, test=147
Building sampled frame paths for 525 samples...
Building sampled frame paths for 77 samples...
Building sampled frame paths for 147 samples...

Downloading: "https://download.pytorch.org/models/convnext_tiny-983f1562.pth" to /home/sajjan/.cache/torch/hub/checkpoints/convnext_tiny-983f1562.pth
100%|██████████| 109M/109M [00:01<00:00, 72.2MB/s]

Epoch 1/12
   [train] batch 1/44 | loss=2.0033
   [train] batch 11/44 | loss=1.9479
   [train] batch 21/44 | loss=1.6495
   [train] batch 31/44 | loss=1.2455
   [train] batch 41/44 | loss=0.8984
   [train] batch 44/44 | loss=0.7895
   [val] batch 1/7 | loss=0.6843
   [val] batch 7/7 | loss=0.5423
Epoch 01 | train_macro_f1=0.3398 | val_macro_f1=0.7203

Epoch 2/12
   [train] batch 1/44 | loss=0.6291
   [train] batch 11/44 | loss=0.4694
   [train] batch 21/44 | loss=0.4239
   [train] batch 31/44 | loss=0.2873
   [train] batch 41/44 | loss=0.3066
   [train] batch 44/44 | loss=0.3534
   [val] batch 1/7 | loss=0.1940
   [val] batch 7/7 | loss=0.3632
Epoch 02 | train_macro_f1=0.8138 | val_macro_f1=0.8533

Epoch 3/12
   [train] batch 1/44 | loss=0.2332
   [train] batch 11/44 | loss=0.1210
   [train] batch 21/44 | loss=0.1058
   [train] batch 31/44 | loss=0.1412
   [train] batch 41/44 | loss=0.2613
   [train] batch 44/44 | loss=0.0367
   [val] batch 1/7 | loss=0.1843
   [val] batch 7/7 | loss=0.3724
Epoch 03 | train_macro_f1=0.8860 | val_macro_f1=0.8959

Epoch 4/12
   [train] batch 1/44 | loss=0.1897
   [train] batch 11/44 | loss=0.5600
   [train] batch 21/44 | loss=0.0390
   [train] batch 31/44 | loss=0.0729
   [train] batch 41/44 | loss=0.1610
   [train] batch 44/44 | loss=0.4156
   [val] batch 1/7 | loss=0.2366
   [val] batch 7/7 | loss=0.2899
Epoch 04 | train_macro_f1=0.9411 | val_macro_f1=0.8819

Epoch 5/12
   [train] batch 1/44 | loss=0.0324
   [train] batch 11/44 | loss=0.1642
   [train] batch 21/44 | loss=0.0276
   [train] batch 31/44 | loss=0.0225
   [train] batch 41/44 | loss=0.0480
   [train] batch 44/44 | loss=0.0289
   [val] batch 1/7 | loss=0.1570
   [val] batch 7/7 | loss=0.7753
Epoch 05 | train_macro_f1=0.9506 | val_macro_f1=0.8954

Epoch 6/12
   [train] batch 1/44 | loss=0.0275
   [train] batch 11/44 | loss=0.2157
   [train] batch 21/44 | loss=0.0184
   [train] batch 31/44 | loss=0.0289
   [train] batch 41/44 | loss=0.0173
   [train] batch 44/44 | loss=0.2126
   [val] batch 1/7 | loss=0.3062
   [val] batch 7/7 | loss=0.1700
Epoch 06 | train_macro_f1=0.9753 | val_macro_f1=0.8944

Epoch 7/12
   [train] batch 1/44 | loss=0.0269
   [train] batch 11/44 | loss=0.1210
   [train] batch 21/44 | loss=0.2083
   [train] batch 31/44 | loss=0.0129
   [train] batch 41/44 | loss=0.1012
   [train] batch 44/44 | loss=0.0204
   [val] batch 1/7 | loss=0.2959
   [val] batch 7/7 | loss=0.6875
Epoch 07 | train_macro_f1=0.9694 | val_macro_f1=0.9214

Epoch 8/12
   [train] batch 1/44 | loss=0.0647
   [train] batch 11/44 | loss=0.1383
   [train] batch 21/44 | loss=0.0152
   [train] batch 31/44 | loss=0.0219
   [train] batch 41/44 | loss=0.0206
   [train] batch 44/44 | loss=0.0628
   [val] batch 1/7 | loss=0.1286
   [val] batch 7/7 | loss=0.6317
Epoch 08 | train_macro_f1=0.9810 | val_macro_f1=0.8829

Epoch 9/12
   [train] batch 1/44 | loss=0.1006
   [train] batch 11/44 | loss=0.0686
   [train] batch 21/44 | loss=0.0434
   [train] batch 31/44 | loss=0.0311
   [train] batch 41/44 | loss=0.0289
   [train] batch 44/44 | loss=0.0939
   [val] batch 1/7 | loss=0.3104
   [val] batch 7/7 | loss=0.3162
Epoch 09 | train_macro_f1=0.9791 | val_macro_f1=0.8807

Epoch 10/12
   [train] batch 1/44 | loss=0.0214
   [train] batch 11/44 | loss=0.0073
   [train] batch 21/44 | loss=0.1496
   [train] batch 31/44 | loss=0.0331
   [train] batch 41/44 | loss=0.0079
   [train] batch 44/44 | loss=0.0049
   [val] batch 1/7 | loss=0.4657
   [val] batch 7/7 | loss=0.4486
Epoch 10 | train_macro_f1=0.9924 | val_macro_f1=0.8688

Epoch 11/12
   [train] batch 1/44 | loss=0.0055
   [train] batch 11/44 | loss=0.0022
   [train] batch 21/44 | loss=0.0030
   [train] batch 31/44 | loss=0.0070
   [train] batch 41/44 | loss=0.0060
   [train] batch 44/44 | loss=0.0029
   [val] batch 1/7 | loss=0.4556
   [val] batch 7/7 | loss=0.4245
Epoch 11 | train_macro_f1=0.9962 | val_macro_f1=0.8807
Early stopping triggered.
{
  "protocol_name": "protocol_A",
  "frame_source": "RGB",
  "model_name": "convnext_tiny",
  "num_sample_frames": 32,
  "batch_size": 12,
  "best_epoch": 7,
  "best_val_macro_f1": 0.9214285714285715,
  "test_accuracy": 0.8435374149659864,
  "test_macro_f1": 0.8460392226590611,
  "test_weighted_f1": 0.8460392226590611,
  "per_class_f1": {
    "doctor": 0.95,
    "emergency": 0.8648648648648649,
    "fire": 0.875,
    "help": 0.975609756097561,
    "robbery": 0.8717948717948718,
    "sit_down": 0.6190476190476191,
    "stand_up": 0.7659574468085106
  },
  "train_time_minutes": 70.54685293038686,
  "inference_time_seconds": 80.27556848526001,
  "videos_per_second": 1.8311922640198026,
  "train_rows": 525,
  "val_rows": 77,
  "test_rows": 147,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_A__rgb__convnext_tiny__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_A__rgb__convnext_tiny__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_A__rgb__convnext_tiny__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_vit_convnext/protocol_A__rgb__convnext_tiny__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_4 | frame_source=RGB | model=vit_b_16
====================================================================================================
train=215, val=23, test=238
Building sampled frame paths for 215 samples...
Building sampled frame paths for 23 samples...
Building sampled frame paths for 238 samples...

Epoch 1/12
   [train] batch 1/27 | loss=1.8925
   [train] batch 11/27 | loss=1.7985
   [train] batch 21/27 | loss=2.1775
   [train] batch 27/27 | loss=1.8969
   [val] batch 1/3 | loss=2.0472
   [val] batch 3/3 | loss=1.9333
Epoch 01 | train_macro_f1=0.1044 | val_macro_f1=0.0229

Epoch 2/12
   [train] batch 1/27 | loss=1.9456
   [train] batch 11/27 | loss=1.9673
   [train] batch 21/27 | loss=2.0944
   [train] batch 27/27 | loss=2.0338
   [val] batch 1/3 | loss=1.8230
   [val] batch 3/3 | loss=1.9079
Epoch 02 | train_macro_f1=0.1008 | val_macro_f1=0.0591

Epoch 3/12
   [train] batch 1/27 | loss=1.9384
   [train] batch 11/27 | loss=1.8423
   [train] batch 21/27 | loss=2.0369
   [train] batch 27/27 | loss=2.1858
   [val] batch 1/3 | loss=2.1364
   [val] batch 3/3 | loss=2.0266
Epoch 03 | train_macro_f1=0.1172 | val_macro_f1=0.0119

Epoch 4/12
   [train] batch 1/27 | loss=1.9794
   [train] batch 11/27 | loss=1.9346
   [train] batch 21/27 | loss=1.9718
   [train] batch 27/27 | loss=1.9023
   [val] batch 1/3 | loss=1.9980
   [val] batch 3/3 | loss=2.0071
Epoch 04 | train_macro_f1=0.1031 | val_macro_f1=0.0119

Epoch 5/12
   [train] batch 1/27 | loss=1.8955
   [train] batch 11/27 | loss=1.9413
   [train] batch 21/27 | loss=1.7247
   [train] batch 27/27 | loss=1.4116
   [val] batch 1/3 | loss=1.5825
   [val] batch 3/3 | loss=1.7226
Epoch 05 | train_macro_f1=0.2529 | val_macro_f1=0.1667

Epoch 6/12
   [train] batch 1/27 | loss=1.2381
   [train] batch 11/27 | loss=0.8605
   [train] batch 21/27 | loss=0.9269
   [train] batch 27/27 | loss=0.6617
   [val] batch 1/3 | loss=1.1133
   [val] batch 3/3 | loss=1.7362
Epoch 06 | train_macro_f1=0.5464 | val_macro_f1=0.3527

Epoch 7/12
   [train] batch 1/27 | loss=1.6057
   [train] batch 11/27 | loss=0.5628
   [train] batch 21/27 | loss=0.3491
   [train] batch 27/27 | loss=0.5494
   [val] batch 1/3 | loss=1.4717
   [val] batch 3/3 | loss=1.4237
Epoch 07 | train_macro_f1=0.7136 | val_macro_f1=0.4488

Epoch 8/12
   [train] batch 1/27 | loss=0.2127
   [train] batch 11/27 | loss=0.7033
   [train] batch 21/27 | loss=0.5065
   [train] batch 27/27 | loss=0.7780
   [val] batch 1/3 | loss=0.4323
   [val] batch 3/3 | loss=1.3250
Epoch 08 | train_macro_f1=0.8308 | val_macro_f1=0.6061

Epoch 9/12
   [train] batch 1/27 | loss=0.9561
   [train] batch 11/27 | loss=0.8858
   [train] batch 21/27 | loss=0.4815
   [train] batch 27/27 | loss=0.4005
   [val] batch 1/3 | loss=1.4519
   [val] batch 3/3 | loss=0.7510
Epoch 09 | train_macro_f1=0.8252 | val_macro_f1=0.5760

Epoch 10/12
   [train] batch 1/27 | loss=0.2420
   [train] batch 11/27 | loss=0.2855
   [train] batch 21/27 | loss=0.1311
   [train] batch 27/27 | loss=0.0237
   [val] batch 1/3 | loss=0.9409
   [val] batch 3/3 | loss=0.9461
Epoch 10 | train_macro_f1=0.9180 | val_macro_f1=0.5405

Epoch 11/12
   [train] batch 1/27 | loss=0.1227
   [train] batch 11/27 | loss=0.1197
   [train] batch 21/27 | loss=0.0157
   [train] batch 27/27 | loss=0.0134
   [val] batch 1/3 | loss=1.0511
   [val] batch 3/3 | loss=0.7450
Epoch 11 | train_macro_f1=0.9520 | val_macro_f1=0.6162

Epoch 12/12
   [train] batch 1/27 | loss=0.0334
   [train] batch 11/27 | loss=0.6799
   [train] batch 21/27 | loss=0.0226
   [train] batch 27/27 | loss=1.0481
   [val] batch 1/3 | loss=1.8477
   [val] batch 3/3 | loss=1.5154
Epoch 12 | train_macro_f1=0.9523 | val_macro_f1=0.4694
{
  "protocol_name": "protocol_B_4_to_4",
  "frame_source": "RGB",
  "model_name": "vit_b_16",
  "num_sample_frames": 32,
  "batch_size": 8,
  "best_epoch": 11,
  "best_val_macro_f1": 0.6162131519274376,
  "test_accuracy": 0.9117647058823529,
  "test_macro_f1": 0.9093520236377379,
  "test_weighted_f1": 0.9093520236377377,
  "per_class_f1": {
    "doctor": 0.9428571428571428,
    "emergency": 1.0,
    "fire": 0.9714285714285714,
    "help": 0.9696969696969697,
    "robbery": 0.9393939393939394,
    "sit_down": 0.8148148148148148,
    "stand_up": 0.7272727272727273
  },
  "train_time_minutes": 13.47468273639679,
  "inference_time_seconds": 60.86904740333557,
  "videos_per_second": 3.910033262438699,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_4_to_4__rgb__vit_b_16__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_4_to_4__rgb__vit_b_16__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_4_to_4__rgb__vit_b_16__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_vit_convnext/protocol_B_4_to_4__rgb__vit_b_16__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_4 | frame_source=RGB | model=convnext_tiny
====================================================================================================
train=215, val=23, test=238
Building sampled frame paths for 215 samples...
Building sampled frame paths for 23 samples...
Building sampled frame paths for 238 samples...

Epoch 1/12
   [train] batch 1/18 | loss=2.1239
   [train] batch 11/18 | loss=1.7043
   [train] batch 18/18 | loss=1.4454
   [val] batch 1/2 | loss=1.5033
   [val] batch 2/2 | loss=1.5376
Epoch 01 | train_macro_f1=0.1947 | val_macro_f1=0.3448

Epoch 2/12
   [train] batch 1/18 | loss=1.1766
   [train] batch 11/18 | loss=1.0303
   [train] batch 18/18 | loss=1.0160
   [val] batch 1/2 | loss=0.8969
   [val] batch 2/2 | loss=0.8920
Epoch 02 | train_macro_f1=0.7001 | val_macro_f1=0.6780

Epoch 3/12
   [train] batch 1/18 | loss=0.7719
   [train] batch 11/18 | loss=0.4565
   [train] batch 18/18 | loss=0.4021
   [val] batch 1/2 | loss=0.5907
   [val] batch 2/2 | loss=0.5272
Epoch 03 | train_macro_f1=0.9062 | val_macro_f1=0.6304

Epoch 4/12
   [train] batch 1/18 | loss=0.4164
   [train] batch 11/18 | loss=0.2787
   [train] batch 18/18 | loss=0.1467
   [val] batch 1/2 | loss=0.4791
   [val] batch 2/2 | loss=0.4463
Epoch 04 | train_macro_f1=0.9670 | val_macro_f1=0.7985

Epoch 5/12
   [train] batch 1/18 | loss=0.1692
   [train] batch 11/18 | loss=0.1419
   [train] batch 18/18 | loss=0.2173
   [val] batch 1/2 | loss=0.4567
   [val] batch 2/2 | loss=0.4029
Epoch 05 | train_macro_f1=0.9857 | val_macro_f1=0.8462

Epoch 6/12
   [train] batch 1/18 | loss=0.0968
   [train] batch 11/18 | loss=0.0385
   [train] batch 18/18 | loss=0.0285
   [val] batch 1/2 | loss=0.6656
   [val] batch 2/2 | loss=0.3154
Epoch 06 | train_macro_f1=0.9905 | val_macro_f1=0.7600

Epoch 7/12
   [train] batch 1/18 | loss=0.0211
   [train] batch 11/18 | loss=0.0170
   [train] batch 18/18 | loss=0.0147
   [val] batch 1/2 | loss=0.4748
   [val] batch 2/2 | loss=0.2153
Epoch 07 | train_macro_f1=1.0000 | val_macro_f1=0.8912

Epoch 8/12
   [train] batch 1/18 | loss=0.0284
   [train] batch 11/18 | loss=0.0216
   [train] batch 18/18 | loss=0.0145
   [val] batch 1/2 | loss=0.5306
   [val] batch 2/2 | loss=0.2250
Epoch 08 | train_macro_f1=1.0000 | val_macro_f1=0.8912

Epoch 9/12
   [train] batch 1/18 | loss=0.0065
   [train] batch 11/18 | loss=0.0128
   [train] batch 18/18 | loss=0.0057
   [val] batch 1/2 | loss=0.6706
   [val] batch 2/2 | loss=0.2546
Epoch 09 | train_macro_f1=1.0000 | val_macro_f1=0.8186

Epoch 10/12
   [train] batch 1/18 | loss=0.0068
   [train] batch 11/18 | loss=0.0047
   [train] batch 18/18 | loss=0.0092
   [val] batch 1/2 | loss=0.6178
   [val] batch 2/2 | loss=0.2170
Epoch 10 | train_macro_f1=1.0000 | val_macro_f1=0.8912

Epoch 11/12
   [train] batch 1/18 | loss=0.0062
   [train] batch 11/18 | loss=0.0030
   [train] batch 18/18 | loss=0.0086
   [val] batch 1/2 | loss=0.6453
   [val] batch 2/2 | loss=0.2225
Epoch 11 | train_macro_f1=1.0000 | val_macro_f1=0.8571
Early stopping triggered.
{
  "protocol_name": "protocol_B_4_to_4",
  "frame_source": "RGB",
  "model_name": "convnext_tiny",
  "num_sample_frames": 32,
  "batch_size": 12,
  "best_epoch": 7,
  "best_val_macro_f1": 0.891156462585034,
  "test_accuracy": 0.9873949579831933,
  "test_macro_f1": 0.9873922313896356,
  "test_weighted_f1": 0.9873922313896357,
  "per_class_f1": {
    "doctor": 1.0,
    "emergency": 1.0,
    "fire": 1.0,
    "help": 1.0,
    "robbery": 1.0,
    "sit_down": 0.9565217391304348,
    "stand_up": 0.9552238805970149
  },
  "train_time_minutes": 12.690839131673178,
  "inference_time_seconds": 70.06055045127869,
  "videos_per_second": 3.3970615198849927,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_4_to_4__rgb__convnext_tiny__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_4_to_4__rgb__convnext_tiny__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_4_to_4__rgb__convnext_tiny__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_vit_convnext/protocol_B_4_to_4__rgb__convnext_tiny__f32__img224/best_model.pt"
}

====================================================================================================
RUNNING | protocol=protocol_B_4_to_6 | frame_source=RGB | model=vit_b_16
====================================================================================================
train=215, val=23, test=245
Building sampled frame paths for 215 samples...
Building sampled frame paths for 23 samples...
Building sampled frame paths for 245 samples...

Epoch 1/12
   [train] batch 1/27 | loss=2.1523
   [train] batch 11/27 | loss=1.8695
   [train] batch 21/27 | loss=1.5930
   [train] batch 27/27 | loss=1.6761
   [val] batch 1/3 | loss=1.2573
   [val] batch 3/3 | loss=1.3116
Epoch 01 | train_macro_f1=0.2443 | val_macro_f1=0.2905

Epoch 2/12
   [train] batch 1/27 | loss=1.1189
   [train] batch 11/27 | loss=1.0968
   [train] batch 21/27 | loss=0.7599
   [train] batch 27/27 | loss=0.5873
   [val] batch 1/3 | loss=1.4268
   [val] batch 3/3 | loss=1.1680
Epoch 02 | train_macro_f1=0.6214 | val_macro_f1=0.4381

Epoch 3/12
   [train] batch 1/27 | loss=0.7573
   [train] batch 11/27 | loss=0.4163
   [train] batch 21/27 | loss=0.2892
   [train] batch 27/27 | loss=0.2536
   [val] batch 1/3 | loss=0.6955
   [val] batch 3/3 | loss=0.3817
Epoch 03 | train_macro_f1=0.8352 | val_macro_f1=0.6908

Epoch 4/12
   [train] batch 1/27 | loss=0.6768
   [train] batch 11/27 | loss=0.2102
   [train] batch 21/27 | loss=0.5872
   [train] batch 27/27 | loss=0.3379
   [val] batch 1/3 | loss=0.5694
   [val] batch 3/3 | loss=0.5788
Epoch 04 | train_macro_f1=0.8539 | val_macro_f1=0.6481

Epoch 5/12
   [train] batch 1/27 | loss=0.2566
   [train] batch 11/27 | loss=0.0782
   [train] batch 21/27 | loss=0.1371
   [train] batch 27/27 | loss=0.2970
   [val] batch 1/3 | loss=0.5056
   [val] batch 3/3 | loss=0.3691
Epoch 05 | train_macro_f1=0.9475 | val_macro_f1=0.7512

Epoch 6/12
   [train] batch 1/27 | loss=0.0831
   [train] batch 11/27 | loss=0.0128
   [train] batch 21/27 | loss=0.0837
   [train] batch 27/27 | loss=0.0084
   [val] batch 1/3 | loss=0.6115
   [val] batch 3/3 | loss=0.3158
Epoch 06 | train_macro_f1=0.9763 | val_macro_f1=0.7170

Epoch 7/12
   [train] batch 1/27 | loss=0.0327
   [train] batch 11/27 | loss=0.3159
   [train] batch 21/27 | loss=0.4085
   [train] batch 27/27 | loss=0.3890
   [val] batch 1/3 | loss=1.0307
   [val] batch 3/3 | loss=0.4548
Epoch 07 | train_macro_f1=0.9186 | val_macro_f1=0.7381

Epoch 8/12
   [train] batch 1/27 | loss=0.0481
   [train] batch 11/27 | loss=0.0206
   [train] batch 21/27 | loss=0.0070
   [train] batch 27/27 | loss=0.0985
   [val] batch 1/3 | loss=1.6644
   [val] batch 3/3 | loss=0.2471
Epoch 08 | train_macro_f1=0.9857 | val_macro_f1=0.6775

Epoch 9/12
   [train] batch 1/27 | loss=0.0447
   [train] batch 11/27 | loss=0.0142
   [train] batch 21/27 | loss=0.0032
   [train] batch 27/27 | loss=0.0172
   [val] batch 1/3 | loss=0.9708
   [val] batch 3/3 | loss=0.1407
Epoch 09 | train_macro_f1=1.0000 | val_macro_f1=0.7997

Epoch 10/12
   [train] batch 1/27 | loss=0.0116
   [train] batch 11/27 | loss=0.0097
   [train] batch 21/27 | loss=0.0073
   [train] batch 27/27 | loss=0.0059
   [val] batch 1/3 | loss=1.4314
   [val] batch 3/3 | loss=0.1003
Epoch 10 | train_macro_f1=1.0000 | val_macro_f1=0.7282

Epoch 11/12
   [train] batch 1/27 | loss=0.0030
   [train] batch 11/27 | loss=0.0030
   [train] batch 21/27 | loss=0.0032
   [train] batch 27/27 | loss=0.0059
   [val] batch 1/3 | loss=1.4510
   [val] batch 3/3 | loss=0.0834
Epoch 11 | train_macro_f1=1.0000 | val_macro_f1=0.7282

Epoch 12/12
   [train] batch 1/27 | loss=0.0067
   [train] batch 11/27 | loss=0.0021
   [train] batch 21/27 | loss=0.0022
   [train] batch 27/27 | loss=0.0018
   [val] batch 1/3 | loss=1.4581
   [val] batch 3/3 | loss=0.0800
Epoch 12 | train_macro_f1=1.0000 | val_macro_f1=0.7282
{
  "protocol_name": "protocol_B_4_to_6",
  "frame_source": "RGB",
  "model_name": "vit_b_16",
  "num_sample_frames": 32,
  "batch_size": 8,
  "best_epoch": 9,
  "best_val_macro_f1": 0.7997113997113996,
  "test_accuracy": 0.8,
  "test_macro_f1": 0.7958796812460651,
  "test_weighted_f1": 0.7958796812460652,
  "per_class_f1": {
    "doctor": 0.7719298245614035,
    "emergency": 0.9295774647887324,
    "fire": 0.8947368421052632,
    "help": 0.8955223880597015,
    "robbery": 0.7951807228915663,
    "sit_down": 0.6,
    "stand_up": 0.6842105263157895
  },
  "train_time_minutes": 14.897252186139424,
  "inference_time_seconds": 192.28801679611206,
  "videos_per_second": 1.2741303596665612,
  "train_rows": 215,
  "val_rows": 23,
  "test_rows": 245,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_4_to_6__rgb__vit_b_16__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_4_to_6__rgb__vit_b_16__f32__img224/classification_report.csv",

In [1]:
# ============================================================
# OPTIMIZED RESUMABLE RUNNER — ViT-B/16 + ConvNeXt-Tiny
# Fixes: OOM from torch.compile CUDA graphs, proper batch sizes
# Tuned for NVIDIA H100 NVL with other processes sharing GPU
# ============================================================

import os, gc, json, time, copy, random, warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision.models import (
    vit_b_16, ViT_B_16_Weights,
    convnext_tiny, ConvNeXt_Tiny_Weights,
)

warnings.filterwarnings("ignore")

# ── tell PyTorch allocator to avoid fragmentation ───────────
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

# ============================================================
# 1. SETTINGS
# ============================================================
SEED              = 42
IMG_SIZE          = 224
NUM_SAMPLE_FRAMES = 32

# Safe batch sizes given ~15 GB free on a shared H100
# (B × T frames go through model at once: B*32 forward passes)
BATCH_SIZE_BY_MODEL = {
    "vit_b_16":      16,   # 16 videos × 32 frames = 512 forward passes per step
    "convnext_tiny": 24,   # 24 × 32 = 768 forward passes per step
}

EPOCHS       = 12
LR           = 1e-4
WEIGHT_DECAY = 1e-4
PATIENCE     = 4

USE_AMP           = True
USE_PRETRAINED    = True
USE_TORCH_COMPILE = False   # DISABLED — causes 64 GB CUDA graph pre-allocation = OOM

# Gradient accumulation: effectively doubles batch without extra VRAM
# Set to 2 → effective batch = 2× above values
GRAD_ACCUM_STEPS = 2

# DataLoader
NUM_WORKERS        = 8    # safe default; raise if CPU is not bottleneck
PIN_MEMORY         = True
PERSISTENT_WORKERS = True
PREFETCH_FACTOR    = 2

SAMPLE_START_FRAC = 0.10
SAMPLE_END_FRAC   = 0.90
SKIP_IF_METRICS_EXISTS = True

FRAME_SOURCES = ["RGB", "RGB_BGREM"]
MODELS_TO_RUN = ["vit_b_16", "convnext_tiny"]

SPLIT_CONFIGS = [
    ("protocol_A",            "protocol_A_train.csv",            "protocol_A_val.csv",  "protocol_A_test.csv"),
    ("protocol_B_4_to_4",     "protocol_B_train_4_test_4.csv",   None, "protocol_B_test_4_same.csv"),
    ("protocol_B_4_to_6",     "protocol_B_train_4_test_6.csv",   None, "protocol_B_test_6.csv"),
    ("protocol_B_4_to_8",     "protocol_B_train_4_test_8.csv",   None, "protocol_B_test_8.csv"),
    ("protocol_B_6_to_4",     "protocol_B_train_6_test_4.csv",   None, "protocol_B_test_4.csv"),
    ("protocol_B_6_to_6",     "protocol_B_train_6_test_6.csv",   None, "protocol_B_test_6_same.csv"),
    ("protocol_B_6_to_8",     "protocol_B_train_6_test_8.csv",   None, "protocol_B_test_8.csv"),
    ("protocol_B_8_to_4",     "protocol_B_train_8_test_4.csv",   None, "protocol_B_test_4.csv"),
    ("protocol_B_8_to_6",     "protocol_B_train_8_test_6.csv",   None, "protocol_B_test_6.csv"),
    ("protocol_B_8_to_8",     "protocol_B_train_8_test_8.csv",   None, "protocol_B_test_8_same.csv"),
    ("protocol_B_4_6_to_4",   "protocol_B_train_4_6_test_4.csv", None, "protocol_B_test_4_from_4_6.csv"),
    ("protocol_B_4_6_to_6",   "protocol_B_train_4_6_test_6.csv", None, "protocol_B_test_6_from_4_6.csv"),
    ("protocol_B_4_6_to_8",   "protocol_B_train_4_6_test_8.csv", None, "protocol_B_test_8_from_4_6.csv"),
    ("protocol_B_4_8_to_4",   "protocol_B_train_4_8_test_4.csv", None, "protocol_B_test_4_from_4_8.csv"),
    ("protocol_B_4_8_to_6",   "protocol_B_train_4_8_test_6.csv", None, "protocol_B_test_6_from_4_8.csv"),
    ("protocol_B_4_8_to_8",   "protocol_B_train_4_8_test_8.csv", None, "protocol_B_test_8_from_4_8.csv"),
    ("protocol_B_6_8_to_4",   "protocol_B_train_6_8_test_4.csv", None, "protocol_B_test_4_from_6_8.csv"),
    ("protocol_B_6_8_to_6",   "protocol_B_train_6_8_test_6.csv", None, "protocol_B_test_6_from_6_8.csv"),
    ("protocol_B_6_8_to_8",   "protocol_B_train_6_8_test_8.csv", None, "protocol_B_test_8_from_6_8.csv"),
    ("protocol_B_4_6_8_to_4", "protocol_B_train_4_6_8_test_4.csv", None, "protocol_B_test_4_from_4_6_8.csv"),
    ("protocol_B_4_6_8_to_6", "protocol_B_train_4_6_8_test_6.csv", None, "protocol_B_test_6_from_4_6_8.csv"),
    ("protocol_B_4_6_8_to_8", "protocol_B_train_4_6_8_test_8.csv", None, "protocol_B_test_8_from_4_6_8.csv"),
]

CLASS_NAMES = ["doctor", "emergency", "fire", "help", "robbery", "sit_down", "stand_up"]
label2id    = {c: i for i, c in enumerate(CLASS_NAMES)}
id2label    = {i: c for c, i in label2id.items()}
NUM_CLASSES = len(CLASS_NAMES)

# ============================================================
# 2. SEED & DEVICE
# ============================================================
def set_seed(seed=42):
    random.seed(seed); np.random.seed(seed)
    torch.manual_seed(seed); torch.cuda.manual_seed_all(seed)

set_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)
if torch.cuda.is_available():
    props = torch.cuda.get_device_properties(0)
    free, total = torch.cuda.mem_get_info(0)
    print(f"GPU : {props.name}")
    print(f"VRAM: {total/1e9:.1f} GB total | {free/1e9:.1f} GB free right now")

torch.backends.cudnn.benchmark        = True
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32       = True
try:
    torch.set_float32_matmul_precision("high")
except Exception:
    pass

# ============================================================
# 3. PATHS
# ============================================================
cwd  = Path.cwd()
ROOT = cwd.parent if cwd.name == "notebooks" else cwd

SPLIT_DIR         = ROOT / "data" / "processed" / "splits"
MANIFEST_DIR      = ROOT / "data" / "processed" / "manifests"
FRAME_SUMMARY_CSV = MANIFEST_DIR / "frame_extraction_trimmed_summary.csv"

RESULTS_ROOT    = ROOT / "results"     / "stage5_vit_convnext"
CHECKPOINT_ROOT = ROOT / "checkpoints" / "stage5_vit_convnext"
LOG_ROOT        = ROOT / "logs"        / "stage5_vit_convnext"

for d in [RESULTS_ROOT, CHECKPOINT_ROOT, LOG_ROOT]:
    d.mkdir(parents=True, exist_ok=True)

print("ROOT:", ROOT)
if not FRAME_SUMMARY_CSV.exists():
    raise FileNotFoundError(f"Missing: {FRAME_SUMMARY_CSV}")

# ============================================================
# 4. FRAME SUMMARY
# ============================================================
frame_df_all = pd.read_csv(FRAME_SUMMARY_CSV)
frame_df_all = frame_df_all[frame_df_all["status"] == "success"].copy()
frame_df_all = (frame_df_all[["pair_id", "modality", "output_dir", "frames_extracted"]]
                .drop_duplicates())

# ============================================================
# 5. HELPERS
# ============================================================
def sample_indices_middle_region(n_total, n_samples, s=0.10, e=0.90):
    if n_total <= 0:
        return [0] * n_samples
    si = max(0, min(int(round(s * (n_total - 1))), n_total - 1))
    ei = max(si, min(int(round(e * (n_total - 1))), n_total - 1))
    return np.clip(np.round(np.linspace(si, ei, n_samples)).astype(int), 0, n_total - 1).tolist()

def frame_index_to_path(frame_dir, idx):
    return Path(frame_dir) / f"frame_{idx+1:06d}.jpg"

def load_split_df(csv_name):
    p = SPLIT_DIR / csv_name
    if not p.exists():
        raise FileNotFoundError(f"Missing split: {p}")
    df = pd.read_csv(p)
    if "is_valid_pair" in df.columns:
        df = df[df["is_valid_pair"] == True].copy()
    return df.reset_index(drop=True)

def attach_labels(df_):
    out = df_[df_["gesture"].isin(CLASS_NAMES)].copy()
    out["label"] = out["gesture"].map(label2id)
    return out.reset_index(drop=True)

def attach_frame_info(df_, frame_source):
    sub = (frame_df_all[frame_df_all["modality"] == frame_source]
           .rename(columns={"output_dir": "frame_dir",
                            "frames_extracted": "num_frames_available"})
           [["pair_id", "frame_dir", "num_frames_available"]]
           .drop_duplicates())
    out = df_.merge(sub, on="pair_id", how="left")
    out = out[out["num_frames_available"].fillna(0) > 0].copy().reset_index(drop=True)
    out["num_frames_available"] = out["num_frames_available"].astype(int)
    return out

# ============================================================
# 6. TRANSFORMS
# ============================================================
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])
eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

# ============================================================
# 7. DATASET
# ============================================================
class FrameVotingDataset(Dataset):
    def __init__(self, df, transform, n_frames=32):
        self.df        = df.reset_index(drop=True).copy()
        self.transform = transform
        self.paths     = []
        print(f"  Building frame paths for {len(self.df)} samples...")
        for _, row in self.df.iterrows():
            idxs = sample_indices_middle_region(
                int(row["num_frames_available"]), n_frames,
                SAMPLE_START_FRAC, SAMPLE_END_FRAC)
            self.paths.append([frame_index_to_path(row["frame_dir"], i) for i in idxs])

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row   = self.df.iloc[idx]
        blank = torch.zeros(3, IMG_SIZE, IMG_SIZE)
        frames = []
        for p in self.paths[idx]:
            try:
                with Image.open(p) as f:
                    frames.append(self.transform(f.convert("RGB")))
            except Exception:
                frames.append(blank)
        return (
            torch.stack(frames),
            int(row["label"]),
            {"pair_id":    row["pair_id"],
             "subject_id": row["subject_id"],
             "distance":   row["distance"],
             "gesture":    row["gesture"],
             "frame_dir":  row["frame_dir"]},
        )

def collate_fn(batch):
    return (
        torch.stack([x[0] for x in batch]),
        torch.tensor([x[1] for x in batch], dtype=torch.long),
        [x[2] for x in batch],
    )

def make_loader(ds, batch_size, shuffle):
    kw = dict(dataset=ds, batch_size=batch_size, shuffle=shuffle,
              num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY,
              collate_fn=collate_fn, drop_last=False)
    if NUM_WORKERS > 0:
        kw["persistent_workers"] = PERSISTENT_WORKERS
        kw["prefetch_factor"]    = PREFETCH_FACTOR
    return DataLoader(**kw)

# ============================================================
# 8. MODEL — no torch.compile (avoids CUDA-graph OOM)
# ============================================================
def create_model(model_name, num_classes, pretrained=True):
    if model_name == "vit_b_16":
        m = vit_b_16(weights=ViT_B_16_Weights.DEFAULT if pretrained else None)
        m.heads.head = nn.Linear(m.heads.head.in_features, num_classes)
    elif model_name == "convnext_tiny":
        m = convnext_tiny(weights=ConvNeXt_Tiny_Weights.DEFAULT if pretrained else None)
        m.classifier[2] = nn.Linear(m.classifier[2].in_features, num_classes)
    else:
        raise ValueError(model_name)

    # channels_last speeds up ConvNeXt significantly on H100
    m = m.to(device).to(memory_format=torch.channels_last)
    return m

def forward_voting(model, frames):
    """Flatten B×T frames into one GPU call, then mean-pool logits."""
    B, T, C, H, W = frames.shape
    flat   = frames.view(B * T, C, H, W).contiguous(memory_format=torch.channels_last)
    logits = model(flat)              # (B*T, num_classes)
    return logits.view(B, T, -1).mean(1)   # (B, num_classes)

# ============================================================
# 9. ADAPTIVE BATCH SIZE — auto-reduce on OOM
# ============================================================
def safe_forward(model, frames, criterion, labels):
    """Try forward pass; if OOM, halve batch and retry (up to 3 times)."""
    for attempt in range(3):
        try:
            with torch.autocast("cuda", dtype=torch.float16,
                                enabled=(USE_AMP and device.type == "cuda")):
                logits = forward_voting(model, frames)
                loss   = criterion(logits, labels)
            return logits, loss, frames.shape[0]
        except torch.cuda.OutOfMemoryError:
            torch.cuda.empty_cache()
            half = frames.shape[0] // 2
            if half == 0:
                raise
            print(f"  ⚠ OOM — retrying with batch={half}")
            frames = frames[:half]
            labels = labels[:half]
    raise RuntimeError("Repeated OOM — reduce BATCH_SIZE_BY_MODEL manually.")

# ============================================================
# 10. TRAIN / EVAL LOOPS
# ============================================================
def run_epoch(model, loader, criterion, optimizer=None, scaler=None, train=True):
    model.train() if train else model.eval()
    total_loss, n_samples = 0.0, 0
    labels_all, preds_all = [], []
    n_batches = len(loader)

    accum_count = 0
    if train:
        optimizer.zero_grad(set_to_none=True)

    t_batch = time.time()

    for bi, (frames, labels, _) in enumerate(loader):
        frames = frames.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        with torch.set_grad_enabled(train):
            if train:
                with torch.autocast("cuda", dtype=torch.float16,
                                    enabled=(USE_AMP and device.type == "cuda")):
                    logits = forward_voting(model, frames)
                    loss   = criterion(logits, labels) / GRAD_ACCUM_STEPS
                scaler.scale(loss).backward()
                accum_count += 1
                if accum_count == GRAD_ACCUM_STEPS or bi == n_batches - 1:
                    scaler.unscale_(optimizer)
                    nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                    scaler.step(optimizer)
                    scaler.update()
                    optimizer.zero_grad(set_to_none=True)
                    accum_count = 0
            else:
                with torch.autocast("cuda", dtype=torch.float16,
                                    enabled=(USE_AMP and device.type == "cuda")):
                    logits = forward_voting(model, frames)
                    loss   = criterion(logits, labels)

        bs_actual = labels.size(0)
        total_loss += loss.item() * (GRAD_ACCUM_STEPS if train else 1) * bs_actual
        n_samples  += bs_actual
        preds = logits.detach().argmax(1)
        labels_all.extend(labels.cpu().numpy())
        preds_all.extend(preds.cpu().numpy())

        # print every 10 batches
        if bi % 10 == 0 or bi == n_batches - 1:
            elapsed = time.time() - t_batch
            vps     = n_samples / elapsed if elapsed > 0 else 0
            mode    = "train" if train else "val"
            print(f"  [{mode}] {bi+1:4d}/{n_batches} | "
                  f"loss={loss.item()*(GRAD_ACCUM_STEPS if train else 1):.4f} | "
                  f"{vps:.1f} vid/s", flush=True)

    return {
        "loss":        total_loss / max(n_samples, 1),
        "accuracy":    accuracy_score(labels_all, preds_all),
        "macro_f1":    f1_score(labels_all, preds_all, average="macro"),
        "weighted_f1": f1_score(labels_all, preds_all, average="weighted"),
    }

@torch.no_grad()
def predict(model, loader):
    model.eval()
    labels_all, preds_all, rows = [], [], []
    t0 = time.time()
    for frames, labels, metas in loader:
        frames = frames.to(device, non_blocking=True)
        with torch.autocast("cuda", dtype=torch.float16,
                            enabled=(USE_AMP and device.type == "cuda")):
            logits = forward_voting(model, frames)
            probs  = torch.softmax(logits, 1)
            preds  = probs.argmax(1)
        probs_np  = probs.cpu().numpy()
        preds_np  = preds.cpu().numpy()
        labels_np = labels.numpy()
        labels_all.extend(labels_np)
        preds_all.extend(preds_np)
        for i, meta in enumerate(metas):
            r = {"pair_id":      meta["pair_id"],
                 "subject_id":   meta["subject_id"],
                 "distance":     meta["distance"],
                 "gesture_true": id2label[int(labels_np[i])],
                 "gesture_pred": id2label[int(preds_np[i])],
                 "frame_dir":    meta["frame_dir"]}
            for ci, cn in id2label.items():
                r[f"prob_{cn}"] = float(probs_np[i][ci])
            rows.append(r)
    elapsed = time.time() - t0
    return labels_all, preds_all, pd.DataFrame(rows), elapsed, len(labels_all) / elapsed

# ============================================================
# 11. CHECKPOINT RESUME
# ============================================================
def load_checkpoint_if_exists(best_ckpt, model, optimizer, scaler):
    """
    Returns (start_epoch, best_val_f1, history).
    Looks for training_state.pt first (full resume),
    then falls back to best_model.pt (weights-only resume).
    """
    state_path = best_ckpt.parent / "training_state.pt"
    if state_path.exists():
        print(f"  ✔ Resuming full state from {state_path.name}")
        s = torch.load(state_path, map_location=device)
        model.load_state_dict(s["model_state_dict"])
        optimizer.load_state_dict(s["optimizer_state_dict"])
        scaler.load_state_dict(s["scaler_state_dict"])
        return s["epoch"] + 1, s["best_val_f1"], s.get("history", [])
    if best_ckpt.exists():
        print(f"  ✔ Found best_model.pt — loading weights, fresh optimizer")
        s = torch.load(best_ckpt, map_location=device)
        model.load_state_dict(s["model_state_dict"])
        return 1, -1.0, []
    print("  Starting fresh from epoch 1")
    return 1, -1.0, []

def save_training_state(best_ckpt, model, optimizer, scaler, epoch, best_val_f1, history):
    torch.save({
        "epoch":                epoch,
        "best_val_f1":          best_val_f1,
        "history":              history,
        "model_state_dict":     model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "scaler_state_dict":    scaler.state_dict(),
    }, best_ckpt.parent / "training_state.pt")

# ============================================================
# 12. SINGLE EXPERIMENT
# ============================================================
def run_experiment(protocol_name, train_csv, val_csv, test_csv, frame_source, model_name):
    print("\n" + "=" * 100)
    print(f"  protocol={protocol_name} | source={frame_source} | model={model_name}")
    print("=" * 100)

    run_name = (f"{protocol_name}__{frame_source.lower()}__{model_name}"
                f"__f{NUM_SAMPLE_FRAMES}__img{IMG_SIZE}")
    results_dir    = RESULTS_ROOT    / run_name
    checkpoint_dir = CHECKPOINT_ROOT / run_name
    log_dir        = LOG_ROOT        / run_name
    for d in [results_dir, checkpoint_dir, log_dir]:
        d.mkdir(parents=True, exist_ok=True)

    metrics_json = results_dir / "metrics.json"
    if SKIP_IF_METRICS_EXISTS and metrics_json.exists():
        print("  Already complete — skipping.")
        with open(metrics_json) as f:
            return json.load(f)

    # ── data ────────────────────────────────────────────────
    train_df = load_split_df(train_csv)
    test_df  = load_split_df(test_csv)
    if val_csv is None:
        train_df = train_df.sample(frac=1, random_state=SEED).reset_index(drop=True)
        n_val    = max(1, int(0.10 * len(train_df)))
        val_df   = train_df.iloc[:n_val].copy().reset_index(drop=True)
        train_df = train_df.iloc[n_val:].copy().reset_index(drop=True)
    else:
        val_df = load_split_df(val_csv)

    train_df = attach_frame_info(attach_labels(train_df), frame_source)
    val_df   = attach_frame_info(attach_labels(val_df),   frame_source)
    test_df  = attach_frame_info(attach_labels(test_df),  frame_source)
    print(f"  train={len(train_df)}, val={len(val_df)}, test={len(test_df)}")

    bs           = BATCH_SIZE_BY_MODEL[model_name]
    train_loader = make_loader(
        FrameVotingDataset(train_df, train_transform, NUM_SAMPLE_FRAMES), bs, True)
    val_loader   = make_loader(
        FrameVotingDataset(val_df,   eval_transform,  NUM_SAMPLE_FRAMES), bs, False)
    test_loader  = make_loader(
        FrameVotingDataset(test_df,  eval_transform,  NUM_SAMPLE_FRAMES), bs, False)

    # ── model + optimiser ────────────────────────────────────
    model     = create_model(model_name, NUM_CLASSES, USE_PRETRAINED)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    scaler    = torch.amp.GradScaler("cuda", enabled=(USE_AMP and device.type == "cuda"))
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=EPOCHS, eta_min=1e-6)

    best_ckpt = checkpoint_dir / "best_model.pt"

    # ── resume ───────────────────────────────────────────────
    start_epoch, best_val_f1, history = load_checkpoint_if_exists(
        best_ckpt, model, optimizer, scaler)

    best_state_dict       = None
    best_epoch            = max(start_epoch - 1, 0)
    epochs_no_improvement = 0

    if history:
        # reconstruct patience counter from saved history
        epochs_no_improvement = 0
        for h in reversed(history):
            if h["val_macro_f1"] < best_val_f1:
                epochs_no_improvement += 1
            else:
                break
        print(f"  Resuming epoch {start_epoch} | best_f1={best_val_f1:.4f} | "
              f"patience={epochs_no_improvement}/{PATIENCE}")

    # advance scheduler to match already-done epochs
    for _ in range(start_epoch - 1):
        scheduler.step()

    # ── training ─────────────────────────────────────────────
    train_start = time.time()

    for epoch in range(start_epoch, EPOCHS + 1):
        lr_now = scheduler.get_last_lr()[0] if epoch > 1 else LR
        print(f"\nEpoch {epoch}/{EPOCHS}  lr={lr_now:.2e}")

        tr = run_epoch(model, train_loader, criterion, optimizer, scaler, train=True)
        va = run_epoch(model, val_loader,   criterion, train=False)
        scheduler.step()

        row = {
            "epoch":            epoch,
            "train_loss":       tr["loss"],
            "train_acc":        tr["accuracy"],
            "train_macro_f1":   tr["macro_f1"],
            "train_weighted_f1":tr["weighted_f1"],
            "val_loss":         va["loss"],
            "val_acc":          va["accuracy"],
            "val_macro_f1":     va["macro_f1"],
            "val_weighted_f1":  va["weighted_f1"],
        }
        history.append(row)
        print(f"  → train_f1={tr['macro_f1']:.4f} | val_f1={va['macro_f1']:.4f}")

        if va["macro_f1"] > best_val_f1:
            best_val_f1           = va["macro_f1"]
            best_epoch            = epoch
            epochs_no_improvement = 0
            best_state_dict       = copy.deepcopy(model.state_dict())
            torch.save({"epoch": epoch, "model_state_dict": best_state_dict,
                        "model_name": model_name, "frame_source": frame_source,
                        "protocol_name": protocol_name,
                        "label2id": label2id, "id2label": id2label}, best_ckpt)
        else:
            epochs_no_improvement += 1

        # save full state every epoch for true resume
        save_training_state(best_ckpt, model, optimizer, scaler,
                            epoch, best_val_f1, history)
        pd.DataFrame(history).to_csv(log_dir / "training_log.csv", index=False)

        if epochs_no_improvement >= PATIENCE:
            print("  Early stopping.")
            break

    train_elapsed = time.time() - train_start

    # ── evaluation ───────────────────────────────────────────
    if best_state_dict is None:
        if best_ckpt.exists():
            best_state_dict = torch.load(best_ckpt, map_location=device)["model_state_dict"]
        else:
            raise RuntimeError("No checkpoint found.")
    model.load_state_dict(best_state_dict)

    test_labels, test_preds, pred_df, infer_t, vps = predict(model, test_loader)

    acc    = accuracy_score(test_labels, test_preds)
    mf1    = f1_score(test_labels, test_preds, average="macro")
    wf1    = f1_score(test_labels, test_preds, average="weighted")
    cm     = confusion_matrix(test_labels, test_preds)
    rep    = classification_report(test_labels, test_preds,
                                   target_names=[id2label[i] for i in range(NUM_CLASSES)],
                                   output_dict=True, zero_division=0)
    rep_df = pd.DataFrame(rep).transpose()

    pred_csv = results_dir / "test_predictions.csv"
    rep_csv  = results_dir / "classification_report.csv"
    cm_png   = results_dir / "confusion_matrix.png"

    pred_df.to_csv(pred_csv, index=False)
    rep_df.to_csv(rep_csv)

    fig, ax = plt.subplots(figsize=(8, 6))
    im = ax.imshow(cm, interpolation="nearest")
    ax.set_title(f"{protocol_name} | {frame_source} | {model_name}")
    plt.colorbar(im, ax=ax)
    ticks = np.arange(NUM_CLASSES)
    ax.set_xticks(ticks); ax.set_yticks(ticks)
    ax.set_xticklabels([id2label[i] for i in range(NUM_CLASSES)], rotation=45, ha="right")
    ax.set_yticklabels([id2label[i] for i in range(NUM_CLASSES)])
    ax.set_xlabel("Predicted"); ax.set_ylabel("True")
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, str(cm[i, j]), ha="center", va="center", fontsize=8)
    plt.tight_layout()
    plt.savefig(cm_png, dpi=150, bbox_inches="tight")
    plt.close()

    per_cls_f1 = {cn: float(rep_df.loc[cn, "f1-score"])
                  for cn in CLASS_NAMES if cn in rep_df.index}

    metrics = {
        "protocol_name":          protocol_name,
        "frame_source":           frame_source,
        "model_name":             model_name,
        "num_sample_frames":      NUM_SAMPLE_FRAMES,
        "batch_size":             bs,
        "effective_batch_size":   bs * GRAD_ACCUM_STEPS,
        "best_epoch":             int(best_epoch),
        "best_val_macro_f1":      float(best_val_f1),
        "test_accuracy":          float(acc),
        "test_macro_f1":          float(mf1),
        "test_weighted_f1":       float(wf1),
        "per_class_f1":           per_cls_f1,
        "train_time_minutes":     float(train_elapsed / 60),
        "inference_time_seconds": float(infer_t),
        "videos_per_second":      float(vps) if vps else None,
        "train_rows":             len(train_df),
        "val_rows":               len(val_df),
        "test_rows":              len(test_df),
        "predictions_csv":        str(pred_csv),
        "classification_report_csv": str(rep_csv),
        "confusion_matrix_png":   str(cm_png),
        "checkpoint_best":        str(best_ckpt),
    }

    with open(metrics_json, "w") as f:
        json.dump(metrics, f, indent=4)
    print(json.dumps({k: v for k, v in metrics.items()
                      if k not in ("per_class_f1",)}, indent=2))

    # ── free VRAM before next experiment ─────────────────────
    del model, train_loader, val_loader, test_loader, best_state_dict
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.synchronize()

    return metrics

# ============================================================
# 13. RUN ALL (resume-aware)
# ============================================================
summary_csv = RESULTS_ROOT / "stage5_vit_convnext_summary.csv"

all_metrics: list = []
if summary_csv.exists():
    try:
        all_metrics = pd.read_csv(summary_csv).to_dict(orient="records")
    except Exception:
        pass

done_keys = {(m["protocol_name"], m["frame_source"], m["model_name"])
             for m in all_metrics}

print(f"\nAlready done: {len(done_keys)} experiments")

for frame_source in FRAME_SOURCES:
    for protocol_name, train_csv, val_csv, test_csv in SPLIT_CONFIGS:
        for model_name in MODELS_TO_RUN:
            key = (protocol_name, frame_source, model_name)
            if SKIP_IF_METRICS_EXISTS and key in done_keys:
                print(f"  Skip (done): {key}")
                continue
            m = run_experiment(
                protocol_name, train_csv, val_csv, test_csv,
                frame_source, model_name)
            all_metrics.append(m)
            done_keys.add(key)
            pd.DataFrame(all_metrics).to_csv(summary_csv, index=False)

final_df = pd.DataFrame(all_metrics)
final_df.to_csv(summary_csv, index=False)

print("\n ALL DONE — summary:", summary_csv)
print(final_df[[
    "protocol_name", "frame_source", "model_name",
    "best_val_macro_f1", "test_accuracy", "test_macro_f1",
    "train_time_minutes", "videos_per_second",
]].sort_values(["protocol_name", "frame_source", "test_macro_f1"],
               ascending=[True, True, False]).to_string())

Device: cuda
GPU : NVIDIA H100 NVL
VRAM: 99.9 GB total | 90.6 GB free right now
ROOT: /data/Sajjan_Singh/gesture_recognition

Already done: 31 experiments
  Skip (done): ('protocol_A', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_A', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_4_to_4', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_4_to_4', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_4_to_6', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_4_to_6', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_4_to_8', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_4_to_8', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_6_to_4', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_6_to_4', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_6_to_6', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_6_to_6', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_6_to_8', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_6_to_8', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_8_to_4', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_8_to_4', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_8_to_6', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_8_to_6', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_8_to_8', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_8_to_8', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_4_6_to_4', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_4_6_to_4', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_4_6_to_6', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_4_6_to_6', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_4_6_to_8', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_4_6_to_8', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_4_8_to_4', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_4_8_to_4', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_4_8_to_6', 'RGB', 'vit_b_16')
  Skip (done): ('protocol_B_4_8_to_6', 'RGB', 'convnext_tiny')
  Skip (done): ('protocol_B_4_8_to_8', 'RGB', 'vit_b_16')

====================================================================================================
  protocol=protocol_B_4_8_to_8 | source=RGB | model=convnext_tiny
====================================================================================================
  train=454, val=50, test=266
  Building frame paths for 454 samples...
  Building frame paths for 50 samples...
  Building frame paths for 266 samples...
  Starting fresh from epoch 1

Epoch 1/12  lr=1.00e-04
  [train]    1/19 | loss=1.9757 | 0.3 vid/s
  [train]   11/19 | loss=1.9421 | 2.4 vid/s
  [train]   19/19 | loss=1.8412 | 2.4 vid/s
  [val]    1/3 | loss=1.8493 | 0.5 vid/s
  [val]    3/3 | loss=1.6924 | 1.0 vid/s
  → train_f1=0.1654 | val_f1=0.2143

Epoch 2/12  lr=9.83e-05
  [train]    1/19 | loss=1.7539 | 0.7 vid/s
  [train]   11/19 | loss=1.4318 | 2.4 vid/s
  [train]   19/19 | loss=1.2855 | 3.0 vid/s
  [val]    1/3 | loss=1.2872 | 0.5 vid/s
  [val]    3/3 | loss=1.3215 | 1.1 vid/s
  → train_f1=0.5497 | val_f1=0.4784

Epoch 3/12  lr=9.34e-05
  [train]    1/19 | loss=1.0929 | 0.5 vid/s
  [train]   11/19 | loss=0.9982 | 2.7 vid/s
  [train]   19/19 | loss=0.8071 | 3.5 vid/s
  [val]    1/3 | loss=0.8796 | 0.6 vid/s
  [val]    3/3 | loss=0.9585 | 1.3 vid/s
  → train_f1=0.7899 | val_f1=0.5210

Epoch 4/12  lr=8.55e-05
  [train]    1/19 | loss=0.6405 | 0.6 vid/s
  [train]   11/19 | loss=0.4970 | 2.9 vid/s
  [train]   19/19 | loss=0.3980 | 3.4 vid/s
  [val]    1/3 | loss=0.6645 | 0.5 vid/s
  [val]    3/3 | loss=0.6199 | 1.0 vid/s
  → train_f1=0.8531 | val_f1=0.6246

Epoch 5/12  lr=7.52e-05
  [train]    1/19 | loss=0.2679 | 0.5 vid/s
  [train]   11/19 | loss=0.4060 | 2.5 vid/s
  [train]   19/19 | loss=0.3067 | 3.0 vid/s
  [val]    1/3 | loss=0.6690 | 0.5 vid/s
  [val]    3/3 | loss=0.9174 | 1.1 vid/s
  → train_f1=0.9140 | val_f1=0.5994

Epoch 6/12  lr=6.33e-05
  [train]    1/19 | loss=0.3071 | 0.7 vid/s
  [train]   11/19 | loss=0.3258 | 2.5 vid/s
  [train]   19/19 | loss=0.1709 | 3.1 vid/s
  [val]    1/3 | loss=0.6149 | 0.5 vid/s
  [val]    3/3 | loss=0.7528 | 1.0 vid/s
  → train_f1=0.9516 | val_f1=0.6175

Epoch 7/12  lr=5.05e-05
  [train]    1/19 | loss=0.0934 | 0.5 vid/s
  [train]   11/19 | loss=0.1727 | 2.5 vid/s
  [train]   19/19 | loss=0.1021 | 3.2 vid/s
  [val]    1/3 | loss=0.5319 | 0.5 vid/s
  [val]    3/3 | loss=0.7059 | 1.0 vid/s
  → train_f1=0.9702 | val_f1=0.6676

Epoch 8/12  lr=3.77e-05
  [train]    1/19 | loss=0.1420 | 0.4 vid/s
  [train]   11/19 | loss=0.0978 | 2.5 vid/s
  [train]   19/19 | loss=0.0619 | 3.1 vid/s
  [val]    1/3 | loss=0.6419 | 0.5 vid/s
  [val]    3/3 | loss=1.0019 | 1.1 vid/s
  → train_f1=0.9930 | val_f1=0.6907

Epoch 9/12  lr=2.58e-05
  [train]    1/19 | loss=0.1006 | 0.5 vid/s
  [train]   11/19 | loss=0.0994 | 2.7 vid/s
  [train]   19/19 | loss=0.0616 | 3.2 vid/s
  [val]    1/3 | loss=0.5636 | 0.5 vid/s
  [val]    3/3 | loss=0.7140 | 1.1 vid/s
  → train_f1=0.9976 | val_f1=0.6802

Epoch 10/12  lr=1.55e-05
  [train]    1/19 | loss=0.0447 | 0.5 vid/s
  [train]   11/19 | loss=0.0488 | 2.8 vid/s
  [train]   19/19 | loss=0.0616 | 3.2 vid/s
  [val]    1/3 | loss=0.6402 | 0.6 vid/s
  [val]    3/3 | loss=0.9177 | 1.1 vid/s
  → train_f1=0.9976 | val_f1=0.6680

Epoch 11/12  lr=7.63e-06
  [train]    1/19 | loss=0.0687 | 0.5 vid/s
  [train]   11/19 | loss=0.0473 | 2.8 vid/s
  [train]   19/19 | loss=0.0385 | 3.2 vid/s
  [val]    1/3 | loss=0.6531 | 0.5 vid/s
  [val]    3/3 | loss=0.9698 | 1.1 vid/s
  → train_f1=0.9952 | val_f1=0.6529

Epoch 12/12  lr=2.69e-06
  [train]    1/19 | loss=0.0225 | 0.5 vid/s
  [train]   11/19 | loss=0.0231 | 2.5 vid/s
  [train]   19/19 | loss=0.0304 | 3.1 vid/s
  [val]    1/3 | loss=0.6188 | 0.5 vid/s
  [val]    3/3 | loss=0.8540 | 1.1 vid/s
  → train_f1=0.9952 | val_f1=0.6651
  Early stopping.
{
  "protocol_name": "protocol_B_4_8_to_8",
  "frame_source": "RGB",
  "model_name": "convnext_tiny",
  "num_sample_frames": 32,
  "batch_size": 24,
  "effective_batch_size": 48,
  "best_epoch": 8,
  "best_val_macro_f1": 0.6906995750245178,
  "test_accuracy": 0.9624060150375939,
  "test_macro_f1": 0.9622892544794689,
  "test_weighted_f1": 0.962289254479469,
  "train_time_minutes": 38.96535459359487,
  "inference_time_seconds": 139.81820917129517,
  "videos_per_second": 1.902470369035524,
  "train_rows": 454,
  "val_rows": 50,
  "test_rows": 266,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_4_8_to_8__rgb__convnext_tiny__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_4_8_to_8__rgb__convnext_tiny__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_4_8_to_8__rgb__convnext_tiny__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_vit_convnext/protocol_B_4_8_to_8__rgb__convnext_tiny__f32__img224/best_model.pt"
}

====================================================================================================
  protocol=protocol_B_6_8_to_4 | source=RGB | model=vit_b_16
====================================================================================================
  train=460, val=51, test=238
  Building frame paths for 460 samples...
  Building frame paths for 51 samples...
  Building frame paths for 238 samples...
  Starting fresh from epoch 1

Epoch 1/12  lr=1.00e-04
  [train]    1/29 | loss=2.1329 | 0.4 vid/s
  [train]   11/29 | loss=2.0881 | 1.9 vid/s
  [train]   21/29 | loss=2.0110 | 2.4 vid/s
  [train]   29/29 | loss=1.9796 | 2.6 vid/s
  [val]    1/4 | loss=2.0331 | 0.4 vid/s
  [val]    4/4 | loss=2.1159 | 1.3 vid/s
  → train_f1=0.1264 | val_f1=0.0208

Epoch 2/12  lr=9.83e-05
  [train]    1/29 | loss=1.9296 | 0.4 vid/s
  [train]   11/29 | loss=2.0008 | 1.9 vid/s
  [train]   21/29 | loss=1.9087 | 2.4 vid/s
  [train]   29/29 | loss=1.8098 | 2.5 vid/s
  [val]    1/4 | loss=1.9921 | 0.4 vid/s
  [val]    4/4 | loss=2.0348 | 1.2 vid/s
  → train_f1=0.1070 | val_f1=0.0429

Epoch 3/12  lr=9.34e-05
  [train]    1/29 | loss=1.9357 | 0.4 vid/s
  [train]   11/29 | loss=2.0109 | 1.8 vid/s
  [train]   21/29 | loss=1.9310 | 2.4 vid/s
  [train]   29/29 | loss=1.8820 | 2.6 vid/s
  [val]    1/4 | loss=2.0725 | 0.4 vid/s
  [val]    4/4 | loss=1.9834 | 1.2 vid/s
  → train_f1=0.0999 | val_f1=0.1400

Epoch 4/12  lr=8.55e-05
  [train]    1/29 | loss=1.8950 | 0.3 vid/s
  [train]   11/29 | loss=1.7324 | 1.9 vid/s
  [train]   21/29 | loss=1.3184 | 2.4 vid/s
  [train]   29/29 | loss=1.1580 | 2.6 vid/s
  [val]    1/4 | loss=0.9804 | 0.4 vid/s
  [val]    4/4 | loss=1.5081 | 1.2 vid/s
  → train_f1=0.3857 | val_f1=0.5420

Epoch 5/12  lr=7.52e-05
  [train]    1/29 | loss=1.0168 | 0.3 vid/s
  [train]   11/29 | loss=0.6373 | 2.0 vid/s
  [train]   21/29 | loss=0.6544 | 2.5 vid/s
  [train]   29/29 | loss=0.5886 | 2.7 vid/s
  [val]    1/4 | loss=0.6805 | 0.4 vid/s
  [val]    4/4 | loss=0.6978 | 1.2 vid/s
  → train_f1=0.7126 | val_f1=0.5144

Epoch 6/12  lr=6.33e-05
  [train]    1/29 | loss=0.4899 | 0.4 vid/s
  [train]   11/29 | loss=0.8455 | 1.9 vid/s
  [train]   21/29 | loss=0.4335 | 2.4 vid/s
  [train]   29/29 | loss=0.3526 | 2.6 vid/s
  [val]    1/4 | loss=0.5374 | 0.4 vid/s
  [val]    4/4 | loss=0.4090 | 1.2 vid/s
  → train_f1=0.8438 | val_f1=0.7914

Epoch 7/12  lr=5.05e-05
  [train]    1/29 | loss=0.2723 | 0.4 vid/s
  [train]   11/29 | loss=0.5498 | 1.9 vid/s
  [train]   21/29 | loss=0.2012 | 2.4 vid/s
  [train]   29/29 | loss=0.1876 | 2.5 vid/s
  [val]    1/4 | loss=0.5932 | 0.4 vid/s
  [val]    4/4 | loss=0.1905 | 1.2 vid/s
  → train_f1=0.9242 | val_f1=0.8203

Epoch 8/12  lr=3.77e-05
  [train]    1/29 | loss=0.1256 | 0.4 vid/s
  [train]   11/29 | loss=0.2456 | 2.1 vid/s
  [train]   21/29 | loss=0.3602 | 2.6 vid/s
  [train]   29/29 | loss=0.2711 | 2.8 vid/s
  [val]    1/4 | loss=0.7565 | 0.4 vid/s
  [val]    4/4 | loss=0.1161 | 1.2 vid/s
  → train_f1=0.9425 | val_f1=0.7837

Epoch 9/12  lr=2.58e-05
  [train]    1/29 | loss=0.0788 | 0.4 vid/s
  [train]   11/29 | loss=0.0658 | 1.9 vid/s
  [train]   21/29 | loss=0.0889 | 2.5 vid/s
  [train]   29/29 | loss=0.0473 | 2.6 vid/s
  [val]    1/4 | loss=0.6624 | 0.4 vid/s
  [val]    4/4 | loss=0.0548 | 1.2 vid/s
  → train_f1=0.9680 | val_f1=0.8480

Epoch 10/12  lr=1.55e-05
  [train]    1/29 | loss=0.0611 | 0.4 vid/s
  [train]   11/29 | loss=0.0279 | 2.0 vid/s
  [train]   21/29 | loss=0.0556 | 2.5 vid/s
  [train]   29/29 | loss=0.0988 | 2.6 vid/s
  [val]    1/4 | loss=0.7862 | 0.4 vid/s
  [val]    4/4 | loss=0.0546 | 1.3 vid/s
  → train_f1=0.9912 | val_f1=0.7715

Epoch 11/12  lr=7.63e-06
  [train]    1/29 | loss=0.0748 | 0.5 vid/s
  [train]   11/29 | loss=0.0178 | 2.0 vid/s
  [train]   21/29 | loss=0.0177 | 2.5 vid/s
  [train]   29/29 | loss=0.0128 | 2.7 vid/s
  [val]    1/4 | loss=0.6823 | 0.4 vid/s
  [val]    4/4 | loss=0.0442 | 1.3 vid/s
  → train_f1=0.9978 | val_f1=0.7791

Epoch 12/12  lr=2.69e-06
  [train]    1/29 | loss=0.0172 | 0.4 vid/s
  [train]   11/29 | loss=0.0137 | 2.0 vid/s
  [train]   21/29 | loss=0.0141 | 2.5 vid/s
  [train]   29/29 | loss=0.0867 | 2.6 vid/s
  [val]    1/4 | loss=0.7544 | 0.4 vid/s
  [val]    4/4 | loss=0.0423 | 1.2 vid/s
  → train_f1=0.9956 | val_f1=0.7866
{
  "protocol_name": "protocol_B_6_8_to_4",
  "frame_source": "RGB",
  "model_name": "vit_b_16",
  "num_sample_frames": 32,
  "batch_size": 16,
  "effective_batch_size": 32,
  "best_epoch": 9,
  "best_val_macro_f1": 0.848037321236448,
  "test_accuracy": 0.8277310924369747,
  "test_macro_f1": 0.828433648506258,
  "test_weighted_f1": 0.828433648506258,
  "train_time_minutes": 44.14368170102437,
  "inference_time_seconds": 34.789498805999756,
  "videos_per_second": 6.841144833019405,
  "train_rows": 460,
  "val_rows": 51,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_6_8_to_4__rgb__vit_b_16__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_6_8_to_4__rgb__vit_b_16__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_6_8_to_4__rgb__vit_b_16__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_vit_convnext/protocol_B_6_8_to_4__rgb__vit_b_16__f32__img224/best_model.pt"
}

====================================================================================================
  protocol=protocol_B_6_8_to_4 | source=RGB | model=convnext_tiny
====================================================================================================
  train=460, val=51, test=238
  Building frame paths for 460 samples...
  Building frame paths for 51 samples...
  Building frame paths for 238 samples...
  Starting fresh from epoch 1

Epoch 1/12  lr=1.00e-04
  [train]    1/20 | loss=1.9377 | 0.4 vid/s
  [train]   11/20 | loss=1.9967 | 2.0 vid/s
  [train]   20/20 | loss=2.1055 | 2.3 vid/s
  [val]    1/3 | loss=2.0075 | 0.4 vid/s
  [val]    3/3 | loss=1.9346 | 0.9 vid/s
  → train_f1=0.1366 | val_f1=0.1083

Epoch 2/12  lr=9.83e-05
  [train]    1/20 | loss=1.7767 | 0.4 vid/s
  [train]   11/20 | loss=1.5869 | 1.9 vid/s
  [train]   20/20 | loss=1.5095 | 2.3 vid/s
  [val]    1/3 | loss=1.7205 | 0.4 vid/s
  [val]    3/3 | loss=1.8447 | 0.9 vid/s
  → train_f1=0.3505 | val_f1=0.2813

Epoch 3/12  lr=9.34e-05
  [train]    1/20 | loss=1.2767 | 0.4 vid/s
  [train]   11/20 | loss=1.1013 | 2.1 vid/s
  [train]   20/20 | loss=1.8219 | 2.4 vid/s
  [val]    1/3 | loss=1.2762 | 0.4 vid/s
  [val]    3/3 | loss=1.0312 | 0.9 vid/s
  → train_f1=0.7029 | val_f1=0.4828

Epoch 4/12  lr=8.55e-05
  [train]    1/20 | loss=0.7873 | 0.5 vid/s
  [train]   11/20 | loss=0.4743 | 2.0 vid/s
  [train]   20/20 | loss=0.2898 | 2.4 vid/s
  [val]    1/3 | loss=0.7173 | 0.4 vid/s
  [val]    3/3 | loss=0.5820 | 0.9 vid/s
  → train_f1=0.8195 | val_f1=0.7555

Epoch 5/12  lr=7.52e-05
  [train]    1/20 | loss=0.3763 | 0.4 vid/s
  [train]   11/20 | loss=0.3277 | 2.0 vid/s
  [train]   20/20 | loss=0.4669 | 2.3 vid/s
  [val]    1/3 | loss=0.5504 | 0.4 vid/s
  [val]    3/3 | loss=0.4177 | 0.9 vid/s
  → train_f1=0.9033 | val_f1=0.7615

Epoch 6/12  lr=6.33e-05
  [train]    1/20 | loss=0.2368 | 0.4 vid/s
  [train]   11/20 | loss=0.2083 | 2.1 vid/s
  [train]   20/20 | loss=0.1063 | 2.5 vid/s
  [val]    1/3 | loss=0.4912 | 0.4 vid/s
  [val]    3/3 | loss=0.3442 | 0.9 vid/s
  → train_f1=0.9363 | val_f1=0.7653

Epoch 7/12  lr=5.05e-05
  [train]    1/20 | loss=0.3143 | 0.4 vid/s
  [train]   11/20 | loss=0.1891 | 2.0 vid/s
  [train]   20/20 | loss=0.0280 | 2.3 vid/s
  [val]    1/3 | loss=0.3448 | 0.4 vid/s
  [val]    3/3 | loss=0.1581 | 0.9 vid/s
  → train_f1=0.9618 | val_f1=0.8189

Epoch 8/12  lr=3.77e-05
  [train]    1/20 | loss=0.2270 | 0.4 vid/s
  [train]   11/20 | loss=0.2286 | 1.8 vid/s
  [train]   20/20 | loss=0.0884 | 2.3 vid/s
  [val]    1/3 | loss=0.2426 | 0.4 vid/s
  [val]    3/3 | loss=0.1013 | 0.8 vid/s
  → train_f1=0.9681 | val_f1=0.8359

Epoch 9/12  lr=2.58e-05
  [train]    1/20 | loss=0.1896 | 0.4 vid/s
  [train]   11/20 | loss=0.0959 | 2.0 vid/s
  [train]   20/20 | loss=0.0842 | 2.4 vid/s
  [val]    1/3 | loss=0.2862 | 0.5 vid/s
  [val]    3/3 | loss=0.1094 | 0.9 vid/s
  → train_f1=0.9766 | val_f1=0.8540

Epoch 10/12  lr=1.55e-05
  [train]    1/20 | loss=0.0678 | 0.4 vid/s
  [train]   11/20 | loss=0.1842 | 1.9 vid/s
  [train]   20/20 | loss=0.0370 | 2.3 vid/s
  [val]    1/3 | loss=0.2398 | 0.4 vid/s
  [val]    3/3 | loss=0.0797 | 0.8 vid/s
  → train_f1=0.9871 | val_f1=0.9050

Epoch 11/12  lr=7.63e-06
  [train]    1/20 | loss=0.0618 | 0.3 vid/s
  [train]   11/20 | loss=0.1081 | 2.0 vid/s
  [train]   20/20 | loss=0.0668 | 2.5 vid/s
  [val]    1/3 | loss=0.2205 | 0.4 vid/s
  [val]    3/3 | loss=0.0659 | 0.9 vid/s
  → train_f1=0.9870 | val_f1=0.8546

Epoch 12/12  lr=2.69e-06
  [train]    1/20 | loss=0.0706 | 0.3 vid/s
  [train]   11/20 | loss=0.0740 | 1.8 vid/s
  [train]   20/20 | loss=0.0859 | 2.2 vid/s
  [val]    1/3 | loss=0.2235 | 0.4 vid/s
  [val]    3/3 | loss=0.0653 | 0.9 vid/s
  → train_f1=0.9956 | val_f1=0.8302
{
  "protocol_name": "protocol_B_6_8_to_4",
  "frame_source": "RGB",
  "model_name": "convnext_tiny",
  "num_sample_frames": 32,
  "batch_size": 24,
  "effective_batch_size": 48,
  "best_epoch": 10,
  "best_val_macro_f1": 0.9049640015157258,
  "test_accuracy": 0.8697478991596639,
  "test_macro_f1": 0.8720130658307437,
  "test_weighted_f1": 0.8720130658307437,
  "train_time_minutes": 50.93979539473852,
  "inference_time_seconds": 44.316328287124634,
  "videos_per_second": 5.370481021306698,
  "train_rows": 460,
  "val_rows": 51,
  "test_rows": 238,
  "predictions_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_6_8_to_4__rgb__convnext_tiny__f32__img224/test_predictions.csv",
  "classification_report_csv": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_6_8_to_4__rgb__convnext_tiny__f32__img224/classification_report.csv",
  "confusion_matrix_png": "/data/Sajjan_Singh/gesture_recognition/results/stage5_vit_convnext/protocol_B_6_8_to_4__rgb__convnext_tiny__f32__img224/confusion_matrix.png",
  "checkpoint_best": "/data/Sajjan_Singh/gesture_recognition/checkpoints/stage5_vit_convnext/protocol_B_6_8_to_4__rgb__convnext_tiny__f32__img224/best_model.pt"
}

====================================================================================================
  protocol=protocol_B_6_8_to_6 | source=RGB | model=vit_b_16
====================================================================================================
  train=460, val=51, test=245
  Building frame paths for 460 samples...
  Building frame paths for 51 samples...
  Building frame paths for 245 samples...
  Starting fresh from epoch 1

Epoch 1/12  lr=1.00e-04
  [train]    1/29 | loss=2.0396 | 0.3 vid/s
  [train]   11/29 | loss=1.9601 | 1.8 vid/s
  [train]   21/29 | loss=1.7693 | 2.3 vid/s
  [train]   29/29 | loss=1.4384 | 2.5 vid/s
  [val]    1/4 | loss=1.4850 | 0.4 vid/s
  [val]    4/4 | loss=1.5068 | 1.3 vid/s
  → train_f1=0.2318 | val_f1=0.4315

Epoch 2/12  lr=9.83e-05
  [train]    1/29 | loss=1.1252 | 0.4 vid/s
  [train]   11/29 | loss=1.1485 | 2.0 vid/s
  [train]   21/29 | loss=0.8933 | 2.3 vid/s
  [train]   29/29 | loss=0.9927 | 2.5 vid/s
  [val]    1/4 | loss=1.1129 | 0.4 vid/s
  [val]    4/4 | loss=1.0518 | 1.3 vid/s
  → train_f1=0.6265 | val_f1=0.5576

Epoch 3/12  lr=9.34e-05
  [train]    1/29 | loss=0.7877 | 0.3 vid/s
  [train]   11/29 | loss=0.6275 | 1.8 vid/s
  [train]   21/29 | loss=0.3604 | 2.4 vid/s
  [train]   29/29 | loss=0.3268 | 2.5 vid/s
  [val]    1/4 | loss=0.5937 | 0.5 vid/s
  [val]    4/4 | loss=0.5166 | 1.3 vid/s
  → train_f1=0.8157 | val_f1=0.8902

Epoch 4/12  lr=8.55e-05
  [train]    1/29 | loss=0.5616 | 0.4 vid/s
  [train]   11/29 | loss=0.2834 | 2.0 vid/s
  [train]   21/29 | loss=0.2690 | 2.4 vid/s
  [train]   29/29 | loss=0.2310 | 2.5 vid/s
  [val]    1/4 | loss=0.2511 | 0.4 vid/s
  [val]    4/4 | loss=0.1824 | 1.3 vid/s
  → train_f1=0.8761 | val_f1=0.8690

Epoch 5/12  lr=7.52e-05
  [train]    1/29 | loss=0.2446 | 0.4 vid/s
  [train]   11/29 | loss=0.1796 | 1.9 vid/s
  [train]   21/29 | loss=0.1491 | 2.4 vid/s
  [train]   29/29 | loss=0.1273 | 2.6 vid/s
  [val]    1/4 | loss=0.4178 | 0.4 vid/s
  [val]    4/4 | loss=0.1675 | 1.3 vid/s
  → train_f1=0.9338 | val_f1=0.8751

Epoch 6/12  lr=6.33e-05
  [train]    1/29 | loss=0.0666 | 0.4 vid/s
  [train]   11/29 | loss=0.0418 | 1.9 vid/s
  [train]   21/29 | loss=0.0940 | 2.5 vid/s
  [train]   29/29 | loss=0.2497 | 2.7 vid/s
  [val]    1/4 | loss=0.4229 | 0.4 vid/s
  [val]    4/4 | loss=0.6081 | 1.3 vid/s
  → train_f1=0.9545 | val_f1=0.7664

Epoch 7/12  lr=5.05e-05
  [train]    1/29 | loss=0.0837 | 0.4 vid/s
  [train]   11/29 | loss=0.0205 | 2.1 vid/s
  [train]   21/29 | loss=0.0159 | 2.4 vid/s